/**
 * Copyright (c) 2025-2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file reduce_std_v2_update_infershape.cpp
 * \brief ReduceStdV2Update 形状推导
 *
 * 输出 shape = x 沿 dim 归约后的 shape（keepdim=true 维度设 1，false 移除）。
 * axes 载体为 attr（ContinuousVector int64），非 axes tensor。
 * 空 axes 语义：dim 为空 → 展开为 [0..rank-1]（all-reduce，与 tiling 一致）。
 *
 * 复用 InferShape4ReduceStdFunc 模板的逻辑。
 */

#include "register/op_impl_registry.h"
#include "exe_graph/runtime/infer_shape_context.h"
#include "op_common/log/log.h"

#include <set>
#include <vector>
#include "util/shape_util.h"

using namespace ge;

namespace ops {

namespace {
// 输入/输出/属性的固定索引
constexpr size_t kInputXIdx = 0;
constexpr size_t kInputMeanIdx = 1;
constexpr size_t kOutputIdx = 0;
constexpr size_t kAttrDimIdx = 0;
constexpr size_t kAttrKeepDimIdx = 3; // def.cpp 属性顺序: dim(0), if_std(1), unbiased(2), keepdim(3), correction(4)
constexpr size_t kMaxSupportedRank = 8;

// 将 dim 属性（ContinuousVector int64）解析为归一化（非负、去重、排序）的 reduce 轴集合
static ge::graphStatus ParseAndNormalizeDim(const gert::InferShapeContext* context, int64_t rank,
                                            std::vector<int64_t>& reduceAxes)
{
    const auto* attrs = context->GetAttrs();
    OP_CHECK_NULL_WITH_CONTEXT(context, attrs);
    const gert::ContinuousVector* dimVec = attrs->GetAttrPointer<gert::ContinuousVector>(kAttrDimIdx);
    OP_CHECK_NULL_WITH_CONTEXT(context, dimVec);
    const int64_t effectiveRank = (rank == 0) ? 1 : rank;
    if (dimVec->GetSize() == 0) {
        // dim 为空 → 全归约 [0..rank-1]
        for (int64_t i = 0; i < rank; ++i) {
            reduceAxes.push_back(i);
        }
        return ge::GRAPH_SUCCESS;
    }
    const int64_t dimNum = static_cast<int64_t>(dimVec->GetSize());
    const int64_t* dimData = static_cast<const int64_t*>(dimVec->GetData());
    std::set<int64_t> seen;
    for (int64_t i = 0; i < dimNum; ++i) {
        int64_t v = dimData[i];
        OP_CHECK_IF(v < -effectiveRank || v >= effectiveRank,
                    OP_LOGE(context->GetNodeName(), "dim[%ld]=%ld out of range [-%ld, %ld)", i, v, effectiveRank,
                            effectiveRank),
                    return ge::GRAPH_FAILED);
        if (v < 0) {
            v += effectiveRank;
        }
        seen.insert(v);
    }
    reduceAxes.assign(seen.begin(), seen.end());
    return ge::GRAPH_SUCCESS;
}

} // namespace

static ge::graphStatus InferShape4ReduceStdV2Update(gert::InferShapeContext* context)
{
    const gert::Shape* xShape = context->GetInputShape(kInputXIdx);
    OP_CHECK_NULL_WITH_CONTEXT(context, xShape);
    const gert::Shape* meanShape = context->GetInputShape(kInputMeanIdx);
    OP_CHECK_NULL_WITH_CONTEXT(context, meanShape);

    gert::Shape* outShape = context->GetOutputShape(kOutputIdx);
    OP_CHECK_NULL_WITH_CONTEXT(context, outShape);

    const bool xUnknownRank = Ops::Base::IsUnknownRank(*xShape);
    const bool meanUnknownRank = Ops::Base::IsUnknownRank(*meanShape);
    if (!xUnknownRank) {
        const size_t xRank = xShape->GetDimNum();
        OP_CHECK_IF(xRank > kMaxSupportedRank,
                    OP_LOGE(context->GetNodeName(), "x rank=%zu exceeds supported range [0, 8]", xRank),
                    return ge::GRAPH_FAILED);
    }
    if (!xUnknownRank && !meanUnknownRank) {
        const size_t xRank = xShape->GetDimNum();
        const size_t meanRank = meanShape->GetDimNum();
        OP_CHECK_IF(meanRank != xRank, OP_LOGE(context->GetNodeName(), "mean rank=%zu != x rank=%zu", meanRank, xRank),
                    return ge::GRAPH_FAILED);
        for (size_t i = 0; i < xRank; ++i) {
            const int64_t xDim = xShape->GetDim(i);
            const int64_t meanDim = meanShape->GetDim(i);
            OP_CHECK_IF(xDim >= 0 && meanDim >= 0 && xDim != meanDim,
                        OP_LOGE(context->GetNodeName(), "mean dim[%zu]=%ld != x dim[%zu]=%ld", i, meanDim, i, xDim),
                        return ge::GRAPH_FAILED);
        }
    }

    if (xUnknownRank) {
        Ops::Base::SetUnknownRank(*outShape);
        return ge::GRAPH_SUCCESS;
    }

    const int64_t rank = static_cast<int64_t>(xShape->GetDimNum());
    std::vector<int64_t> reduceAxes;
    OP_CHECK_IF(ParseAndNormalizeDim(context, rank, reduceAxes) != ge::GRAPH_SUCCESS, , return ge::GRAPH_FAILED);

    // keepdim 兜底（OPTIONAL，用 nullptr 判断默认 false）
    const auto* attrs = context->GetAttrs();
    bool keepdim = false;
    if (attrs != nullptr) {
        const bool* keepdimPtr = attrs->GetAttrPointer<bool>(kAttrKeepDimIdx);
        if (keepdimPtr != nullptr) {
            keepdim = *keepdimPtr;
        }
    }

    // shape 推导：keepdim=true 维度设 1，false 移除
    std::set<int64_t> reduceSet(reduceAxes.begin(), reduceAxes.end());
    outShape->SetDimNum(0);
    for (int64_t i = 0; i < rank; ++i) {
        if (reduceSet.count(i) > 0) {
            if (keepdim) {
                outShape->AppendDim(1);
            }
            // keepdim=false 移除
        } else {
            outShape->AppendDim(xShape->GetDim(static_cast<size_t>(i)));
        }
    }

    // dtype 透传：output.dtype = x.dtype（由 OpDef .DataType(...) 声明自动处理，InferShape 无需显式设置）

    OP_LOGI(context, "[InferShape] output shape=%s", Ops::Base::ToString(*outShape).c_str());
    return ge::GRAPH_SUCCESS;
}

IMPL_OP_INFERSHAPE(ReduceStdV2Update).InferShape(InferShape4ReduceStdV2Update);

} // namespace ops
