/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */
#include <array>
#include <cstdlib>
#include "acl/acl.h"
#include <gmock/gmock.h>
#include "gtest/gtest.h"
#include <vector>

#include "../../../op_host/op_api/aclnn_weight_quant_preprocess.h"

#include "op_api_ut_common/op_api_ut.h"
#include "op_api_ut_common/scalar_desc.h"
#include "op_api_ut_common/tensor_desc.h"
#include "opdev/platform.h"
#include "ut_stub.h"

#define CHECK_RET(cond, return_expr) \
    do {                             \
        if (!(cond)) {               \
            return_expr;             \
        }                            \
    } while (0)

#define LOG_PRINT(message, ...)         \
    do {                                \
        printf(message, ##__VA_ARGS__); \
    } while (0)

#define CEIL_DIV(x, y) (((x) + (y) - 1) / (y))

struct WeightQuantPreprocessTestParam {
    string caseName;
    vector<int64_t> weightViewShape;
    vector<int64_t> weightStorageShape;
    vector<int64_t> weightStrides;
    vector<int64_t> scaleViewShape;
    vector<int64_t> scaleStorageShape;
    vector<int64_t> scaleStrides;
    aclDataType weightDtype;
    aclDataType scaleDtype;
    aclFormat weightFormat;
    aclFormat scaleFormat;
    aclDataType xDtype;
    aclDataType xScaleDtype;
    int64_t kGroupSize;
    bool isGMM;
    aclnnStatus expectRet;
    bool weightIsNull;
    bool weightScaleIsNull;
    bool outWeightIsNull;
    bool outWeightScaleIsNull;
    bool hasWeightOffset;
    bool hasBias;
    vector<int64_t> biasViewShape;
    vector<int64_t> biasStorageShape;
    aclDataType biasDtype;
    aclFormat biasFormat;
    aclFormat outWeightFormat;
    aclDataType outWeightDtype;
    aclDataType outWeightScaleDtype;
    vector<int64_t> outWeightStorageShape; // 非空时覆盖自动推导的 outWeight storageShape（用于构造负例）
};

class l2_weight_quant_preprocess_test : public testing::TestWithParam<WeightQuantPreprocessTestParam> {
protected:
    static void SetUpTestCase() { cout << "l2_weight_quant_preprocess_test SetUp" << endl; }
    static void TearDownTestCase() { cout << "l2_weight_quant_preprocess_test TearDown" << endl; }
};

class l2_weight_quant_preprocess_gmm_test : public testing::TestWithParam<WeightQuantPreprocessTestParam> {
protected:
    static void SetUpTestCase() { cout << "l2_weight_quant_preprocess_gmm_test SetUp" << endl; }
    static void TearDownTestCase() { cout << "l2_weight_quant_preprocess_gmm_test TearDown" << endl; }
};

class l2_weight_quant_preprocess_mm_test : public testing::TestWithParam<WeightQuantPreprocessTestParam> {
protected:
    static void SetUpTestCase() { cout << "l2_weight_quant_preprocess_mm_test SetUp" << endl; }
    static void TearDownTestCase() { cout << "l2_weight_quant_preprocess_mm_test TearDown" << endl; }
};

static void TestOneParamCase(const WeightQuantPreprocessTestParam& param)
{
    std::cout << "run case start: " << param.caseName << std::endl;
    void* weightDeviceAddr = nullptr;
    void* scaleDeviceAddr = nullptr;
    void* outWeightDeviceAddr = nullptr;
    void* outScaleDeviceAddr = nullptr;
    void* biasDeviceAddr = nullptr;

    int64_t weightStorageSize = 1;
    for (auto d : param.weightStorageShape)
        weightStorageSize *= d;
    int64_t weightBytes = weightStorageSize / 2;

    int64_t scaleStorageSize = 1;
    for (auto d : param.scaleStorageShape)
        scaleStorageSize *= d;
    int64_t scaleBytes = scaleStorageSize;

    aclTensor* weight = nullptr;
    if (!param.weightIsNull) {
        weight = aclCreateTensor(param.weightViewShape.data(), param.weightViewShape.size(), param.weightDtype,
                                 param.weightStrides.data(), 0, param.weightFormat, param.weightStorageShape.data(),
                                 param.weightStorageShape.size(), weightDeviceAddr);
    }

    aclTensor* weightScale = nullptr;
    if (!param.weightScaleIsNull) {
        weightScale = aclCreateTensor(param.scaleViewShape.data(), param.scaleViewShape.size(), param.scaleDtype,
                                      param.scaleStrides.data(), 0, param.scaleFormat, param.scaleStorageShape.data(),
                                      param.scaleStorageShape.size(), scaleDeviceAddr);
    }

    int64_t C0 = 32;
    auto outWeightViewShape = param.weightViewShape;
    vector<int64_t> outWeightStorageShape;
    if (!param.weightIsNull && !param.weightViewShape.empty()) {
        aclFormat effOutFormat = param.outWeightFormat != ACL_FORMAT_UNDEFINED ? param.outWeightFormat :
                                                                                 ACL_FORMAT_FRACTAL_NZ_C0_32;
        if (!param.outWeightStorageShape.empty()) {
            // 显式指定 outWeight storageShape（用于构造 NZ 分形形状错误的负例）
            outWeightStorageShape = param.outWeightStorageShape;
        } else if (effOutFormat == ACL_FORMAT_ND) {
            // ND 直拷：outWeight storageShape 与 viewShape 一致
            outWeightStorageShape = param.weightViewShape;
        } else if (effOutFormat == ACL_FORMAT_FRACTAL_NZ_C0_16) {
            // NZ_C0_16（A16W4 紧凑 4-bit）：N 块在前 {ceildiv(N, 16), ceildiv(K, 16), 16, 16}
            size_t dimNum = param.weightViewShape.size();
            int64_t K = param.weightViewShape[dimNum - 2];
            int64_t N = param.weightViewShape[dimNum - 1];
            outWeightStorageShape = {CEIL_DIV(N, 16), CEIL_DIV(K, 16), 16, 16};
        } else if (param.isGMM) {
            int64_t G = param.weightViewShape[0];
            int64_t K = param.weightViewShape[1];
            int64_t N = param.weightViewShape[2];
            outWeightStorageShape = {G, CEIL_DIV(K, C0), CEIL_DIV(N, 16), 16, C0};
        } else {
            int64_t K = param.weightViewShape[0];
            int64_t N = param.weightViewShape[1];
            outWeightStorageShape = {CEIL_DIV(K, C0), CEIL_DIV(N, 16), 16, C0};
        }
    }
    int64_t outWeightStorageSize = 1;
    for (auto d : outWeightStorageShape)
        outWeightStorageSize *= d;
    int64_t outWeightBytes = outWeightStorageSize / 2;

    aclTensor* outWeight = nullptr;
    if (!param.outWeightIsNull && !outWeightViewShape.empty()) {
        aclFormat outFormat = param.outWeightFormat != ACL_FORMAT_UNDEFINED ? param.outWeightFormat :
                                                                              ACL_FORMAT_FRACTAL_NZ_C0_32;
        aclDataType outDtype = param.outWeightDtype != ACL_DT_UNDEFINED ? param.outWeightDtype : param.weightDtype;
        outWeight = aclCreateTensor(outWeightViewShape.data(), outWeightViewShape.size(), outDtype, nullptr, 0,
                                    outFormat, outWeightStorageShape.data(), outWeightStorageShape.size(),
                                    outWeightDeviceAddr);
    }

    auto outScaleViewShape = param.scaleViewShape;
    auto outScaleStorageShape = param.scaleStorageShape;
    int64_t outScaleStorageSize = scaleStorageSize;

    aclTensor* outWeightScale = nullptr;
    if (!param.outWeightScaleIsNull && !outScaleViewShape.empty()) {
        aclDataType outScaleDtype = param.outWeightScaleDtype != ACL_DT_UNDEFINED ? param.outWeightScaleDtype :
                                                                                    param.scaleDtype;
        outWeightScale = aclCreateTensor(outScaleViewShape.data(), outScaleViewShape.size(), outScaleDtype,
                                         param.scaleStrides.data(), 0, param.scaleFormat, outScaleStorageShape.data(),
                                         outScaleStorageShape.size(), outScaleDeviceAddr);
    }

    aclTensor* biasOptional = nullptr;
    aclTensor* outBiasOptional = nullptr;
    if (param.hasBias && !param.biasViewShape.empty()) {
        biasOptional = aclCreateTensor(param.biasViewShape.data(), param.biasViewShape.size(), param.biasDtype, nullptr,
                                       0, param.biasFormat, param.biasStorageShape.data(),
                                       param.biasStorageShape.size(), biasDeviceAddr);
        outBiasOptional = aclCreateTensor(param.biasViewShape.data(), param.biasViewShape.size(), param.biasDtype,
                                          nullptr, 0, param.biasFormat, param.biasStorageShape.data(),
                                          param.biasStorageShape.size(), biasDeviceAddr);
    }

    aclTensor* weightOffsetOptional = nullptr;
    aclTensor* outWeightOffsetOptional = nullptr;
    if (param.hasWeightOffset) {
        weightOffsetOptional = aclCreateTensor(
            param.scaleViewShape.data(), param.scaleViewShape.size(), param.scaleDtype, nullptr, 0, param.scaleFormat,
            param.scaleStorageShape.data(), param.scaleStorageShape.size(), scaleDeviceAddr);
        outWeightOffsetOptional = aclCreateTensor(
            param.scaleViewShape.data(), param.scaleViewShape.size(), param.scaleDtype, nullptr, 0, param.scaleFormat,
            param.scaleStorageShape.data(), param.scaleStorageShape.size(), scaleDeviceAddr);
    }

    uint64_t workspaceSize = 0U;
    aclOpExecutor* exe = nullptr;
    void* workspaceAddr = nullptr;
    aclrtStream stream = nullptr;

    auto ret = aclnnWeightQuantPreprocessGetWorkspaceSize(
        weight, weightScale, weightOffsetOptional, biasOptional, param.xDtype, param.xScaleDtype, param.kGroupSize,
        outWeight, outWeightScale, outWeightOffsetOptional, outBiasOptional, &workspaceSize, &exe);
    std::cout << "aclnnWeightQuantPreprocessGetWorkspaceSize returned: " << ret << std::endl;

    if (ret != ACL_SUCCESS) {
        LOG_PRINT("aclnnWeightQuantPreprocessGetWorkspaceSize failed. ERROR: %d\n", ret);
        EXPECT_EQ(ret, param.expectRet);
        if (weight)
            aclDestroyTensor(weight);
        if (weightScale)
            aclDestroyTensor(weightScale);
        if (outWeight)
            aclDestroyTensor(outWeight);
        if (outWeightScale)
            aclDestroyTensor(outWeightScale);
        if (biasOptional)
            aclDestroyTensor(biasOptional);
        if (outBiasOptional)
            aclDestroyTensor(outBiasOptional);
        if (weightOffsetOptional)
            aclDestroyTensor(weightOffsetOptional);
        if (outWeightOffsetOptional)
            aclDestroyTensor(outWeightOffsetOptional);
        return;
    }

    ret = aclnnWeightQuantPreprocess(workspaceAddr, workspaceSize, exe, stream);
    std::cout << "aclnnWeightQuantPreprocess returned: " << ret << std::endl;

    if (ret != ACL_SUCCESS) {
        LOG_PRINT("aclnnWeightQuantPreprocess failed. ERROR: %d\n", ret);
        EXPECT_EQ(ret, param.expectRet);
    }

    std::cout << "run case end: " << param.caseName << std::endl;
    if (param.expectRet == ACLNN_SUCCESS) {
        EXPECT_NE(exe, nullptr);
    } else {
        ADD_FAILURE() << "case expected GetWorkspaceSize to fail with " << param.expectRet << " but got ACL_SUCCESS";
    }

    if (weight)
        aclDestroyTensor(weight);
    if (weightScale)
        aclDestroyTensor(weightScale);
    if (outWeight)
        aclDestroyTensor(outWeight);
    if (outWeightScale)
        aclDestroyTensor(outWeightScale);
    if (biasOptional)
        aclDestroyTensor(biasOptional);
    if (outBiasOptional)
        aclDestroyTensor(outBiasOptional);
    if (weightOffsetOptional)
        aclDestroyTensor(weightOffsetOptional);
    if (outWeightOffsetOptional)
        aclDestroyTensor(outWeightOffsetOptional);
}

static void TestOneParamCaseInSubprocess(const WeightQuantPreprocessTestParam& param)
{
    ASSERT_EXIT(
        {
            op::SetPlatformNpuArch(NpuArch::DAV_3510);
            TestOneParamCase(param);
            std::_Exit(::testing::Test::HasFailure() ? 1 : 0);
        },
        ::testing::ExitedWithCode(0), "");
}

TEST_P(l2_weight_quant_preprocess_gmm_test, gmmNormalTest)
{
    WeightQuantPreprocessTestParam param = GetParam();
    TestOneParamCaseInSubprocess(param);
}

TEST_P(l2_weight_quant_preprocess_mm_test, mmNormalTest)
{
    WeightQuantPreprocessTestParam param = GetParam();
    TestOneParamCaseInSubprocess(param);
}

TEST_P(l2_weight_quant_preprocess_test, generalTest)
{
    op::SetPlatformNpuArch(NpuArch::DAV_3510);
    WeightQuantPreprocessTestParam param = GetParam();
    TestOneParamCase(param);
}

static WeightQuantPreprocessTestParam gmmNormalCases[] = {
    {"ascend950_test_GMM_MX_A8W4_normal",
     {2, 64, 128},
     {2, 128, 64},
     {8192, 1, 64},
     {2, 1, 128, 2},
     {2, 128, 1, 2},
     {256, 2, 2, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT8_E4M3FN,
     ACL_FLOAT8_E8M0,
     32,
     true,
     ACLNN_SUCCESS,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_UNDEFINED,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},
};

static WeightQuantPreprocessTestParam mmNormalCases[] = {
    {"ascend950_test_MM_MX_A8W4_normal",
     {64, 128},
     {128, 64},
     {1, 64},
     {1, 128, 2},
     {128, 1, 2},
     {2, 2, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT8_E4M3FN,
     ACL_FLOAT8_E8M0,
     32,
     false,
     ACLNN_SUCCESS,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_UNDEFINED,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    {"ascend950_test_MM_MX_A8W4_bias_1d",
     {64, 128},
     {128, 64},
     {1, 64},
     {1, 128, 2},
     {128, 1, 2},
     {2, 2, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT8_E4M3FN,
     ACL_FLOAT8_E8M0,
     32,
     false,
     ACLNN_SUCCESS,
     false,
     false,
     false,
     false,
     false,
     true,
     {128},
     {128},
     ACL_FLOAT16,
     ACL_FORMAT_ND,
     ACL_FORMAT_UNDEFINED,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    {"ascend950_test_MM_MX_A8W4_bias_2d",
     {64, 128},
     {128, 64},
     {1, 64},
     {1, 128, 2},
     {128, 1, 2},
     {2, 2, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT8_E4M3FN,
     ACL_FLOAT8_E8M0,
     32,
     false,
     ACLNN_SUCCESS,
     false,
     false,
     false,
     false,
     false,
     true,
     {1, 128},
     {1, 128},
     ACL_FLOAT16,
     ACL_FORMAT_ND,
     ACL_FORMAT_UNDEFINED,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    // [STC a16s4 F-01/R-01] A16S4 per-channel 非转置 + NZ_C0_16 转换正例：weight [K,N] INT4，scale {N} FP16
    {"ascend950_test_MM_A16S4_perchannel_nz",
     {256, 256},
     {256, 256},
     {256, 1},
     {256},
     {256},
     {1},
     ACL_INT4,
     ACL_FLOAT16,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT16,
     ACL_DT_UNDEFINED,
     0,
     false,
     ACLNN_SUCCESS,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_FRACTAL_NZ_C0_16,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    // [STC a16s4 F-07/R-03] A16S4 per-group gs=64 非转置 + NZ_C0_16 转换正例：scale {4, 256} FP16
    {"ascend950_test_MM_A16S4_pergroup_nz",
     {256, 256},
     {256, 256},
     {256, 1},
     {4, 256},
     {4, 256},
     {256, 1},
     ACL_INT4,
     ACL_FLOAT16,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT16,
     ACL_DT_UNDEFINED,
     64,
     false,
     ACLNN_SUCCESS,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_FRACTAL_NZ_C0_16,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    // A16S4 per-channel NZ + weightOffset 直拷透传正例：offset 与 scale 同形同 dtype
    {"ascend950_test_MM_A16S4_perchannel_nz_offset",
     {256, 256},
     {256, 256},
     {256, 1},
     {256},
     {256},
     {1},
     ACL_INT4,
     ACL_FLOAT16,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT16,
     ACL_DT_UNDEFINED,
     0,
     false,
     ACLNN_SUCCESS,
     false,
     false,
     false,
     false,
     true,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_FRACTAL_NZ_C0_16,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    // A16S4 per-group NZ + weightOffset 直拷透传正例：offset 与 scale 同为 {4, 256}
    {"ascend950_test_MM_A16S4_pergroup_nz_offset",
     {256, 256},
     {256, 256},
     {256, 1},
     {4, 256},
     {4, 256},
     {256, 1},
     ACL_INT4,
     ACL_FLOAT16,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT16,
     ACL_DT_UNDEFINED,
     64,
     false,
     ACLNN_SUCCESS,
     false,
     false,
     false,
     false,
     true,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_FRACTAL_NZ_C0_16,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    // A16S4 per-tensor ND 直拷 + weightOffset 透传正例：offset 与 scale 同为 {1}
    {"ascend950_test_MM_A16S4_pertensor_nd_offset",
     {256, 256},
     {256, 256},
     {256, 1},
     {1},
     {1},
     {1},
     ACL_INT4,
     ACL_FLOAT16,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT16,
     ACL_DT_UNDEFINED,
     0,
     false,
     ACLNN_SUCCESS,
     false,
     false,
     false,
     false,
     true,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    // [STC a16s4 R-10] A16S4 per-tensor（scale 单元素）仅 ND 直拷正例
    {"ascend950_test_MM_A16S4_pertensor_nd",
     {256, 256},
     {256, 256},
     {256, 1},
     {1},
     {1},
     {1},
     ACL_INT4,
     ACL_FLOAT16,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT16,
     ACL_DT_UNDEFINED,
     0,
     false,
     ACLNN_SUCCESS,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    // [STC a16s4 R-08] A16S4 per-channel 转置 weight + ND 直拷正例：strides [1, K]
    {"ascend950_test_MM_A16S4_perchannel_trans_nd",
     {256, 256},
     {256, 256},
     {1, 256},
     {256},
     {256},
     {1},
     ACL_INT4,
     ACL_FLOAT16,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT16,
     ACL_DT_UNDEFINED,
     0,
     false,
     ACLNN_SUCCESS,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    // A16S4 per-channel 转置 ND 直拷 + weightOffset 透传正例
    {"ascend950_test_MM_A16S4_perchannel_trans_nd_offset",
     {256, 256},
     {256, 256},
     {1, 256},
     {256},
     {256},
     {1},
     ACL_INT4,
     ACL_FLOAT16,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT16,
     ACL_DT_UNDEFINED,
     0,
     false,
     ACLNN_SUCCESS,
     false,
     false,
     false,
     false,
     true,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    // A16S4 per-channel 非转置 + ND 出：不支持（非转置仅支持 NZ_C0_16 出，与 A16F4 对齐），judge 全不匹配
    {"ascend950_test_MM_A16S4_perchannel_nontrans_nd_reject",
     {256, 256},
     {256, 256},
     {256, 1},
     {256},
     {256},
     {1},
     ACL_INT4,
     ACL_FLOAT16,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT16,
     ACL_DT_UNDEFINED,
     0,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    // [STC a16s4 R-09] A16S4 per-group 转置 weight + ND 直拷正例：strides [1, K]
    {"ascend950_test_MM_A16S4_pergroup_trans_nd",
     {256, 256},
     {256, 256},
     {1, 256},
     {4, 256},
     {4, 256},
     {256, 1},
     ACL_INT4,
     ACL_FLOAT16,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT16,
     ACL_DT_UNDEFINED,
     64,
     false,
     ACLNN_SUCCESS,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    // [STC a16s4 T-14] per-group scale G=5 与 ceildiv(K=256, gs=64)=4 不对应：CheckWeightScalePerGroupViewShape 拒绝
    {"ascend950_test_MM_A16S4_pergroup_scale_g_mismatch",
     {256, 256},
     {256, 256},
     {256, 1},
     {5, 256},
     {5, 256},
     {256, 1},
     ACL_INT4,
     ACL_FLOAT16,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT16,
     ACL_DT_UNDEFINED,
     64,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_FRACTAL_NZ_C0_16,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    // [STC a16f4 F-01/R-01] A16F4 per-group gs=64 + NZ_C0_16 正例：weight FP4，scale {4, 256} FP16
    {"ascend950_test_MM_A16F4_pergroup_nz",
     {256, 256},
     {256, 256},
     {256, 1},
     {4, 256},
     {4, 256},
     {256, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT16,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT16,
     ACL_DT_UNDEFINED,
     64,
     false,
     ACLNN_SUCCESS,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_FRACTAL_NZ_C0_16,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    // [STC a16f4 F-07/R-03] A16MXF4 正例：weight FP4，scale E8M0 2D {ceildiv(256,32), 256}，kGroupSize=32
    {"ascend950_test_MM_A16MXF4_nz",
     {256, 256},
     {256, 256},
     {256, 1},
     {8, 256},
     {8, 256},
     {256, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT16,
     ACL_DT_UNDEFINED,
     32,
     false,
     ACLNN_SUCCESS,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_FRACTAL_NZ_C0_16,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},
};

static WeightQuantPreprocessTestParam casesParams[] = {

    {"ascend950_test_GMM_kGroupSize_not_32",
     {2, 64, 128},
     {2, 128, 64},
     {8192, 1, 64},
     {2, 1, 128, 2},
     {2, 128, 1, 2},
     {256, 2, 2, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT8_E4M3FN,
     ACL_FLOAT8_E8M0,
     64,
     true,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_UNDEFINED,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    {"ascend950_test_weight_nullptr",
     {64, 128},
     {128, 64},
     {1, 64},
     {1, 128, 2},
     {128, 1, 2},
     {2, 2, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT8_E4M3FN,
     ACL_FLOAT8_E8M0,
     32,
     false,
     ACLNN_ERR_PARAM_NULLPTR,
     true,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_UNDEFINED,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    {"ascend950_test_weightScale_nullptr",
     {64, 128},
     {128, 64},
     {1, 64},
     {1, 128, 2},
     {128, 1, 2},
     {2, 2, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT8_E4M3FN,
     ACL_FLOAT8_E8M0,
     32,
     false,
     ACLNN_ERR_PARAM_NULLPTR,
     false,
     true,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_UNDEFINED,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    {"ascend950_test_outWeight_nullptr",
     {64, 128},
     {128, 64},
     {1, 64},
     {1, 128, 2},
     {128, 1, 2},
     {2, 2, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT8_E4M3FN,
     ACL_FLOAT8_E8M0,
     32,
     false,
     ACLNN_ERR_PARAM_NULLPTR,
     false,
     false,
     true,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_UNDEFINED,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    {"ascend950_test_outWeightScale_nullptr",
     {64, 128},
     {128, 64},
     {1, 64},
     {1, 128, 2},
     {128, 1, 2},
     {2, 2, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT8_E4M3FN,
     ACL_FLOAT8_E8M0,
     32,
     false,
     ACLNN_ERR_PARAM_NULLPTR,
     false,
     false,
     false,
     true,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_UNDEFINED,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    {"ascend950_test_weight_empty",
     {0, 128},
     {128, 0},
     {1, 0},
     {1, 128, 2},
     {128, 1, 2},
     {2, 2, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT8_E4M3FN,
     ACL_FLOAT8_E8M0,
     32,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_UNDEFINED,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    {"ascend950_test_weightScale_empty",
     {64, 128},
     {128, 64},
     {1, 64},
     {1, 0, 2},
     {0, 1, 2},
     {2, 2, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT8_E4M3FN,
     ACL_FLOAT8_E8M0,
     32,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_UNDEFINED,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    {"ascend950_test_weight_format_invalid",
     {64, 128},
     {128, 64},
     {1, 64},
     {1, 128, 2},
     {128, 1, 2},
     {2, 2, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_NCHW,
     ACL_FORMAT_ND,
     ACL_FLOAT8_E4M3FN,
     ACL_FLOAT8_E8M0,
     32,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_UNDEFINED,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    {"ascend950_test_weightScale_format_invalid",
     {64, 128},
     {128, 64},
     {1, 64},
     {1, 128, 2},
     {128, 1, 2},
     {2, 2, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_NHWC,
     ACL_FLOAT8_E4M3FN,
     ACL_FLOAT8_E8M0,
     32,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_UNDEFINED,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    {"ascend950_test_outWeight_format_invalid",
     {64, 128},
     {128, 64},
     {1, 64},
     {1, 128, 2},
     {128, 1, 2},
     {2, 2, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT8_E4M3FN,
     ACL_FLOAT8_E8M0,
     32,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    {"ascend950_test_weight_dtype_invalid",
     {64, 128},
     {128, 64},
     {1, 64},
     {1, 128, 2},
     {128, 1, 2},
     {2, 2, 1},
     ACL_INT8,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT8_E4M3FN,
     ACL_FLOAT8_E8M0,
     32,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_UNDEFINED,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    {"ascend950_test_weightScale_dtype_invalid",
     {64, 128},
     {128, 64},
     {1, 64},
     {1, 128, 2},
     {128, 1, 2},
     {2, 2, 1},
     ACL_FLOAT4_E2M1,
     ACL_INT8,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT8_E4M3FN,
     ACL_FLOAT8_E8M0,
     32,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_UNDEFINED,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    {"ascend950_test_xDtype_invalid",
     {64, 128},
     {128, 64},
     {1, 64},
     {1, 128, 2},
     {128, 1, 2},
     {2, 2, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT16,
     ACL_FLOAT8_E8M0,
     32,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_UNDEFINED,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    {"ascend950_test_outWeight_dtype_mismatch",
     {64, 128},
     {128, 64},
     {1, 64},
     {1, 128, 2},
     {128, 1, 2},
     {2, 2, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT8_E4M3FN,
     ACL_FLOAT8_E8M0,
     32,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_UNDEFINED,
     ACL_INT8,
     ACL_DT_UNDEFINED},

    {"ascend950_test_outWeightScale_dtype_mismatch",
     {64, 128},
     {128, 64},
     {1, 64},
     {1, 128, 2},
     {128, 1, 2},
     {2, 2, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT8_E4M3FN,
     ACL_FLOAT8_E8M0,
     32,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_UNDEFINED,
     ACL_DT_UNDEFINED,
     ACL_INT8},

    {"ascend950_test_weight_dim_1d",
     {64},
     {64},
     {1},
     {1, 2},
     {2, 1},
     {1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT8_E4M3FN,
     ACL_FLOAT8_E8M0,
     32,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_UNDEFINED,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    {"ascend950_test_weight_dim_4d",
     {2, 2, 64, 128},
     {2, 2, 128, 64},
     {16384, 8192, 128, 1},
     {2, 2, 1, 128, 2},
     {2, 2, 128, 1, 2},
     {256, 256, 2, 2, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT8_E4M3FN,
     ACL_FLOAT8_E8M0,
     32,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_UNDEFINED,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    {"ascend950_test_weight_not_transposed",
     {64, 128},
     {64, 128},
     {128, 1},
     {1, 128, 2},
     {128, 1, 2},
     {2, 2, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT8_E4M3FN,
     ACL_FLOAT8_E8M0,
     32,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_UNDEFINED,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    {"ascend950_test_kGroupSize_not_32",
     {64, 128},
     {128, 64},
     {1, 64},
     {1, 128, 2},
     {128, 1, 2},
     {2, 2, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT8_E4M3FN,
     ACL_FLOAT8_E8M0,
     64,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_UNDEFINED,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    {"ascend950_test_kGroupSize_zero",
     {64, 128},
     {128, 64},
     {1, 64},
     {1, 128, 2},
     {128, 1, 2},
     {2, 2, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT8_E4M3FN,
     ACL_FLOAT8_E8M0,
     0,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_UNDEFINED,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    {"ascend950_test_weightScale_shape_invalid",
     {64, 128},
     {128, 64},
     {1, 64},
     {2, 128, 2},
     {128, 2, 2},
     {2, 2, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT8_E4M3FN,
     ACL_FLOAT8_E8M0,
     32,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_UNDEFINED,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    {"ascend950_test_weightScale_not_transposed",
     {64, 128},
     {128, 64},
     {1, 64},
     {1, 128, 2},
     {1, 128, 2},
     {256, 2, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT8_E4M3FN,
     ACL_FLOAT8_E8M0,
     32,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_UNDEFINED,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    {"ascend950_test_weightOffset_not_nullptr",
     {64, 128},
     {128, 64},
     {1, 64},
     {1, 128, 2},
     {128, 1, 2},
     {2, 2, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT8_E4M3FN,
     ACL_FLOAT8_E8M0,
     32,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     true,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_UNDEFINED,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    {"ascend950_test_bias_dtype_invalid",
     {64, 128},
     {128, 64},
     {1, 64},
     {1, 128, 2},
     {128, 1, 2},
     {2, 2, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT8_E4M3FN,
     ACL_FLOAT8_E8M0,
     32,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     true,
     {1, 128},
     {1, 128},
     ACL_INT8,
     ACL_FORMAT_ND,
     ACL_FORMAT_UNDEFINED,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    {"ascend950_test_bias_shape_invalid",
     {64, 128},
     {128, 64},
     {1, 64},
     {1, 128, 2},
     {128, 1, 2},
     {2, 2, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT8_E4M3FN,
     ACL_FLOAT8_E8M0,
     32,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     true,
     {2, 128},
     {2, 128},
     ACL_FLOAT16,
     ACL_FORMAT_ND,
     ACL_FORMAT_UNDEFINED,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    {"ascend950_test_bias_1d_shape_invalid",
     {64, 128},
     {128, 64},
     {1, 64},
     {1, 128, 2},
     {128, 1, 2},
     {2, 2, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT8_E4M3FN,
     ACL_FLOAT8_E8M0,
     32,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     true,
     {127},
     {127},
     ACL_FLOAT16,
     ACL_FORMAT_ND,
     ACL_FORMAT_UNDEFINED,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    {"ascend950_test_bias_format_invalid",
     {64, 128},
     {128, 64},
     {1, 64},
     {1, 128, 2},
     {128, 1, 2},
     {2, 2, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT8_E4M3FN,
     ACL_FLOAT8_E8M0,
     32,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     true,
     {1, 128},
     {1, 128},
     ACL_FLOAT16,
     ACL_FORMAT_NCHW,
     ACL_FORMAT_UNDEFINED,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    {"ascend950_test_GMM_bias_shape_invalid",
     {2, 64, 128},
     {2, 128, 64},
     {8192, 1, 64},
     {2, 1, 128, 2},
     {2, 128, 1, 2},
     {256, 2, 2, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT8_E4M3FN,
     ACL_FLOAT8_E8M0,
     32,
     true,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     true,
     {1, 128},
     {1, 128},
     ACL_FLOAT16,
     ACL_FORMAT_ND,
     ACL_FORMAT_UNDEFINED,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    {"ascend950_test_GMM_bias_1d_shape_invalid",
     {2, 64, 128},
     {2, 128, 64},
     {8192, 1, 64},
     {2, 1, 128, 2},
     {2, 128, 1, 2},
     {256, 2, 2, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT8_E4M3FN,
     ACL_FLOAT8_E8M0,
     32,
     true,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     true,
     {128},
     {128},
     ACL_FLOAT16,
     ACL_FORMAT_ND,
     ACL_FORMAT_UNDEFINED,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    // A16S4（INT4 紧凑 4-bit）per-channel 负例：weight [K,N] ND，scale [N] FP16，kGroupSize=0
    {"ascend950_test_A16S4_INT4_outWeight_nullptr",
     {64, 128},
     {64, 128},
     {128, 1},
     {128},
     {128},
     {1},
     ACL_INT4,
     ACL_FLOAT16,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT16,
     ACL_DT_UNDEFINED,
     0,
     false,
     ACLNN_ERR_PARAM_NULLPTR,
     false,
     false,
     true,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_UNDEFINED,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    // weight 末两维 strides 既非连续也非严格转置（{N, 2}），INT4 视图非法
    // （NZ_C0_16 出命中非转置 NZ 条目，由 CheckWeightInt4DirectCopyView 拒绝）
    {"ascend950_test_A16S4_INT4_weight_strides_invalid",
     {64, 128},
     {128, 128},
     {128, 2},
     {128},
     {128},
     {1},
     ACL_INT4,
     ACL_FLOAT16,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT16,
     ACL_DT_UNDEFINED,
     0,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_FRACTAL_NZ_C0_16,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    // [STC a16s4 T-12] per-channel scale {N} 与 weight N=128 不匹配（CheckWeightScalePerChannelViewShape）
    {"ascend950_test_A16S4_perchannel_scale_n_mismatch",
     {64, 128},
     {64, 128},
     {128, 1},
     {127},
     {127},
     {1},
     ACL_INT4,
     ACL_FLOAT16,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT16,
     ACL_DT_UNDEFINED,
     0,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_FRACTAL_NZ_C0_16,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    // [STC a16s4 T-13] per-channel scale {1, N} 与 weight N=128 不匹配（CheckWeightScalePerChannelViewShape）
    {"ascend950_test_A16S4_perchannel_scale_1n_mismatch",
     {64, 128},
     {64, 128},
     {128, 1},
     {1, 127},
     {1, 127},
     {127, 1},
     ACL_INT4,
     ACL_FLOAT16,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT16,
     ACL_DT_UNDEFINED,
     0,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_FRACTAL_NZ_C0_16,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    // per-channel 形状 scale {N} 配 kGroupSize>0 属矛盾输入（CheckKGroupSizeZero）
    {"ascend950_test_A16S4_perchannel_kgroupsize_nonzero",
     {64, 128},
     {64, 128},
     {128, 1},
     {128},
     {128},
     {1},
     ACL_INT4,
     ACL_FLOAT16,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT16,
     ACL_DT_UNDEFINED,
     64,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_FRACTAL_NZ_C0_16,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    // scale {2} 非单元素不命中 per-tensor，路由到 per-channel 后 N 不匹配
    {"ascend950_test_A16S4_pertensor_scale_two_elem",
     {64, 128},
     {64, 128},
     {128, 1},
     {2},
     {2},
     {1},
     ACL_INT4,
     ACL_FLOAT16,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT16,
     ACL_DT_UNDEFINED,
     0,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_FRACTAL_NZ_C0_16,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    // [STC a16s4 T-23] N=17 非 2 对齐，紧凑 4-bit 打包维须为偶数（CheckWeightPackingDimEven）
    {"ascend950_test_A16S4_n_not_2aligned",
     {256, 17},
     {256, 17},
     {17, 1},
     {17},
     {17},
     {1},
     ACL_INT4,
     ACL_FLOAT16,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT16,
     ACL_DT_UNDEFINED,
     0,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_FRACTAL_NZ_C0_16,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    // [STC a16s4 T-24] outWeight dtype 与 weight 不同（CheckOutWeightDtypeSame）
    {"ascend950_test_A16S4_outWeight_dtype_mismatch",
     {64, 128},
     {64, 128},
     {128, 1},
     {128},
     {128},
     {1},
     ACL_INT4,
     ACL_FLOAT16,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT16,
     ACL_DT_UNDEFINED,
     0,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_FRACTAL_NZ_C0_16,
     ACL_INT8,
     ACL_DT_UNDEFINED},

    // [STC a16s4 T-25] 非转置 per-channel + outWeight format=NZ_C0_32：judge 均不匹配
    {"ascend950_test_A16S4_outWeight_format_nzc032",
     {64, 128},
     {64, 128},
     {128, 1},
     {128},
     {128},
     {1},
     ACL_INT4,
     ACL_FLOAT16,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT16,
     ACL_DT_UNDEFINED,
     0,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_FRACTAL_NZ_C0_32,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    // [STC a16s4 T-26] outWeight NZ_C0_16 storageShape 错误：正确为 N 块在前 {8, 4, 16, 16}，
    // 此处按 K 块在前传 {4, 8, 16, 16}（CheckOutWeightTransNz）
    {"ascend950_test_A16S4_outWeight_nz_storage_shape_wrong",
     {64, 128},
     {64, 128},
     {128, 1},
     {128},
     {128},
     {1},
     ACL_INT4,
     ACL_FLOAT16,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT16,
     ACL_DT_UNDEFINED,
     0,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_FRACTAL_NZ_C0_16,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED,
     {4, 8, 16, 16}},

    // [STC a16s4 T-19] 转置 weight + NZ_C0_16 输出：命中 per-channel 转置 ND 直拷条目，
    // outWeight 非 ND 被 CheckOutWeightFormatND 拒绝
    {"ascend950_test_A16S4_transposed_weight_nz_out",
     {64, 128},
     {128, 64},
     {1, 64},
     {128},
     {128},
     {1},
     ACL_INT4,
     ACL_FLOAT16,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT16,
     ACL_DT_UNDEFINED,
     0,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_FRACTAL_NZ_C0_16,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    // [STC a16f4 R-05] FP4 weight + per-channel 1D scale：A16F4 不支持 per-channel，judge 全不匹配
    {"ascend950_test_A16F4_perchannel_scale_nomatch",
     {64, 128},
     {64, 128},
     {128, 1},
     {128},
     {128},
     {1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT16,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT16,
     ACL_DT_UNDEFINED,
     0,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_FRACTAL_NZ_C0_16,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    // [STC a16f4 T-31] A16MXF4 kGroupSize=64 ≠ 32（CheckKGroupSizeMx）
    {"ascend950_test_A16MXF4_kgroupsize_not_32",
     {64, 128},
     {64, 128},
     {128, 1},
     {2, 128},
     {2, 128},
     {128, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT16,
     ACL_DT_UNDEFINED,
     64,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_FRACTAL_NZ_C0_16,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    // [STC a16f4 T-18] MX scale 3D 旧布局 {ceildiv(K,32), N, 2}：A16MXF4 仅接受 2D，judge 全不匹配
    {"ascend950_test_A16MXF4_scale_3d_legacy",
     {64, 128},
     {64, 128},
     {128, 1},
     {2, 128, 2},
     {2, 128, 2},
     {256, 2, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT8_E8M0,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT16,
     ACL_DT_UNDEFINED,
     32,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_FRACTAL_NZ_C0_16,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

    // [STC a16f4 T-26] FP4 转置 weight：A16F4 per-group NZ 路径仅支持非转置（CheckWeightNotTrans）
    {"ascend950_test_A16F4_transposed_weight",
     {64, 128},
     {128, 64},
     {1, 64},
     {2, 128},
     {2, 128},
     {128, 1},
     ACL_FLOAT4_E2M1,
     ACL_FLOAT16,
     ACL_FORMAT_ND,
     ACL_FORMAT_ND,
     ACL_FLOAT16,
     ACL_DT_UNDEFINED,
     32,
     false,
     ACLNN_ERR_PARAM_INVALID,
     false,
     false,
     false,
     false,
     false,
     false,
     {},
     {},
     ACL_DT_UNDEFINED,
     ACL_FORMAT_ND,
     ACL_FORMAT_FRACTAL_NZ_C0_16,
     ACL_DT_UNDEFINED,
     ACL_DT_UNDEFINED},

};

INSTANTIATE_TEST_SUITE_P(WeightQuantPreprocessGMM, l2_weight_quant_preprocess_gmm_test,
                         testing::ValuesIn(gmmNormalCases));
INSTANTIATE_TEST_SUITE_P(WeightQuantPreprocessMM, l2_weight_quant_preprocess_mm_test, testing::ValuesIn(mmNormalCases));
INSTANTIATE_TEST_SUITE_P(WeightQuantPreprocess, l2_weight_quant_preprocess_test, testing::ValuesIn(casesParams));
