/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file square_sum_v1_tiling_key.h
 * \brief square_sum_v1 tiling key
 */

#ifndef _SQUARE_SUM_V1_TILING_KEY_H_
#define _SQUARE_SUM_V1_TILING_KEY_H_

#include "atvoss/reduce/reduce_tiling_key_decl.h"

ASCENDC_TPL_ARGS_DECL(SquareSumV1, REDUCE_TPL_KEY_DECL(), ASCENDC_TPL_UINT_DECL(Noop, 1, ASCENDC_TPL_UI_LIST, 0, 1));
ASCENDC_TPL_SEL(
    // Empty
    ASCENDC_TPL_ARGS_SEL(REDUCE_TPL_KEY_SEL_EMPTY(), ASCENDC_TPL_UINT_SEL(Noop, ASCENDC_TPL_UI_LIST, 0, 1)),
    // A
    ASCENDC_TPL_ARGS_SEL(REDUCE_TPL_KEY_SEL_A(), ASCENDC_TPL_UINT_SEL(Noop, ASCENDC_TPL_UI_LIST, 0, 1)),
    // AR
    ASCENDC_TPL_ARGS_SEL(REDUCE_TPL_KEY_SEL_AR_NORMAL(), ASCENDC_TPL_UINT_SEL(Noop, ASCENDC_TPL_UI_LIST, 0, 1)),
    ASCENDC_TPL_ARGS_SEL(REDUCE_TPL_KEY_SEL_AR_GROUP(), ASCENDC_TPL_UINT_SEL(Noop, ASCENDC_TPL_UI_LIST, 0, 1)),
    // ARA
    ASCENDC_TPL_ARGS_SEL(REDUCE_TPL_KEY_SEL_ARA_NORMAL(), ASCENDC_TPL_UINT_SEL(Noop, ASCENDC_TPL_UI_LIST, 0, 1)),
    ASCENDC_TPL_ARGS_SEL(REDUCE_TPL_KEY_SEL_ARA_GROUP(), ASCENDC_TPL_UINT_SEL(Noop, ASCENDC_TPL_UI_LIST, 0, 1)),
    // ARAR
    ASCENDC_TPL_ARGS_SEL(REDUCE_TPL_KEY_SEL_ARAR_NORMAL(), ASCENDC_TPL_UINT_SEL(Noop, ASCENDC_TPL_UI_LIST, 0, 1)),
    ASCENDC_TPL_ARGS_SEL(REDUCE_TPL_KEY_SEL_ARAR_GROUP(), ASCENDC_TPL_UINT_SEL(Noop, ASCENDC_TPL_UI_LIST, 0, 1)),
    // ARARARAR
    ASCENDC_TPL_ARGS_SEL(REDUCE_TPL_KEY_SEL_ARARARAR_NORMAL(), ASCENDC_TPL_UINT_SEL(Noop, ASCENDC_TPL_UI_LIST, 0, 1)),
    ASCENDC_TPL_ARGS_SEL(REDUCE_TPL_KEY_SEL_ARARARAR_GROUP(), ASCENDC_TPL_UINT_SEL(Noop, ASCENDC_TPL_UI_LIST, 0, 1)),
    // ARARARARA
    ASCENDC_TPL_ARGS_SEL(REDUCE_TPL_KEY_SEL_ARARARARA_NORMAL(), ASCENDC_TPL_UINT_SEL(Noop, ASCENDC_TPL_UI_LIST, 0, 1)),
    ASCENDC_TPL_ARGS_SEL(REDUCE_TPL_KEY_SEL_ARARARARA_GROUP(), ASCENDC_TPL_UINT_SEL(Noop, ASCENDC_TPL_UI_LIST, 0, 1)));
#endif
