/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 *
 * Generated By CANNBot
 */

/*!
 * \file test_inv_grad_tiling_arch35.cpp
 * \brief InvGrad Tiling UT (arch35 / Ascend950)
 *
 * Covers paths in op_host/arch35/inv_grad_tiling_arch35.cpp:
 *   1) Dtype path -- dtype changes element size and UB tiling parameters;
 *      kernel dtype binaries are generated from inv_grad_def.cpp, not TilingKey.
 *   2) Multi-core path (large shape) vs single-core path (small shape).
 *   3) Non-aligned tail (totalElements not multiple of 32B in elements).
 *   4) Empty tensor (totalElements == 0)
 *        - kernel early-return path: blockDim=1, all tiling fields = 0.
 *   5) Failure paths:
 *        - dtype mismatch between x and grad   -> GRAPH_FAILED
 *        - shape mismatch (dimNum differs)     -> GRAPH_FAILED
 *        - shape mismatch (same rank, dim differs) -> GRAPH_FAILED
 *        - unsupported dtype (DT_DOUBLE)       -> GRAPH_FAILED
 *
 * Default platform info from TilingContextPara: coreNum=64, ubSize=262144.
 *
 * Expected TilingData = "totalElements blockFactor ubFactor " (3 int64_t).
 *
 * UB / blockFactor derivation (matches inv_grad_tiling_arch35.cpp lines 200-207):
 *   bytesPerElem = 3 * typeSize + 2 * sizeof(float)
 *   FP32 typeSize=4 -> bytesPerElem=20 -> ubFactor=FloorAlign(262144/20, 8)
 *                                                 = FloorAlign(13107, 8) = 13104
 *   FP16 typeSize=2 -> bytesPerElem=14 -> ubFactor=FloorAlign(262144/14, 16)
 *                                                 = FloorAlign(18724, 16) = 18720
 *   BF16 typeSize=2 -> same formula as FP16        -> ubFactor=18720
 *
 *   blockFactor = ceil_align( ceil(totalElements/coreNum), ubBlockSize )
 *   usedCoreNum = ceil(totalElements / blockFactor)
 *
 * The included header re-exposes InvGradCompileInfo (an empty marker struct)
 * matching the TilingParse<InvGradCompileInfo> registration.
 */

#include "../../../../op_host/arch35/inv_grad_tiling_arch35.h"
#include "../../../../op_kernel/arch35/inv_grad_tiling_data.h"
#include <cstdint>
#include <iostream>
#include <gtest/gtest.h>
#include "tiling_context_faker.h"
#include "tiling_case_executor.h"

using namespace std;

class InvGradTilingTest : public testing::Test {
protected:
    static void SetUpTestCase() { std::cout << "InvGradTilingTest SetUp" << std::endl; }

    static void TearDownTestCase() { std::cout << "InvGradTilingTest TearDown" << std::endl; }
};

static void ExecuteInvGradTilingCase(const gert::TilingContextPara& tilingContextPara, ge::graphStatus expectResult,
                                     int64_t expectTotalElements, int64_t expectBlockFactor, int64_t expectUbFactor,
                                     const std::vector<size_t>& expectWorkspaces)
{
    TilingInfo tilingInfo;
    const bool tilingSuccess = ExecuteTiling(tilingContextPara, tilingInfo);
    ASSERT_EQ(tilingSuccess, expectResult == ge::GRAPH_SUCCESS);
    if (expectResult != ge::GRAPH_SUCCESS) {
        return;
    }

    ASSERT_EQ(tilingInfo.workspaceSizes.size(), expectWorkspaces.size());
    for (size_t i = 0; i < expectWorkspaces.size(); ++i) {
        EXPECT_EQ(tilingInfo.workspaceSizes[i], expectWorkspaces[i]);
    }

    ASSERT_GE(tilingInfo.tilingDataSize, sizeof(InvGradTilingData));
    const auto* tilingData = reinterpret_cast<const InvGradTilingData*>(tilingInfo.tilingData.get());
    EXPECT_EQ(tilingData->totalElements, expectTotalElements);
    EXPECT_EQ(tilingData->blockFactor, expectBlockFactor);
    EXPECT_EQ(tilingData->ubFactor, expectUbFactor);
}

// ===========================================================================
// 1) FP32 main path -- multi-core, aligned
//    shape {1, 64, 2, 64} = 8192 elem, coreNum=64, ubSize=262144
//      ubBlockSize = 32/4 = 8
//      perCoreRaw = ceil(8192/64) = 128; blockFactor = align_up(128, 8) = 128
//      usedCoreNum = ceil(8192/128) = 64
//      bytesPerElem = 3*4 + 2*4 = 20 -> ubFactor = FloorAlign(13107, 8) = 13104
// ===========================================================================
TEST_F(InvGradTilingTest, test_tiling_fp32_multi_core_001)
{
    optiling::InvGradCompileInfo compileInfo;
    gert::TilingContextPara tilingContextPara(
        "InvGrad",
        {
            {{{1, 64, 2, 64}, {1, 64, 2, 64}}, ge::DT_FLOAT, ge::FORMAT_ND}, // x
            {{{1, 64, 2, 64}, {1, 64, 2, 64}}, ge::DT_FLOAT, ge::FORMAT_ND}, // grad
        },
        {
            {{{1, 64, 2, 64}, {1, 64, 2, 64}}, ge::DT_FLOAT, ge::FORMAT_ND}, // y
        },
        &compileInfo);
    std::vector<size_t> expectWorkspaces = {0};
    ExecuteInvGradTilingCase(tilingContextPara, ge::GRAPH_SUCCESS, 8192, 128, 13104, expectWorkspaces);
}

// ===========================================================================
// 2) FP16 main path -- multi-core, aligned
//    shape {1, 64, 2, 64} = 8192 elem
//      ubBlockSize = 32/2 = 16
//      perCoreRaw = ceil(8192/64) = 128; blockFactor = align_up(128, 16) = 128
//      usedCoreNum = 64
//      bytesPerElem = 3*2 + 2*4 = 14 -> ubFactor = FloorAlign(18724, 16) = 18720
// ===========================================================================
TEST_F(InvGradTilingTest, test_tiling_fp16_multi_core_002)
{
    optiling::InvGradCompileInfo compileInfo;
    gert::TilingContextPara tilingContextPara("InvGrad",
                                              {
                                                  {{{1, 64, 2, 64}, {1, 64, 2, 64}}, ge::DT_FLOAT16, ge::FORMAT_ND},
                                                  {{{1, 64, 2, 64}, {1, 64, 2, 64}}, ge::DT_FLOAT16, ge::FORMAT_ND},
                                              },
                                              {
                                                  {{{1, 64, 2, 64}, {1, 64, 2, 64}}, ge::DT_FLOAT16, ge::FORMAT_ND},
                                              },
                                              &compileInfo);
    std::vector<size_t> expectWorkspaces = {0};
    ExecuteInvGradTilingCase(tilingContextPara, ge::GRAPH_SUCCESS, 8192, 128, 18720, expectWorkspaces);
}

// ===========================================================================
// 3) BF16 main path -- multi-core, aligned (shares fp16 layout)
// ===========================================================================
TEST_F(InvGradTilingTest, test_tiling_bf16_multi_core_003)
{
    optiling::InvGradCompileInfo compileInfo;
    gert::TilingContextPara tilingContextPara("InvGrad",
                                              {
                                                  {{{1, 64, 2, 64}, {1, 64, 2, 64}}, ge::DT_BF16, ge::FORMAT_ND},
                                                  {{{1, 64, 2, 64}, {1, 64, 2, 64}}, ge::DT_BF16, ge::FORMAT_ND},
                                              },
                                              {
                                                  {{{1, 64, 2, 64}, {1, 64, 2, 64}}, ge::DT_BF16, ge::FORMAT_ND},
                                              },
                                              &compileInfo);
    std::vector<size_t> expectWorkspaces = {0};
    ExecuteInvGradTilingCase(tilingContextPara, ge::GRAPH_SUCCESS, 8192, 128, 18720, expectWorkspaces);
}

// ===========================================================================
// 4) FP32 small + single-core + non-aligned tail
//    shape {7} = 7 elem
//      ubBlockSize = 8
//      perCoreRaw = ceil(7/64) = 1; blockFactor = align_up(1, 8) = 8
//      usedCoreNum = ceil(7/8) = 1
//    Expected tiling data: totalElements=7, blockFactor=8, ubFactor=13104
// ===========================================================================
TEST_F(InvGradTilingTest, test_tiling_fp32_small_tail_004)
{
    optiling::InvGradCompileInfo compileInfo;
    gert::TilingContextPara tilingContextPara("InvGrad",
                                              {
                                                  {{{7}, {7}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                  {{{7}, {7}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              {
                                                  {{{7}, {7}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              &compileInfo);
    std::vector<size_t> expectWorkspaces = {0};
    ExecuteInvGradTilingCase(tilingContextPara, ge::GRAPH_SUCCESS, 7, 8, 13104, expectWorkspaces);
}

// ===========================================================================
// 5) FP32 multi-core + non-aligned tail
//    shape {33} = 33 elem
//      ubBlockSize = 8
//      perCoreRaw = ceil(33/64) = 1; blockFactor = align_up(1, 8) = 8
//      usedCoreNum = ceil(33/8) = 5  (5 cores active; last core processes tail)
// ===========================================================================
TEST_F(InvGradTilingTest, test_tiling_fp32_unalign_multi_core_005)
{
    optiling::InvGradCompileInfo compileInfo;
    gert::TilingContextPara tilingContextPara("InvGrad",
                                              {
                                                  {{{33}, {33}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                  {{{33}, {33}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              {
                                                  {{{33}, {33}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              &compileInfo);
    std::vector<size_t> expectWorkspaces = {0};
    ExecuteInvGradTilingCase(tilingContextPara, ge::GRAPH_SUCCESS, 33, 8, 13104, expectWorkspaces);
}

// ===========================================================================
// 6) FP16 non-aligned tail single-core
//    shape {17} = 17 elem
//      ubBlockSize = 16
//      perCoreRaw = ceil(17/64) = 1; blockFactor = align_up(1, 16) = 16
//      usedCoreNum = ceil(17/16) = 2
// ===========================================================================
TEST_F(InvGradTilingTest, test_tiling_fp16_unalign_006)
{
    optiling::InvGradCompileInfo compileInfo;
    gert::TilingContextPara tilingContextPara("InvGrad",
                                              {
                                                  {{{17}, {17}}, ge::DT_FLOAT16, ge::FORMAT_ND},
                                                  {{{17}, {17}}, ge::DT_FLOAT16, ge::FORMAT_ND},
                                              },
                                              {
                                                  {{{17}, {17}}, ge::DT_FLOAT16, ge::FORMAT_ND},
                                              },
                                              &compileInfo);
    std::vector<size_t> expectWorkspaces = {0};
    ExecuteInvGradTilingCase(tilingContextPara, ge::GRAPH_SUCCESS, 17, 16, 18720, expectWorkspaces);
}

// ===========================================================================
// 7) Empty tensor FP32: totalElements=0 -> early return branch
//    Tiling data should be {0, 0, 0}; blockDim = 1.
// ===========================================================================
TEST_F(InvGradTilingTest, test_tiling_empty_fp32_007)
{
    optiling::InvGradCompileInfo compileInfo;
    gert::TilingContextPara tilingContextPara("InvGrad",
                                              {
                                                  {{{0}, {0}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                  {{{0}, {0}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              {
                                                  {{{0}, {0}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              &compileInfo);
    std::vector<size_t> expectWorkspaces = {0};
    ExecuteInvGradTilingCase(tilingContextPara, ge::GRAPH_SUCCESS, 0, 0, 0, expectWorkspaces);
}

// ===========================================================================
// 8) Empty tensor BF16: multi-dim with leading zero
// ===========================================================================
TEST_F(InvGradTilingTest, test_tiling_empty_bf16_008)
{
    optiling::InvGradCompileInfo compileInfo;
    gert::TilingContextPara tilingContextPara("InvGrad",
                                              {
                                                  {{{0, 8}, {0, 8}}, ge::DT_BF16, ge::FORMAT_ND},
                                                  {{{0, 8}, {0, 8}}, ge::DT_BF16, ge::FORMAT_ND},
                                              },
                                              {
                                                  {{{0, 8}, {0, 8}}, ge::DT_BF16, ge::FORMAT_ND},
                                              },
                                              &compileInfo);
    std::vector<size_t> expectWorkspaces = {0};
    ExecuteInvGradTilingCase(tilingContextPara, ge::GRAPH_SUCCESS, 0, 0, 0, expectWorkspaces);
}

// ===========================================================================
// 9) FAIL: dtype mismatch between x and grad (x=FP16, grad=FP32)
//    GetShapeInfo enforces dataType(x) == dataType(grad) -> GRAPH_FAILED
// ===========================================================================
TEST_F(InvGradTilingTest, test_tiling_fail_dtype_mismatch_009)
{
    optiling::InvGradCompileInfo compileInfo;
    gert::TilingContextPara tilingContextPara("InvGrad",
                                              {
                                                  {{{8}, {8}}, ge::DT_FLOAT16, ge::FORMAT_ND},
                                                  {{{8}, {8}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              {
                                                  {{{8}, {8}}, ge::DT_FLOAT16, ge::FORMAT_ND},
                                              },
                                              &compileInfo);
    ExecuteInvGradTilingCase(tilingContextPara, ge::GRAPH_FAILED, 0, 0, 0, {});
}

// ===========================================================================
// 10) FAIL: shape rank mismatch (x is 1D, grad is 2D)
// ===========================================================================
TEST_F(InvGradTilingTest, test_tiling_fail_rank_mismatch_010)
{
    optiling::InvGradCompileInfo compileInfo;
    gert::TilingContextPara tilingContextPara("InvGrad",
                                              {
                                                  {{{8}, {8}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                  {{{2, 4}, {2, 4}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              {
                                                  {{{8}, {8}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              &compileInfo);
    ExecuteInvGradTilingCase(tilingContextPara, ge::GRAPH_FAILED, 0, 0, 0, {});
}

// ===========================================================================
// 11) FAIL: same rank but dim mismatch (x=[8], grad=[16])
// ===========================================================================
TEST_F(InvGradTilingTest, test_tiling_fail_dim_mismatch_011)
{
    optiling::InvGradCompileInfo compileInfo;
    gert::TilingContextPara tilingContextPara("InvGrad",
                                              {
                                                  {{{8}, {8}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                  {{{16}, {16}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              {
                                                  {{{8}, {8}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              &compileInfo);
    ExecuteInvGradTilingCase(tilingContextPara, ge::GRAPH_FAILED, 0, 0, 0, {});
}

// ===========================================================================
// 12) FAIL: unsupported dtype DT_DOUBLE
// ===========================================================================
TEST_F(InvGradTilingTest, test_tiling_fail_unsupported_dtype_double_012)
{
    optiling::InvGradCompileInfo compileInfo;
    gert::TilingContextPara tilingContextPara("InvGrad",
                                              {
                                                  {{{16}, {16}}, ge::DT_DOUBLE, ge::FORMAT_ND},
                                                  {{{16}, {16}}, ge::DT_DOUBLE, ge::FORMAT_ND},
                                              },
                                              {
                                                  {{{16}, {16}}, ge::DT_DOUBLE, ge::FORMAT_ND},
                                              },
                                              &compileInfo);
    ExecuteInvGradTilingCase(tilingContextPara, ge::GRAPH_FAILED, 0, 0, 0, {});
}

// ===========================================================================
// 13) FAIL: unsupported dtype DT_INT8 (int32 支持，int8 因 arch35 cast 限制不支持)
// ===========================================================================
TEST_F(InvGradTilingTest, test_tiling_fail_unsupported_dtype_int8_013)
{
    optiling::InvGradCompileInfo compileInfo;
    gert::TilingContextPara tilingContextPara("InvGrad",
                                              {
                                                  {{{16}, {16}}, ge::DT_INT8, ge::FORMAT_ND},
                                                  {{{16}, {16}}, ge::DT_INT8, ge::FORMAT_ND},
                                              },
                                              {
                                                  {{{16}, {16}}, ge::DT_INT8, ge::FORMAT_ND},
                                              },
                                              &compileInfo);
    ExecuteInvGradTilingCase(tilingContextPara, ge::GRAPH_FAILED, 0, 0, 0, {});
}

// ===========================================================================
// 14) PASS: int32 native compute path, multi-core
//   typeSize=4, bytesPerElem = 3*4 + 2*4 = 20
//   ubFactor expected ~ same as fp32 (typeSize 相同)
// ===========================================================================
TEST_F(InvGradTilingTest, test_tiling_int32_multi_core_014)
{
    optiling::InvGradCompileInfo compileInfo;
    gert::TilingContextPara tilingContextPara("InvGrad",
                                              {
                                                  {{{1, 64, 2, 64}, {1, 64, 2, 64}}, ge::DT_INT32, ge::FORMAT_ND},
                                                  {{{1, 64, 2, 64}, {1, 64, 2, 64}}, ge::DT_INT32, ge::FORMAT_ND},
                                              },
                                              {
                                                  {{{1, 64, 2, 64}, {1, 64, 2, 64}}, ge::DT_INT32, ge::FORMAT_ND},
                                              },
                                              &compileInfo);
    std::vector<size_t> expectWorkspaces = {0};
    ExecuteInvGradTilingCase(tilingContextPara, ge::GRAPH_SUCCESS, 8192, 128, 13104, expectWorkspaces);
}

// ===========================================================================
// 15) PASS: int32 empty tensor — totalElements=0 走 memset 早返回路径
//   tilingData 全 0, blockDim=1
// ===========================================================================
TEST_F(InvGradTilingTest, test_tiling_empty_int32_015)
{
    optiling::InvGradCompileInfo compileInfo;
    gert::TilingContextPara tilingContextPara("InvGrad",
                                              {
                                                  {{{0, 8}, {0, 8}}, ge::DT_INT32, ge::FORMAT_ND},
                                                  {{{0, 8}, {0, 8}}, ge::DT_INT32, ge::FORMAT_ND},
                                              },
                                              {
                                                  {{{0, 8}, {0, 8}}, ge::DT_INT32, ge::FORMAT_ND},
                                              },
                                              &compileInfo);
    std::vector<size_t> expectWorkspaces = {0};
    ExecuteInvGradTilingCase(tilingContextPara, ge::GRAPH_SUCCESS, 0, 0, 0, expectWorkspaces);
}

// ===========================================================================
// 16) PASS: int32 unalign small shape [33] — 非对齐尾块, blockFactor 上对齐到 8
//   typeSize=4, ubBlockSize=32/4=8
//   blockFactor = CeilDiv(33, 64) = 1, 上对齐到 8 → 8
//   ubFactor = FloorAlign(262144/20=13107, 8) = 13104
// ===========================================================================
TEST_F(InvGradTilingTest, test_tiling_int32_unalign_016)
{
    optiling::InvGradCompileInfo compileInfo;
    gert::TilingContextPara tilingContextPara("InvGrad",
                                              {
                                                  {{{33}, {33}}, ge::DT_INT32, ge::FORMAT_ND},
                                                  {{{33}, {33}}, ge::DT_INT32, ge::FORMAT_ND},
                                              },
                                              {
                                                  {{{33}, {33}}, ge::DT_INT32, ge::FORMAT_ND},
                                              },
                                              &compileInfo);
    std::vector<size_t> expectWorkspaces = {0};
    ExecuteInvGradTilingCase(tilingContextPara, ge::GRAPH_SUCCESS, 33, 8, 13104, expectWorkspaces);
}
