/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#include <iostream>
#include <gtest/gtest.h>
#include "tiling_context_faker.h"
#include "tiling_case_executor.h"
#include "../../../../op_kernel/arch35/tabulate_fusion_tiling_data.h"

using namespace std;
using namespace ge;

class TabulateFusionTiling : public testing::Test {
protected:
    static void SetUpTestCase() { std::cout << "TabulateFusionTiling SetUp" << std::endl; }

    static void TearDownTestCase() { std::cout << "TabulateFusionTiling TearDown" << std::endl; }
};

std::map<std::string, std::string> soc_version_infos = {{"Short_SoC_version", "Ascend950"}};

// float32 用例: nloc=2, nnei=3, last_layer_size=4
// table: (10, 384), table_info: (5,), em_x: (6, 1), em: (2, 3, 4), descriptor: (2, 4, 4)
// TabulateFusionTilingData 字段顺序: needCoreNum, nloc, nnei, lastLayerSize, lastSizeAlign, tableRowSize, tableRows
// totalWork = 2*4 = 8; coreNum=64 -> perCore=1 < 1024 -> 1024; needCoreNum = ceil(8/1024) = 1
TEST_F(TabulateFusionTiling, tabulate_fusion_float32)
{
    struct TabulateFusionCompileInfo {
    } compileInfo;
    gert::TilingContextPara tilingContextPara(
        "TabulateFusion",
        {
            {{{10, 384}, {10, 384}}, ge::DT_FLOAT, ge::FORMAT_ND}, // input 0: table
            {{{5}, {5}}, ge::DT_FLOAT, ge::FORMAT_ND},             // input 1: table_info
            {{{6, 1}, {6, 1}}, ge::DT_FLOAT, ge::FORMAT_ND},       // input 2: em_x
            {{{2, 3, 4}, {2, 3, 4}}, ge::DT_FLOAT, ge::FORMAT_ND}, // input 3: em
        },
        {
            {{{2, 4, 4}, {2, 4, 4}}, ge::DT_FLOAT, ge::FORMAT_ND}, // output 0: descriptor
        },
        {
            gert::TilingContextPara::OpAttr("last_layer_size",
                                            Ops::Math::AnyValue::CreateFrom<int64_t>(static_cast<int64_t>(4))),
        },
        &compileInfo,
        64,                       // number of cores obtained in the tiling phase
        262144,                   // the ubsize obtained in the tiling phase
        4096);                    // specifies the maximum size of the tiling data in the tiling phase
    uint64_t expectTilingKey = 0; // TABULATE_FUSION_MODE_DEFAULT
    // TilingData 字段为 int32_t，UT 框架按 int64_t 读取（little-endian 两两合并）：
    // int64_t[0]=needCoreNum(1)|(nloc(2)<<32)=8589934593, int64_t[1]=nnei(3)|(lastLayerSize(4)<<32)=17179869187,
    // int64_t[2]=lastSizeAlign(64)|(tableRowSize(384)<<32)=1649267441728
    string expectTilingData = "8589934593 17179869187 1649267441728 ";
    // workspace = userWorkspace(0) + sysWorkspace(GetLibApiWorkSpaceSize on ascend950 = 16MB)
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}

// float16 用例: nloc=2, nnei=3, last_layer_size=4
TEST_F(TabulateFusionTiling, tabulate_fusion_float16)
{
    struct TabulateFusionCompileInfo {
    } compileInfo;
    gert::TilingContextPara tilingContextPara(
        "TabulateFusion",
        {
            {{{10, 384}, {10, 384}}, ge::DT_FLOAT16, ge::FORMAT_ND}, // input 0: table
            {{{5}, {5}}, ge::DT_FLOAT16, ge::FORMAT_ND},             // input 1: table_info
            {{{6, 1}, {6, 1}}, ge::DT_FLOAT16, ge::FORMAT_ND},       // input 2: em_x
            {{{2, 3, 4}, {2, 3, 4}}, ge::DT_FLOAT16, ge::FORMAT_ND}, // input 3: em
        },
        {
            {{{2, 4, 4}, {2, 4, 4}}, ge::DT_FLOAT16, ge::FORMAT_ND}, // output 0: descriptor
        },
        {
            gert::TilingContextPara::OpAttr("last_layer_size",
                                            Ops::Math::AnyValue::CreateFrom<int64_t>(static_cast<int64_t>(4))),
        },
        &compileInfo,
        64,                       // number of cores obtained in the tiling phase
        262144,                   // the ubsize obtained in the tiling phase
        4096);                    // specifies the maximum size of the tiling data in the tiling phase
    uint64_t expectTilingKey = 0; // TABULATE_FUSION_MODE_DEFAULT
    // TilingData 字段为 int32_t，UT 框架按 int64_t 读取（little-endian 两两合并）：
    // int64_t[0]=needCoreNum(1)|(nloc(2)<<32)=8589934593, int64_t[1]=nnei(3)|(lastLayerSize(4)<<32)=17179869187,
    // int64_t[2]=lastSizeAlign(64)|(tableRowSize(384)<<32)=1649267441728
    string expectTilingData = "8589934593 17179869187 1649267441728 ";
    // workspace = userWorkspace(0) + sysWorkspace(GetLibApiWorkSpaceSize on ascend950 = 16MB)
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}
