/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file prod_virial_se_a_apt.cpp
 * \brief Kernel entry for prod_virial_se_a operator
 *
 * 单一场景模式（schMode=0），dtype 由 DTYPE_ 宏自动实例化。
 * Input 顺序: net_deriv, in_deriv, rij, nlist, natoms
 * Output 顺序: virial, atom_virial
 */

#include "arch35/prod_virial_se_a_simt.h"

template <uint32_t schMode>
__global__ __aicore__ void prod_virial_se_a(GM_ADDR net_deriv, GM_ADDR in_deriv, GM_ADDR rij, GM_ADDR nlist,
                                            GM_ADDR natoms, GM_ADDR virial, GM_ADDR atom_virial, GM_ADDR workspace,
                                            GM_ADDR tiling)
{
    REGISTER_TILING_DEFAULT(ProdVirialSeATilingData);
    GET_TILING_DATA_WITH_STRUCT(ProdVirialSeATilingData, tilingData, tiling);

    if constexpr (schMode == PROD_VIRIAL_SE_A_TPL_SCH_MODE_DEFAULT) {
        NsProdVirialSeA::Process<DTYPE_NET_DERIV>(net_deriv, in_deriv, rij, nlist, virial, atom_virial, workspace,
                                                  &tilingData);
    }
}
