/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file tabulate_fusion_proto.h
 * \brief Proto declaration for tabulate_fusion operator
 */
#ifndef OPS_OP_PROTO_INC_TABULATE_FUSION_H_
#define OPS_OP_PROTO_INC_TABULATE_FUSION_H_

#include "graph/operator_reg.h"
#include "graph/types.h"

namespace ge {

/**
 *@brief TabulateFusion is the core operator of DeepMD-kit, which fuses the
 *       embedding vectors of the environment matrix into descriptors through
 *       table lookup and 5th-order polynomial interpolation.
 *@par Inputs:
 *Four inputs, including:
 * @li table: A 2D ND Tensor. Must be one of the following types: float16, float, double.
 *            Shape = (N, last_size_align*6), each row has 6 groups of polynomial
 *            coefficients a0~a5, each group has last_size_align elements.
 * @li table_info: A 1D ND Tensor. Must be one of the following types: float16, float, double.
 *                 Shape = (>=5,), the first 5 elements are [lower, upper, max, stride0, stride1]. \n
 * @li em_x: A 2D ND Tensor. Must be one of the following types: float16, float, double.
 *           Shape = (nloc*nnei, 1), environment embedding values.
 * @li em: A 3D ND Tensor. Must be one of the following types: float16, float, double.
 *         Shape = (nloc, nnei, 4), environment matrix with 4 ll coefficients. \n

 *@par Outputs:
 *descriptor: A 3D ND Tensor. Must be one of the following types: float16, float, double.
 *            Shape = (nloc, 4, last_layer_size), the fused descriptor.

 *@par Attributes:
 *@li last_layer_size: An required Int. The last dim size of output descriptor.

 *@par Third-party framework compatibility
 *It is a custom operator of DeepMD-kit, not compatible with any third-party framework.
 */
REG_OP(TabulateFusion)
    .INPUT(table, TensorType({DT_FLOAT16, DT_FLOAT, DT_DOUBLE}))
    .INPUT(table_info, TensorType({DT_FLOAT16, DT_FLOAT, DT_DOUBLE}))
    .INPUT(em_x, TensorType({DT_FLOAT16, DT_FLOAT, DT_DOUBLE}))
    .INPUT(em, TensorType({DT_FLOAT16, DT_FLOAT, DT_DOUBLE}))
    .OUTPUT(descriptor, TensorType({DT_FLOAT16, DT_FLOAT, DT_DOUBLE}))
    .REQUIRED_ATTR(last_layer_size, Int)
    .OP_END_FACTORY_REG(TabulateFusion)

} // namespace ge

#endif // OPS_OP_PROTO_INC_TABULATE_FUSION_H_
