/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file prod_env_mat_a_tiling_data.h
 * \brief Tiling data structure for prod_env_mat_a
 *
 */

#ifndef PROD_ENV_MAT_A_TILING_DATA_H
#define PROD_ENV_MAT_A_TILING_DATA_H

// 常量定义
constexpr int32_t PROD_ENV_MAT_A_MAX_NTYPES = 16;          // 最大原子类型数
constexpr int32_t PROD_ENV_MAT_A_MAX_UB_NBOR_SIZE = 16384; // UB 排序缓冲上限

// UB params buffer layout (int32_t slots)
// [0] nloc  [1] nall  [2] nnei  [3] ntypes  [4] maxNborSize
// [5] nsample  [6] perCoreAtoms  [7] rcutR(bits)  [8] rcutRSmth(bits)
// [9..24]  selA[16]
// [25..41] sec[17]
constexpr int32_t PROD_ENV_MAT_A_UB_PARAMS_INT32 = 42;

struct ProdEnvMatATilingData {
    // === 核数切分参数 ===
    int32_t needCoreNum = 0;  // 实际启动核数
    int32_t totalAtoms = 0;   // 总原子数 = nsample * nloc
    int32_t perCoreAtoms = 0; // 每核处理的原子数

    // === 几何参数 ===
    int32_t nsample = 0;     // 帧数
    int32_t nloc = 0;        // 本地原子数（从输出 shape 推导）
    int32_t nall = 0;        // 所有原子数 = coord.shape[1] / 3
    int32_t nnei = 0;        // 邻居总数 = sum(sel_a)
    int32_t ntypes = 0;      // 原子类型数 = len(sel_a)
    int32_t maxNborSize = 0; // 最大邻居数 = min(nall - 1, MAX_UB_NBOR_SIZE)

    // === 物理参数 ===
    float rcutR = 0.0f;     // 径向截断半径
    float rcutRSmth = 0.0f; // 平滑起始半径

    // === sel_a / sec 数组 (通过 UB 传递给 VF) ===
    int32_t selA[PROD_ENV_MAT_A_MAX_NTYPES] = {0};    // sel_a 数组
    int32_t sec[PROD_ENV_MAT_A_MAX_NTYPES + 1] = {0}; // sec 累积和数组
};

#endif // PROD_ENV_MAT_A_TILING_DATA_H
