/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */
#ifndef EXPERIMENTAL_IM2COL_TILING_KEY_H_
#define EXPERIMENTAL_IM2COL_TILING_KEY_H_

#include "ascendc/host_api/tiling/template_argument.h"

#define IM2COL_PATH_CONTIGUOUS_W 0
#define IM2COL_PATH_GATHER_W 1
#define IM2COL_PATH_GATHER_BOOL 2
#define IM2COL_PATH_CHANNEL_TEMPLATE 3
#define IM2COL_PATH_CHANNEL_TRANSPOSE 4

ASCENDC_TPL_ARGS_DECL(
    Im2col, ASCENDC_TPL_DATATYPE_DECL(D_T, C_DT_FLOAT16, C_DT_FLOAT, C_DT_BF16, C_DT_BOOL, ASCENDC_TPL_INPUT(0)),
    ASCENDC_TPL_UINT_DECL(PATH, 8, ASCENDC_TPL_UI_LIST, IM2COL_PATH_CONTIGUOUS_W, IM2COL_PATH_GATHER_W,
                          IM2COL_PATH_GATHER_BOOL, IM2COL_PATH_CHANNEL_TEMPLATE, IM2COL_PATH_CHANNEL_TRANSPOSE));

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T, C_DT_FLOAT16),
                         ASCENDC_TPL_UINT_SEL(PATH, ASCENDC_TPL_UI_LIST, IM2COL_PATH_CONTIGUOUS_W, IM2COL_PATH_GATHER_W,
                                              IM2COL_PATH_CHANNEL_TEMPLATE, IM2COL_PATH_CHANNEL_TRANSPOSE)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T, C_DT_FLOAT),
                         ASCENDC_TPL_UINT_SEL(PATH, ASCENDC_TPL_UI_LIST, IM2COL_PATH_CONTIGUOUS_W, IM2COL_PATH_GATHER_W,
                                              IM2COL_PATH_CHANNEL_TEMPLATE, IM2COL_PATH_CHANNEL_TRANSPOSE)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T, C_DT_BF16),
                         ASCENDC_TPL_UINT_SEL(PATH, ASCENDC_TPL_UI_LIST, IM2COL_PATH_CONTIGUOUS_W, IM2COL_PATH_GATHER_W,
                                              IM2COL_PATH_CHANNEL_TEMPLATE, IM2COL_PATH_CHANNEL_TRANSPOSE)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DATATYPE_SEL(D_T, C_DT_BOOL),
                         ASCENDC_TPL_UINT_SEL(PATH, ASCENDC_TPL_UI_LIST, IM2COL_PATH_CONTIGUOUS_W,
                                              IM2COL_PATH_GATHER_BOOL)));

#endif // EXPERIMENTAL_IM2COL_TILING_KEY_H_
