/**
 * Copyright (c) 2025-2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file sign_bits_unpack.cpp
 * \brief SignBitsUnpack kernel entry for arch35 (DAV_3510 / Ascend 950)
 */

#include "arch35/sign_bits_unpack.h"

extern "C" __global__ __aicore__ void sign_bits_unpack(GM_ADDR input, GM_ADDR output, GM_ADDR workspace, GM_ADDR tiling)
{
    REGISTER_TILING_DEFAULT(SignBitsUnpackTilingData);
    GET_TILING_DATA_WITH_STRUCT(SignBitsUnpackTilingData, tilingData, tiling);

    NsSignBitsUnpack::SignBitsUnpackKernel<DTYPE_X, DTYPE_Y> op;
    op.Init(input, output, &tilingData);
    op.Process();
}
