/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 *
 * Generated By CANNBot
 */

#ifndef DAWSN_TILING_DATA_H
#define DAWSN_TILING_DATA_H

struct DawsnTilingData {
    int64_t dim0;                // 元素总数量（所有维度展平）
    int64_t coreNum;             // 实际使用核数
    int64_t blockFormer;         // 每个核的基础元素数（512 对齐）
    int64_t blockNum;            // 虚拟 block 数量
    int64_t ubFormer;            // 每个 UB 块的基础元素数（256B 对齐）
    int64_t ubLoopOfFormerBlock; // 首块 UB 循环次数
    int64_t ubTailOfFormerBlock; // 首块尾部元素数
    int64_t ubLoopOfTailBlock;   // 尾块 UB 循环次数
    int64_t ubTailOfTailBlock;   // 尾块尾部元素数
};

#endif // DAWSN_TILING_DATA_H
