#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# ----------------------------------------------------------------------------

# /* Generated By CANNBot */

import numpy as np

# ml_dtypes dependency: used for bfloat16 dtype support
# When ml_dtypes is available, use ml_dtypes.bfloat16 for BF16 golden computation;
# When ml_dtypes is not available, fall back to uint16 view-based bit-level simulation.
try:
    import ml_dtypes
    BF16_DTYPE = ml_dtypes.bfloat16
    HAS_ML_DTYPES = True
except ImportError:
    HAS_ML_DTYPES = False
    BF16_DTYPE = None  # Will use uint16 bit-level simulation as fallback

__golden__ = {
    "kernel": {"stride_add": "stride_add_golden"},
    "aclnn": {"aclnnStrideAdd": "aclnn_stride_add_golden"},
}


def stride_add_golden(x1, x2, *, x1_c1_offset=0, x2_c1_offset=0, c1_len=1, **kwargs):
    '''
    Golden function for stride_add.
    All the parameters (names and order) follow SE doc prototype definition without outputs.
    All the input Tensors are numpy.ndarray.

    Args:
        x1: numpy.ndarray, shape (N, C1_x1, H, W, C0), NC1HWC0 format
        x2: numpy.ndarray, shape (N, C1_x2, H, W, C0), NC1HWC0 format
        x1_c1_offset: int, x1 C1 dimension offset (unit: C1 blocks)
        x2_c1_offset: int, x2 C1 dimension offset (unit: C1 blocks)
        c1_len: int, output y C1 dimension length (unit: C1 blocks)
        **kwargs: {input,output}_{dtypes,ori_shapes,formats,ori_formats},
                  full_soc_version, short_soc_version, testcase_name

    Returns:
        Output tensor, shape (N, c1_len, H, W, C0), dtype same as x1
    '''
    # bfloat16 / float16 compatibility: convert to float32 for computation
    orig_dtype = x1.dtype
    inputs = [x1, x2]

    if orig_dtype.name == 'bfloat16':
        # BF16 handling: prefer ml_dtypes.bfloat16 for proper dtype,
        # fall back to uint16 bit-level simulation if ml_dtypes unavailable
        if HAS_ML_DTYPES:
            # ml_dtypes.bfloat16 supports direct astype to float32
            inputs = [inp.astype(np.float32) for inp in inputs]
            x1_f, x2_f = inputs
        else:
            # uint16 bit-level simulation: view bfloat16 bits as uint16,
            # shift left 16 bits to expand to float32 bit pattern, then view as float32
            inputs = []
            for inp in inputs:
                u16 = inp.view(np.uint16)  # BF16 stored as uint16
                u32 = u16.astype(np.uint32) << 16  # Shift to float32 bit position
                inp_f = u32.view(np.float32)
                inputs.append(inp_f)
            x1_f, x2_f = inputs
    elif orig_dtype.name == 'float16':
        inputs = [inp.astype(np.float32) for inp in inputs]
        x1_f, x2_f = inputs
    else:
        x1_f, x2_f = x1, x2

    # StrideAdd computation: slice from C1 dimension and add
    x1_slice = x1_f[:, x1_c1_offset:x1_c1_offset + c1_len, :, :, :]
    x2_slice = x2_f[:, x2_c1_offset:x2_c1_offset + c1_len, :, :, :]
    result = x1_slice + x2_slice

    # Convert back to original dtype
    if orig_dtype.name == 'bfloat16':
        if HAS_ML_DTYPES:
            result = result.astype(BF16_DTYPE, copy=False)
        else:
            # uint16 bit-level simulation: truncate float32 to bfloat16
            u32 = result.view(np.uint32)
            u16 = (u32 >> 16).astype(np.uint16)  # Truncate lower 16 bits
            result = u16.view(BF16_DTYPE if HAS_ML_DTYPES else np.dtype('V2'))
            # When ml_dtypes unavailable, result is stored as opaque 2-byte dtype;
            # Golden comparison framework should handle uint16→BF16 bit comparison
    elif orig_dtype.name == 'float16':
        result = result.astype(np.float16, copy=False)

    return result


def _aclnn_stride_add_impl(x1_tensor, x2_tensor, x1_c1_offset, x2_c1_offset, c1_len):
    """Common implementation for aclnn stride_add golden."""
    import torch

    # Extract scalar values
    x1_off = int(x1_c1_offset.item()) if hasattr(x1_c1_offset, 'item') else int(x1_c1_offset)
    x2_off = int(x2_c1_offset.item()) if hasattr(x2_c1_offset, 'item') else int(x2_c1_offset)
    c1 = int(c1_len.item()) if hasattr(c1_len, 'item') else int(c1_len)

    # Handle dtype conversion for bfloat16
    orig_dtype = x1_tensor.dtype
    need_convert = orig_dtype in (torch.bfloat16, torch.float16)

    if need_convert:
        x1_tensor = x1_tensor.to(torch.float32)
        x2_tensor = x2_tensor.to(torch.float32)

    # Slice and add
    x1_slice = x1_tensor[:, x1_off:x1_off + c1, :, :, :]
    x2_slice = x2_tensor[:, x2_off:x2_off + c1, :, :, :]
    result = x1_slice + x2_slice

    if need_convert:
        result = result.to(orig_dtype)

    return result


def aclnn_stride_add_golden(x1, x2, x1_c1_offset, x2_c1_offset, c1_len, y, **kwargs):
    '''
    Aclnn golden for aclnnStrideAdd.
    All the parameters (name & order) follow \
        function `aclnnStrideAddGetWorkspaceSize` in @aclnn_stride_add.h \
        without `workspaceSize` & `executor`.
    When all dtypes are natively supported by torch, \
        the Tensors in the parameters are all torch.Tensor. \
        Conversely, when not, the Tensors in the parameters are all numpy.ndarray.

    Args:
        kwargs: tensor_{dtypes, formats}, scalar_dtypes, short_soc_version, testcase_name

    Returns:
        Output tensors.
    '''
    return _aclnn_stride_add_impl(x1, x2, x1_c1_offset, x2_c1_offset, c1_len)