/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file radix_sort_proto.h
 * \brief
 */
#ifndef OPS_OP_PROTO_INC_RADIX_SORT_H_
#define OPS_OP_PROTO_INC_RADIX_SORT_H_

#include "graph/operator_reg.h"
#include "graph/types.h"

namespace ge {

/**
*@brief LSD radix sort for 1D integer tensors.
*@par Inputs:
*One input, including:
* @li x: A 1D Tensor. Supported type: int32, uint32, int64, uint64. Supported format: ND.
*@par Attributes:
* @li descending: An optional attribute indicates descending sort or not. Defaults to false.
*@par Outputs:
* @li sorted_values: A 1D Tensor. Must have the same type and shape as x.
* @li sorted_indices: A 1D Tensor. Original indices of sorted values. Dtype is int64.
*@attention Constraints:
* - Only 1D input is supported.
* - The operator uses LSD radix sort algorithm (8-bit per pass, 256 bins).
* - The sort is guaranteed to be stable.
*/
REG_OP(RadixSort)
    .INPUT(x, TensorType({DT_INT32, DT_UINT32, DT_INT64, DT_UINT64}))
    .OUTPUT(sorted_values, TensorType({DT_INT32, DT_UINT32, DT_INT64, DT_UINT64}))
    .OUTPUT(sorted_indices, TensorType({DT_INT64}))
    .ATTR(descending, Bool, false)
    .OP_END_FACTORY_REG(RadixSort)

} // namespace ge

#endif // OPS_OP_PROTO_INC_RADIX_SORT_H_
