/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 *
 * Generated By CANNBot
 */

/*!
 * \file spence_proto.h
 * \brief Spence 算子 GE IR 注册
 */
#ifndef OPS_OP_PROTO_INC_SPENCE_H_
#define OPS_OP_PROTO_INC_SPENCE_H_

#include "graph/operator_reg.h"
#include "graph/types.h"

namespace ge {

/**
*@brief Computes the Spence function (dilogarithm): S(x) = -integral_0^x ln(1-t)/t dt.
*@par Inputs:
*One input:
 * @li x: A ND Tensor. Must be one of the following types: float16, float32, float64, bfloat16.
 *
 *@par Outputs:
 *y: A ND Tensor. Same type as x.
 */
REG_OP(Spence)
    .INPUT(x, TensorType({DT_BF16, DT_FLOAT16, DT_FLOAT, DT_DOUBLE}))
    .OUTPUT(y, TensorType({DT_BF16, DT_FLOAT16, DT_FLOAT, DT_DOUBLE}))
    .OP_END_FACTORY_REG(Spence)

} // namespace ge

#endif // OPS_OP_PROTO_INC_SPENCE_H_
