/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/**
 * @file test_geir_reduce_std_with_mean_dynamic.cpp
 * @brief GE IR dynamic example for ReduceStdWithMean
 *
 * Two scenarios in separate graphs on the same Session:
 *   unknown_dim_minus_1:  declared shape [-1,-1], dim=[1], 3 concrete 2-D shapes
 *   unknown_rank_minus_2: declared shape [-2],   dim=[],   3 concrete shapes (rank 1/2/3)
 *
 * invert=false, correction=1 (sample std), keepdim=false, epsilon=0.001.
 * mean is pre-computed per concrete shape (row-mean for -1; global-mean for -2).
 */

#include <iostream>
#include <fstream>
#include <string.h>
#include <stdint.h>
#include <vector>
#include <string>
#include <map>
#include <ctime>
#include <cmath>

#include "graph.h"
#include "types.h"
#include "tensor.h"
#include "ge_error_codes.h"
#include "ge_api_types.h"
#include "ge_api.h"
#include "array_ops.h"
#include "ge_ir_build.h"

#include "../../op_graph/reduce_std_with_mean_proto.h"

#define FAILED -1
#define SUCCESS 0

using namespace ge;
using std::map;
using std::string;
using std::vector;

static string GetTime()
{
    time_t timep;
    time(&timep);
    char tmp[64];
    strftime(tmp, sizeof(tmp), "%Y-%m-%d %H:%M:%S,000", localtime(&timep));
    return string(tmp);
}

static string ShapeToString(const vector<int64_t>& shape)
{
    string s = "[";
    for (size_t i = 0; i < shape.size(); ++i) {
        s += std::to_string(shape[i]);
        if (i + 1 < shape.size())
            s += ",";
    }
    s += "]";
    return s;
}

// Generate ramp input data for x
static vector<float> GenInputData(const vector<int64_t>& shape)
{
    size_t n = 1;
    for (auto d : shape)
        n *= static_cast<size_t>(d);
    vector<float> buf(n);
    for (size_t i = 0; i < n; ++i) {
        buf[i] = 0.5f + 0.25f * static_cast<float>(i);
    }
    return buf;
}

// Compute row-mean (along last axis) and broadcast — for dim=[1] scenario
static vector<float> GenRowMean(const vector<int64_t>& shape)
{
    size_t rows = 1;
    for (size_t i = 0; i + 1 < shape.size(); ++i)
        rows *= static_cast<size_t>(shape[i]);
    size_t cols = static_cast<size_t>(shape.back());
    vector<float> data = GenInputData(shape);
    vector<float> mean(rows * cols);
    for (size_t r = 0; r < rows; ++r) {
        float sum = 0.0f;
        for (size_t c = 0; c < cols; ++c)
            sum += data[r * cols + c];
        float m = sum / static_cast<float>(cols);
        for (size_t c = 0; c < cols; ++c)
            mean[r * cols + c] = m;
    }
    return mean;
}

// Compute global mean — for dim=[] (all-reduce) scenario
static vector<float> GenGlobalMean(const vector<int64_t>& shape)
{
    vector<float> data = GenInputData(shape);
    size_t n = data.size();
    float sum = 0.0f;
    for (size_t i = 0; i < n; ++i)
        sum += data[i];
    float m = sum / static_cast<float>(n);
    vector<float> mean(n, m);
    return mean;
}

// Golden: sqrt(sum((x-mean)^2, axis) / (N-1))  [correction=1, invert=false]
static vector<float> ComputeGoldenDim1(const vector<float>& x, const vector<float>& mean, size_t rows, size_t cols)
{
    vector<float> out(rows);
    for (size_t r = 0; r < rows; ++r) {
        float ss = 0.0f;
        for (size_t c = 0; c < cols; ++c) {
            float d = x[r * cols + c] - mean[r * cols + c];
            ss += d * d;
        }
        float denom = static_cast<float>(cols) - 1.0f; // correction=1
        out[r] = (denom > 0.0f) ? std::sqrt(ss / denom) : 0.0f;
    }
    return out;
}

static float ComputeGoldenAllReduce(const vector<float>& x, const vector<float>& mean)
{
    float ss = 0.0f;
    for (size_t i = 0; i < x.size(); ++i) {
        float d = x[i] - mean[i];
        ss += d * d;
    }
    float n = static_cast<float>(x.size());
    float denom = n - 1.0f; // correction=1
    return (denom > 0.0f) ? std::sqrt(ss / denom) : 0.0f;
}

static Tensor MakeTensor(const vector<int64_t>& shape, DataType dt, const vector<float>& data)
{
    TensorDesc desc = TensorDesc(ge::Shape(shape), FORMAT_ND, dt);
    desc.SetPlacement(ge::kPlacementHost);
    desc.SetFormat(FORMAT_ND);
    desc.SetRealDimCnt(shape.size());
    size_t n = data.size();
    return Tensor(desc, reinterpret_cast<uint8_t*>(const_cast<float*>(data.data())), n * sizeof(float));
}

struct ScenarioResult {
    int passed = 0;
    int total = 0;
};

// Scenario 1: unknown_dim_minus_1
// Declared shape [-1, -1], dim=[1], 3 concrete 2-D shapes
static ScenarioResult RunScenarioDimMinus1(Session* session)
{
    ScenarioResult sr;
    vector<vector<int64_t>> shapes = {{2, 4}, {4, 8}, {8, 16}};
    sr.total = static_cast<int>(shapes.size());

    string scenarioName = "unknown_dim_minus_1";
    Graph graph(("reduce_std_with_mean_" + scenarioName).c_str());

    auto rsm = op::ReduceStdWithMean(scenarioName.c_str());
    rsm.set_attr_dim(vector<int64_t>{1});
    rsm.set_attr_unbiased(true);
    rsm.set_attr_keepdim(false);
    rsm.set_attr_invert(false);
    rsm.set_attr_epsilon(0.001f);
    rsm.set_attr_correction(1);

    // Declared dynamic shape [-1, -1]
    vector<int64_t> declShape = {-1, -1};
    TensorDesc xDesc = TensorDesc(ge::Shape(declShape), FORMAT_ND, DT_FLOAT);
    xDesc.SetPlacement(ge::kPlacementHost);
    xDesc.SetFormat(FORMAT_ND);
    xDesc.SetRealDimCnt(2);

    auto dataX = op::Data("placeholder_x").set_attr_index(0);
    dataX.update_input_desc_x(xDesc);
    dataX.update_output_desc_y(xDesc);
    graph.AddOp(dataX);
    rsm.set_input_x(dataX);

    auto dataMean = op::Data("placeholder_mean").set_attr_index(1);
    dataMean.update_input_desc_x(xDesc);
    dataMean.update_output_desc_y(xDesc);
    graph.AddOp(dataMean);
    rsm.set_input_mean(dataMean);

    TensorDesc yDesc = TensorDesc(ge::Shape(vector<int64_t>{-1}), FORMAT_ND, DT_FLOAT);
    rsm.update_output_desc_y(yDesc);

    vector<Operator> inputs = {dataX, dataMean};
    vector<Operator> outputs = {rsm};
    graph.SetInputs(inputs).SetOutputs(outputs);

    map<AscendString, AscendString> graphOptions = {};
    Status ret = session->AddGraph(10, graph, graphOptions);
    if (ret != SUCCESS) {
        printf("AddGraph failed for %s\n", scenarioName.c_str());
        return sr;
    }

    printf("Scenario %s, declared shape [-1,-1]\n", scenarioName.c_str());

    for (const auto& shape : shapes) {
        printf("Run concrete shape %s\n", ShapeToString(shape).c_str());
        vector<float> xData = GenInputData(shape);
        vector<float> meanData = GenRowMean(shape);

        vector<ge::Tensor> feeds;
        feeds.push_back(MakeTensor(shape, DT_FLOAT, xData));
        feeds.push_back(MakeTensor(shape, DT_FLOAT, meanData));

        vector<ge::Tensor> output;
        ret = session->RunGraph(10, feeds, output);
        if (ret != SUCCESS) {
            printf("RunGraph failed for shape %s\n", ShapeToString(shape).c_str());
            continue;
        }
        if (output.empty()) {
            printf("No output for shape %s\n", ShapeToString(shape).c_str());
            continue;
        }

        // Verify output shape: (rows,)
        size_t rows = static_cast<size_t>(shape[0]);
        size_t cols = static_cast<size_t>(shape[1]);
        auto outShape = output[0].GetTensorDesc().GetShape();
        bool shapeOk = (static_cast<size_t>(outShape.GetDimNum()) == 1 &&
                        static_cast<size_t>(outShape.GetDim(0)) == rows);
        bool dtypeOk = (output[0].GetTensorDesc().GetDataType() == DT_FLOAT);

        // Verify values
        vector<float> golden = ComputeGoldenDim1(xData, meanData, rows, cols);
        const float* outData = reinterpret_cast<const float*>(output[0].GetData());
        bool valuesOk = true;
        for (size_t i = 0; i < rows; ++i) {
            if (std::abs(outData[i] - golden[i]) > 0.001f) {
                valuesOk = false;
                break;
            }
        }

        if (shapeOk && dtypeOk && valuesOk) {
            printf("Shape, dtype and values PASSED for %s\n", ShapeToString(shape).c_str());
            sr.passed++;
        } else {
            printf("Shape, dtype and values FAILED for %s (shape=%d dtype=%d values=%d)\n",
                   ShapeToString(shape).c_str(), shapeOk, dtypeOk, valuesOk);
        }
    }

    printf("Scenario %s summary: %d/%d passed\n", scenarioName.c_str(), sr.passed, sr.total);
    return sr;
}

// Scenario 2: unknown_rank_minus_2
// Declared shape [-2], dim=[] (all-reduce), 3 concrete shapes with rank 1/2/3
static ScenarioResult RunScenarioRankMinus2(Session* session)
{
    ScenarioResult sr;
    vector<vector<int64_t>> shapes = {{8}, {2, 4}, {2, 3, 4}};
    sr.total = static_cast<int>(shapes.size());

    string scenarioName = "unknown_rank_minus_2";
    Graph graph(("reduce_std_with_mean_" + scenarioName).c_str());

    auto rsm = op::ReduceStdWithMean(scenarioName.c_str());
    rsm.set_attr_dim(vector<int64_t>{}); // all-reduce
    rsm.set_attr_unbiased(true);
    rsm.set_attr_keepdim(false);
    rsm.set_attr_invert(false);
    rsm.set_attr_epsilon(0.001f);
    rsm.set_attr_correction(1);

    // Declared dynamic shape [-2] (unknown rank)
    vector<int64_t> declShape = {-2};
    TensorDesc xDesc = TensorDesc(ge::Shape(declShape), FORMAT_ND, DT_FLOAT);
    xDesc.SetPlacement(ge::kPlacementHost);
    xDesc.SetFormat(FORMAT_ND);

    auto dataX = op::Data("placeholder_x").set_attr_index(0);
    dataX.update_input_desc_x(xDesc);
    dataX.update_output_desc_y(xDesc);
    graph.AddOp(dataX);
    rsm.set_input_x(dataX);

    auto dataMean = op::Data("placeholder_mean").set_attr_index(1);
    dataMean.update_input_desc_x(xDesc);
    dataMean.update_output_desc_y(xDesc);
    graph.AddOp(dataMean);
    rsm.set_input_mean(dataMean);

    TensorDesc yDesc = TensorDesc(ge::Shape(vector<int64_t>{-2}), FORMAT_ND, DT_FLOAT);
    rsm.update_output_desc_y(yDesc);

    vector<Operator> inputs = {dataX, dataMean};
    vector<Operator> outputs = {rsm};
    graph.SetInputs(inputs).SetOutputs(outputs);

    map<AscendString, AscendString> graphOptions = {};
    Status ret = session->AddGraph(20, graph, graphOptions);
    if (ret != SUCCESS) {
        printf("AddGraph failed for %s\n", scenarioName.c_str());
        return sr;
    }

    printf("Scenario %s, declared shape [-2]\n", scenarioName.c_str());

    for (const auto& shape : shapes) {
        printf("Run concrete shape %s\n", ShapeToString(shape).c_str());
        vector<float> xData = GenInputData(shape);
        vector<float> meanData = GenGlobalMean(shape);

        vector<ge::Tensor> feeds;
        feeds.push_back(MakeTensor(shape, DT_FLOAT, xData));
        feeds.push_back(MakeTensor(shape, DT_FLOAT, meanData));

        vector<ge::Tensor> output;
        ret = session->RunGraph(20, feeds, output);
        if (ret != SUCCESS) {
            printf("RunGraph failed for shape %s\n", ShapeToString(shape).c_str());
            continue;
        }
        if (output.empty()) {
            printf("No output for shape %s\n", ShapeToString(shape).c_str());
            continue;
        }

        // Verify output: scalar (0-D or 1-D with size 1)
        auto outShape = output[0].GetTensorDesc().GetShape();
        size_t outDims = static_cast<size_t>(outShape.GetDimNum());
        bool shapeOk = (outDims == 0 || (outDims == 1 && outShape.GetDim(0) == 1));
        bool dtypeOk = (output[0].GetTensorDesc().GetDataType() == DT_FLOAT);

        // Verify values
        float golden = ComputeGoldenAllReduce(xData, meanData);
        const float* outData = reinterpret_cast<const float*>(output[0].GetData());
        bool valuesOk = (std::abs(outData[0] - golden) < 0.001f);

        if (shapeOk && dtypeOk && valuesOk) {
            printf("Shape, dtype and values PASSED for %s\n", ShapeToString(shape).c_str());
            sr.passed++;
        } else {
            printf("Shape, dtype and values FAILED for %s (shape=%d dtype=%d values=%d)\n",
                   ShapeToString(shape).c_str(), shapeOk, dtypeOk, valuesOk);
        }
    }

    printf("Scenario %s summary: %d/%d passed\n", scenarioName.c_str(), sr.passed, sr.total);
    return sr;
}

int main(int argc, char* argv[])
{
    (void)argc;
    (void)argv;

    printf("%s - INFO - [XIR]: Start dynamic GEIR verification for ReduceStdWithMean\n", GetTime().c_str());

    std::map<AscendString, AscendString> globalOptions = {{"ge.exec.deviceId", "0"}, {"ge.graphRunMode", "1"}};
    Status ret = ge::GEInitialize(globalOptions);
    if (ret != SUCCESS) {
        printf("%s - ERROR - [XIR]: Initialize ge failed\n", GetTime().c_str());
        return FAILED;
    }
    printf("%s - INFO - [XIR]: Initialize ge success\n", GetTime().c_str());

    std::map<AscendString, AscendString> buildOptions = {};
    ge::Session* session = new Session(buildOptions);
    if (session == nullptr) {
        printf("%s - ERROR - [XIR]: Create session failed\n", GetTime().c_str());
        GEFinalize();
        return FAILED;
    }
    printf("%s - INFO - [XIR]: Create session success\n", GetTime().c_str());

    ScenarioResult dimResult = RunScenarioDimMinus1(session);
    ScenarioResult rankResult = RunScenarioRankMinus2(session);

    bool allPassed = (dimResult.passed == dimResult.total) && (rankResult.passed == rankResult.total);

    delete session;
    ret = ge::GEFinalize();
    if (ret != SUCCESS) {
        printf("%s - ERROR - [XIR]: Finalize failed\n", GetTime().c_str());
        return FAILED;
    }
    printf("%s - INFO - [XIR]: Finalize success\n", GetTime().c_str());

    if (allPassed) {
        printf("ReduceStdWithMean dynamic GEIR verification PASSED (-1 and -2)\n");
        return SUCCESS;
    } else {
        printf("ReduceStdWithMean dynamic GEIR verification FAILED (-1 and -2)\n");
        return FAILED;
    }
}
