/**
 * Copyright (c) 2025-2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#ifndef OP_PROTO_REDUCE_STD_V2_UPDATE_H
#define OP_PROTO_REDUCE_STD_V2_UPDATE_H

#include "graph/operator_reg.h"
#include "graph/types.h"

namespace ge {

/**
* @brief Receives the original input x and the pre-computed mean, reduces along
* the specified dimensions to compute the sum of squared deviations, then divides
* by N - correction to obtain the variance or standard deviation.

* @par Inputs:
* x: A tensor. Format supports ND. Must be one of the following types:
*    float32, float16, bfloat16. \n
* mean: Pre-computed mean tensor (already Expand-broadcast to x's shape),
*       same dtype/format as x. \n

* @par Attributes:
* @li dim: Required ListInt. Dimensions to reduce, supports negative index.
*          If empty, reduces all dimensions.
*          Must be in range [-rank(x), rank(x)). \n
* @li if_std: Optional Bool, default false. false = output variance,
*             true = output standard deviation (sqrt). \n
* @li unbiased: Optional Bool, default true. true = unbiased (N-1),
*               false = biased (N). Mutually exclusive with correction. \n
* @li keepdim: Optional Bool, default false. Whether to keep reduced dims
*              (set to 1 if true, removed if false). \n
* @li correction: Optional Int, default 1. Bessel correction factor.
*                 0 = biased (N), 1 = unbiased (N-1). Only 0 and 1 supported. \n

* @par Outputs:
* output_var: A tensor, variance (if_std=false) or standard deviation
*             (if_std=true). Same type and format as x. \n

* @par Third-party framework compatibility
* Compatible with the Pytorch operator var and var_mean.
*/
#ifndef OPS_PROTO_DEF_REDUCESTDV2UPDATE
#define OPS_PROTO_DEF_REDUCESTDV2UPDATE
REG_OP(ReduceStdV2Update)
    .INPUT(x, TensorType({DT_FLOAT, DT_FLOAT16, DT_BF16}))
    .INPUT(mean, TensorType({DT_FLOAT, DT_FLOAT16, DT_BF16}))
    .OUTPUT(output_var, TensorType({DT_FLOAT, DT_FLOAT16, DT_BF16}))
    .REQUIRED_ATTR(dim, ListInt)
    .ATTR(if_std, Bool, false)
    .ATTR(unbiased, Bool, true)
    .ATTR(keepdim, Bool, false)
    .ATTR(correction, Int, 1)
    .OP_END_FACTORY_REG(ReduceStdV2Update)
#endif

} // namespace ge

#endif // OP_PROTO_REDUCE_STD_V2_UPDATE_H
