/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file acosh_grad_kernel.h
 * \brief AcoshGrad 算子 Kernel 类定义（arch35 / DAV_3510）
 *
 * 公式: z = dy / sqrt(y² - 1)
 * 计算路径 (FP16/BF16): Cast→FP32 → Mul → Adds(-1) → Sqrt → Div → Cast→原dtype
 * 计算路径 (FP32): Mul → Adds(-1) → Sqrt → Div
 * Double Buffer 流水线并行
 *
 * 关键设计约束（来自迭代二穿刺验证）：
 *   1. GlobalTensor 多 tile 不自动推进：每次 tile 循环前必须显式调用
 *      SetGlobalBuffer(base + offset, remain) 更新 GM 指针偏移
 *   2. TBuf 必须用独立实例：3 个独立 TBuf<VECCALC>（bufSlot0_/1_/2_），
 *      禁止单 TBuf + GetWithOffset（totalNum=1 时仅 12 字节导致 +Inf）
 *
 * dtype 通过 DTYPE_Y 宏指定（由 CANN 编译系统根据 op_def 输入名 "y" 自动生成）
 */
#ifndef ACOSH_GRAD_KERNEL_H
#define ACOSH_GRAD_KERNEL_H

#include "kernel_operator.h"
#include "kernel_tiling/kernel_tiling.h"
#include "acosh_grad_tiling_data.h"
#include "acosh_grad_tiling_key.h"

namespace NsAcoshGrad {

using namespace AscendC;

template <typename T>
class AcoshGradKernel {
    static constexpr int32_t BUFFER_NUM = 2;  // Double Buffer

public:
    __aicore__ inline AcoshGradKernel() {};

    __aicore__ inline void Init(GM_ADDR y, GM_ADDR dy, GM_ADDR z,
                                const AcoshGradTilingData* tilingData);
    __aicore__ inline void Process();

private:
    __aicore__ inline void CopyIn(int64_t currentNum);
    __aicore__ inline void Compute(int64_t currentNum);
    __aicore__ inline void CopyOut(int64_t currentNum);

private:
    TPipe pipe;
    TQue<TPosition::VECIN, BUFFER_NUM> inQueueY;
    TQue<TPosition::VECIN, BUFFER_NUM> inQueueDy;
    TQue<TPosition::VECOUT, BUFFER_NUM> outQueueZ;

    // 3 个独立 FP32 中间计算 buffer（禁止合并为单 TBuf + GetWithOffset）
    // 穿刺 probe_fp16_overflow 验证：单 TBuf 在 totalNum=1 时仅分配 12 字节，
    // 导致 slot 地址重叠，输出 +Inf
    TBuf<TPosition::VECCALC> bufSlot0_;  // yFp32 → dyFp32 → result
    TBuf<TPosition::VECCALC> bufSlot1_;  // ySq → ySqM1
    TBuf<TPosition::VECCALC> bufSlot2_;  // sqrtVal

    GlobalTensor<T> yGM;
    GlobalTensor<T> dyGM;
    GlobalTensor<T> zGM;

    // Base GM 地址（用于 tile 偏移计算，穿刺 probe_large_shape 验证必须保存）
    __gm__ T* yBase_ = nullptr;
    __gm__ T* dyBase_ = nullptr;
    __gm__ T* zBase_ = nullptr;

    int64_t blockLength_ = 0;
    int64_t ubLength_ = 0;
};

template <typename T>
__aicore__ inline void AcoshGradKernel<T>::Init(
    GM_ADDR y, GM_ADDR dy, GM_ADDR z, const AcoshGradTilingData* tilingData)
{
    int64_t remainderLength = tilingData->totalNum - tilingData->blockFactor * AscendC::GetBlockIdx();
    blockLength_ = (remainderLength > tilingData->blockFactor) ? tilingData->blockFactor : remainderLength;
    // blockIdx 过大时 remainderLength 可能为负，钳为 0 避免后续计算出错（参考 ndtri_kernel.h:152-154）
    if (blockLength_ < 0) {
        blockLength_ = 0;
    }
    ubLength_ = tilingData->ubFactor;

    // 保存 base GM 地址，Process 中按 tile 偏移调用 SetGlobalBuffer
    // （穿刺 probe_large_shape 验证：DataCopyPad 不自动推进 GlobalTensor 地址）
    yBase_ = (__gm__ T*)y + tilingData->blockFactor * AscendC::GetBlockIdx();
    dyBase_ = (__gm__ T*)dy + tilingData->blockFactor * AscendC::GetBlockIdx();
    zBase_ = (__gm__ T*)z + tilingData->blockFactor * AscendC::GetBlockIdx();

    // GlobalTensor 初始设置：指向第一个 tile
    yGM.SetGlobalBuffer(yBase_, blockLength_);
    dyGM.SetGlobalBuffer(dyBase_, blockLength_);
    zGM.SetGlobalBuffer(zBase_, blockLength_);

    pipe.InitBuffer(inQueueY, BUFFER_NUM, ubLength_ * sizeof(T));
    pipe.InitBuffer(inQueueDy, BUFFER_NUM, ubLength_ * sizeof(T));
    pipe.InitBuffer(outQueueZ, BUFFER_NUM, ubLength_ * sizeof(T));

    // FP32 中间 buffer：3 个独立 TBuf 实例（禁止合并为单 TBuf）
    // 穿刺 probe_fp16_overflow 验证：单 TBuf + GetWithOffset 在 totalNum=1 时
    // 仅分配 12 字节（3*sizeof(float)），slot 地址重叠导致输出 +Inf
    pipe.InitBuffer(bufSlot0_, ubLength_ * sizeof(float));
    pipe.InitBuffer(bufSlot1_, ubLength_ * sizeof(float));
    pipe.InitBuffer(bufSlot2_, ubLength_ * sizeof(float));
}

template <typename T>
__aicore__ inline void AcoshGradKernel<T>::CopyIn(int64_t currentNum)
{
    LocalTensor<T> yLocal = inQueueY.template AllocTensor<T>();
    LocalTensor<T> dyLocal = inQueueDy.template AllocTensor<T>();

    // DataCopyPad 直接从 GlobalTensor 当前地址读取（Process 中已推进到正确 tile）
    DataCopyParams copyParams;
    copyParams.blockCount = 1;
    copyParams.blockLen = currentNum * sizeof(T);
    copyParams.srcStride = 0;
    copyParams.dstStride = 0;

    DataCopyPad(yLocal, yGM, copyParams, {false, 0, 0, 0});
    DataCopyPad(dyLocal, dyGM, copyParams, {false, 0, 0, 0});

    inQueueY.EnQue(yLocal);
    inQueueDy.EnQue(dyLocal);
}

template <typename T>
__aicore__ inline void AcoshGradKernel<T>::Compute(int64_t currentNum)
{
    LocalTensor<T> yLocal = inQueueY.template DeQue<T>();
    LocalTensor<T> dyLocal = inQueueDy.template DeQue<T>();
    LocalTensor<T> zLocal = outQueueZ.template AllocTensor<T>();

    // 从 3 个独立 TBuf 获取 FP32 中间 Buffer（无地址冲突）
    // 穿刺 probe_fp16_overflow 验证：独立 TBuf 实例保证地址不重叠
    LocalTensor<float> slot0 = bufSlot0_.Get<float>();  // yFp32 → dyFp32 → result
    LocalTensor<float> slot1 = bufSlot1_.Get<float>();  // ySq → ySqM1
    LocalTensor<float> slot2 = bufSlot2_.Get<float>();  // sqrtVal

    if constexpr (std::is_same_v<T, float>) {
        // FP32 路径：直接计算，无需 Cast
        // slot0 = y² (临时)
        AscendC::Mul<float>(slot0, yLocal, yLocal, currentNum);
        // slot1 = y² - 1
        AscendC::Adds<float>(slot1, slot0, -1.0f, currentNum);
        // slot2 = sqrt(y² - 1)
        AscendC::Sqrt<float>(slot2, slot1, currentNum);
        // zLocal = dy / sqrt(y² - 1)
        AscendC::Div<float>(zLocal, dyLocal, slot2, currentNum);
    } else {
        // FP16/BF16 路径：Cast→FP32→计算→Cast
        // Step 1: Cast y → FP32 (slot0)
        AscendC::Cast<float, T>(slot0, yLocal, AscendC::RoundMode::CAST_NONE, currentNum);
        // Step 2: y² (slot1)
        AscendC::Mul<float>(slot1, slot0, slot0, currentNum);
        // Step 3: y² - 1 (slot1, in-place)
        AscendC::Adds<float>(slot1, slot1, -1.0f, currentNum);
        // Step 4: sqrt(y² - 1) (slot2)
        AscendC::Sqrt<float>(slot2, slot1, currentNum);
        // Step 5: Cast dy → FP32 (slot0, 复用)
        AscendC::Cast<float, T>(slot0, dyLocal, AscendC::RoundMode::CAST_NONE, currentNum);
        // Step 6: dy / sqrt (slot0, 复用)
        AscendC::Div<float>(slot0, slot0, slot2, currentNum);
        // Step 7: Cast result → 原 dtype (zLocal)
        AscendC::Cast<T, float>(zLocal, slot0, AscendC::RoundMode::CAST_ROUND, currentNum);
    }

    outQueueZ.template EnQue<T>(zLocal);
    inQueueY.FreeTensor(yLocal);
    inQueueDy.FreeTensor(dyLocal);
}

template <typename T>
__aicore__ inline void AcoshGradKernel<T>::CopyOut(int64_t currentNum)
{
    LocalTensor<T> zLocal = outQueueZ.template DeQue<T>();

    // DataCopyPad 直接写入 GlobalTensor 当前地址（Process 中已推进到正确 tile）
    DataCopyParams copyParams;
    copyParams.blockCount = 1;
    copyParams.blockLen = currentNum * sizeof(T);
    copyParams.srcStride = 0;
    copyParams.dstStride = 0;

    DataCopyPad(zGM, zLocal, copyParams);
    outQueueZ.FreeTensor(zLocal);
}

template <typename T>
__aicore__ inline void AcoshGradKernel<T>::Process()
{
    if (blockLength_ == 0) return;

    int64_t loopCount = (blockLength_ + ubLength_ - 1) / ubLength_;
    for (int64_t i = 0; i < loopCount; i++) {
        int64_t currentNum = (i == (loopCount - 1)) ? (blockLength_ - ubLength_ * i) : ubLength_;

        // 显式推进 GlobalTensor 到当前 tile 偏移
        // （穿刺 probe_large_shape 验证：DataCopyPad 不自动推进 GlobalTensor 地址，
        //   多 tile 循环必须在每次迭代前重新调用 SetGlobalBuffer）
        int64_t offset = i * ubLength_;
        int64_t remain = blockLength_ - offset;
        yGM.SetGlobalBuffer(yBase_ + offset, remain);
        dyGM.SetGlobalBuffer(dyBase_ + offset, remain);
        zGM.SetGlobalBuffer(zBase_ + offset, remain);

        CopyIn(currentNum);
        Compute(currentNum);
        CopyOut(currentNum);
    }
}

} // namespace NsAcoshGrad

#endif // ACOSH_GRAD_KERNEL_H
