/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 *
 * Generated By CANNBot
 */

/*!
 * \file bessel_i0e_tiling_arch35.cpp
 * \brief BesselI0e Host 侧 Tiling 计算 (arch35)
 */

#include "bessel_i0e_tiling_arch35.h"
#include "register/op_def_registry.h"
#include "op_common/log/log.h"
#include "op_common/op_host/util/math_util.h"
#include "op_common/op_host/util/platform_util.h"
#include "register/tilingdata_base.h"
#include "math/bessel_i0e/op_kernel/arch35/bessel_i0e_tiling_data.h"
#include "math/bessel_i0e/op_kernel/arch35/bessel_i0e_tiling_key.h"

namespace optiling {

using Ops::Base::CeilAlign;
using Ops::Base::CeilDiv;
using Ops::Base::FloorAlign;
using Ops::Base::FloorDiv;
using Ops::Base::GetUbBlockSize;

constexpr uint32_t WS_SYS_SIZE = 0U;
constexpr int64_t TYPE_SIZE_FP32 = 4;
constexpr size_t WORKSPACE_NUM = 1;
// FP32 路径实际分配 7 个 buffer：1 VECIN + 5 VECCALC + 1 VECOUT
// FP16/BF16 路径实际分配 9 个 buffer：1 VECIN + 5 VECCALC + 2 extra VECCALC + 1 VECOUT
// 使用 11 作为除数（留安全余量），确保 9 * (ubSize/11) < ubSize
constexpr int64_t BUFFER_NUM_FP32 = 11;

static const gert::Shape g_vec_1_shape = {1};

static inline const gert::Shape EnsureNotScalar(const gert::Shape& in_shape)
{
    if (in_shape.GetDimNum() == 0) {
        return g_vec_1_shape;
    }
    return in_shape;
}

// 获取平台信息（ubSize, coreNum）
static ge::graphStatus GetPlatformInfo(gert::TilingContext* context, uint64_t* ubSize, int64_t* coreNum)
{
    fe::PlatFormInfos* platformInfoPtr = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfoPtr);
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);
    *coreNum = ascendcPlatform.GetCoreNumAiv();
    OP_CHECK_IF(*coreNum == 0, OP_LOGE(context, "coreNum is 0"), return ge::GRAPH_FAILED);
    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, *ubSize);
    OP_CHECK_IF(*ubSize == 0, OP_LOGE(context, "ubSize is 0"), return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

// 获取输入 shape 和 dtype 信息
static ge::graphStatus GetShapeAttrsInfo(gert::TilingContext* context, int64_t* totalIdx, ge::DataType* dataType)
{
    auto inputX = context->GetInputShape(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputX);
    auto inputShapeX = EnsureNotScalar(inputX->GetStorageShape());

    *totalIdx = inputShapeX.GetShapeSize();

    const std::set<ge::DataType> supportedDtype = {ge::DT_FLOAT16, ge::DT_FLOAT, ge::DT_BF16};
    auto inputDesc = context->GetInputDesc(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputDesc);
    *dataType = inputDesc->GetDataType();
    OP_CHECK_IF(supportedDtype.count(*dataType) == 0,
                OP_LOGE(context, "BesselI0e: unsupported dtype=%d", static_cast<int>(*dataType)),
                return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

// 设置 workspace = 0
static ge::graphStatus GetWorkspaceSize(gert::TilingContext* context)
{
    size_t* currentWorkspace = context->GetWorkspaceSizes(WORKSPACE_NUM);
    OP_CHECK_NULL_WITH_CONTEXT(context, currentWorkspace);
    currentWorkspace[0] = WS_SYS_SIZE;
    return ge::GRAPH_SUCCESS;
}

// Tiling 分发入口
static ge::graphStatus BesselI0eTilingFunc(gert::TilingContext* context)
{
    OP_LOGI(context->GetNodeName(), "Enter BesselI0eTilingFunc");
    // 1. 获取平台运行信息
    uint64_t ubSize;
    int64_t coreNum;
    OP_CHECK_IF(GetPlatformInfo(context, &ubSize, &coreNum) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "GetPlatformInfo error"), return ge::GRAPH_FAILED);

    // 2. 获取 shape、属性信息
    int64_t totalIdx = 0;
    ge::DataType dataType = ge::DT_FLOAT;
    OP_CHECK_IF(GetShapeAttrsInfo(context, &totalIdx, &dataType) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "GetShapeAttrsInfo error"), return ge::GRAPH_FAILED);

    // 3. 设置 workspace = 0
    OP_CHECK_IF(GetWorkspaceSize(context) != ge::GRAPH_SUCCESS, OP_LOGE(context, "GetWorkspaceSize error"),
                return ge::GRAPH_FAILED);

    // 4. 设置 tiling 信息
    BesselI0eTilingData* tiling = context->GetTilingData<BesselI0eTilingData>();
    OP_CHECK_NULL_WITH_CONTEXT(context, tiling);
    OP_CHECK_IF(memset_s(tiling, sizeof(BesselI0eTilingData), 0, sizeof(BesselI0eTilingData)) != EOK,
                OP_LOGE(context, "set tiling data error"), return ge::GRAPH_FAILED);

    // 空 Tensor 检查
    if (totalIdx == 0) {
        context->SetBlockDim(1);
        ASCENDC_TPL_SEL_PARAM(context, static_cast<uint32_t>(dataType));
        return ge::GRAPH_SUCCESS;
    }

    tiling->totalNum = totalIdx;

    // 多核切分：将总元素按核数均分，按 UB 块大小对齐
    int64_t ubBlockSize = GetUbBlockSize(context);
    tiling->blockFactor = CeilAlign(CeilDiv(totalIdx, coreNum), ubBlockSize);
    int64_t usedCoreNum = CeilDiv(totalIdx, tiling->blockFactor);

    // UB 切分：按可用 UB 大小和 buffer 数量均分
    // FP32 路径需要 6 个 buffer（1 VECIN + 5 VECCALC + 1 VECOUT 简化为 6 份）
    // 公式：ubFactor = FloorAlign(FloorDiv(ubSize / TYPE_SIZE, BUFFER_NUM), ubBlockSize)
    tiling->ubFactor = FloorAlign(FloorDiv(static_cast<int64_t>(ubSize) / TYPE_SIZE_FP32, BUFFER_NUM_FP32),
                                  ubBlockSize);

    context->SetBlockDim(usedCoreNum);

    // 5. 设置 TilingKey（根据 dtype 选择模板）
    // TilingKey 0: float16, TilingKey 1: float32, TilingKey 2: bfloat16
    uint32_t dTypeX = static_cast<uint32_t>(dataType);
    ASCENDC_TPL_SEL_PARAM(context, dTypeX);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus TilingParseForBesselI0e([[maybe_unused]] gert::TilingParseContext* context)
{
    return ge::GRAPH_SUCCESS;
}

struct BesselI0eCompileInfo {}; // 必须定义，入图场景依赖

// Tiling 注册入口
IMPL_OP_OPTILING(BesselI0e).Tiling(BesselI0eTilingFunc).TilingParse<BesselI0eCompileInfo>(TilingParseForBesselI0e);

} // namespace optiling
