/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 *
 * Generated By CANNBot
 */

/*!
 * \file dawsn_tiling_arch35.cpp
 * \brief Dawsn 算子 Host 侧 Tiling 计算（arch35 / DAV_3510）
 */

#include "register/op_def_registry.h"
#include "op_common/log/log.h"
#include "op_common/op_host/util/math_util.h"
#include "op_common/op_host/util/platform_util.h"
#include "../../op_kernel/arch35/dawsn_tiling_data.h"
#include "../../op_kernel/arch35/dawsn_tiling_key.h"

namespace optiling {

using Ops::Base::CeilDiv;
using Ops::Base::CeilAlign;
using Ops::Base::FloorDiv;
using Ops::Base::FloorAlign;
using Ops::Base::GetUbBlockSize;

constexpr uint32_t WS_SYS_SIZE = 0U;
constexpr size_t WORKSPACE_NUM = 1;
constexpr int64_t MIN_TILING_BITS = 32768;       // 4KB per core minimum, in bits
constexpr int64_t ELEM_ALIGN_FACTOR = 512;       // multi-core element alignment
constexpr int64_t ALIGN_256_BYTES = 256;         // UB alignment in bytes
constexpr int64_t BITS_PER_BYTE = 8;             // bits per byte

// Buffer planning constants for GetBufferDivisor
constexpr int64_t FP32_REG_BUF_COUNT = 7;        // FP32 path: 6 RegTensor buffers + x/y buffers
constexpr int64_t FP32_MASK_BYTES = 1;           // mask buffer size per element
constexpr int64_t FP16_ELEM_BYTES = 2;           // half/bf16 element size in bytes
constexpr int64_t FP16_ORIG_BUF_COUNT = 2;       // FP16/BF16: 2 original dtype buffers
constexpr int64_t FP16_FP32_BUF_COUNT = 5;       // FP16/BF16: 5 FP32 intermediate buffers

static const gert::Shape g_vec_1_shape = {1};

static inline const gert::Shape EnsureNotScalar(const gert::Shape& in_shape) {
    if (in_shape.GetDimNum() == 0) {
        return g_vec_1_shape;
    }
    return in_shape;
}

static ge::graphStatus GetPlatformInfo(gert::TilingContext* context, uint64_t* ubSize, int64_t* coreNum)
{
    fe::PlatFormInfos* platformInfoPtr = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfoPtr);
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);
    *coreNum = ascendcPlatform.GetCoreNumAiv();
    OP_CHECK_IF(*coreNum == 0, OP_LOGE(context, "coreNum is 0"), return ge::GRAPH_FAILED);
    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, *ubSize);
    OP_CHECK_IF(*ubSize == 0, OP_LOGE(context, "ubSize is 0"), return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus GetShapeAttrsInfo(gert::TilingContext* context, int64_t* totalIdx, ge::DataType* dataType)
{
    auto inputX = context->GetInputShape(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputX);
    auto inputShapeX = EnsureNotScalar(inputX->GetStorageShape());

    *totalIdx = inputShapeX.GetShapeSize();

    const std::set<ge::DataType> supportedDtype = {ge::DT_FLOAT, ge::DT_FLOAT16, ge::DT_BF16};
    auto inputDesc = context->GetInputDesc(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputDesc);
    *dataType = inputDesc->GetDataType();
    OP_CHECK_IF(supportedDtype.count(*dataType) == 0, OP_LOGE(context, "invalid dtype"), return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus GetWorkspaceSize(gert::TilingContext* context)
{
    size_t* currentWorkspace = context->GetWorkspaceSizes(WORKSPACE_NUM);
    OP_CHECK_NULL_WITH_CONTEXT(context, currentWorkspace);
    currentWorkspace[0] = WS_SYS_SIZE;
    return ge::GRAPH_SUCCESS;
}

static int64_t GetElemBytes(ge::DataType dtype)
{
    switch (dtype) {
        case ge::DT_FLOAT16: return 2;
        case ge::DT_BF16:    return 2;
        case ge::DT_FLOAT:   return 4;
        default:             return 4;
    }
}

static int64_t GetBufferDivisor(ge::DataType dtype)
{
    // bufferDivisor accounts for all UB buffers needed per element
    if (dtype == ge::DT_FLOAT) {
        // FP32 path: FP32_REG_BUF_COUNT FP32 buffers + FP32_MASK_BYTES mask
        // Plus x_buf and y_buf
        return FP32_REG_BUF_COUNT * sizeof(float) + FP32_MASK_BYTES;
    } else if (dtype == ge::DT_FLOAT16 || dtype == ge::DT_BF16) {
        // FP16/BF16 path: FP16_ORIG_BUF_COUNT original dtype buffers + FP16_FP32_BUF_COUNT FP32 buffers
        return FP16_ORIG_BUF_COUNT * FP16_ELEM_BYTES + FP16_FP32_BUF_COUNT * sizeof(float);
    } else {
        // Fallback: use FP32-like buffer planning
        return FP32_REG_BUF_COUNT * sizeof(float) + FP32_MASK_BYTES;
    }
}

static void ComputeTilingParams(int64_t totalIdx, int64_t availableCoreNum, uint64_t ubSize,
                                ge::DataType dataType, DawsnTilingData* tiling)
{
    int64_t elemBytes = GetElemBytes(dataType);
    int64_t minDtypeBits = elemBytes * BITS_PER_BYTE;

    // Multi-core splitting
    int64_t coreNum = (totalIdx * minDtypeBits + MIN_TILING_BITS - 1) / MIN_TILING_BITS;
    coreNum = std::min(coreNum, availableCoreNum);
    int64_t blockFormer = ((totalIdx + coreNum - 1) / coreNum + ELEM_ALIGN_FACTOR - 1) /
                           ELEM_ALIGN_FACTOR * ELEM_ALIGN_FACTOR;
    int64_t blockNum = (totalIdx + blockFormer - 1) / blockFormer;

    // UB splitting
    int64_t bufferDivisor = GetBufferDivisor(dataType);
    int64_t maxElemNum = static_cast<int64_t>(ubSize) / bufferDivisor;
    int64_t alignFactor = ALIGN_256_BYTES / elemBytes;
    int64_t ubFormer = (maxElemNum / alignFactor) * alignFactor;
    if (ubFormer <= 0) {
        ubFormer = alignFactor;
    }

    // Loop counts
    int64_t ubLoopOfFormerBlock = (blockFormer + ubFormer - 1) / ubFormer;
    int64_t ubTailOfFormerBlock = blockFormer - (ubLoopOfFormerBlock - 1) * ubFormer;
    int64_t blockTail = totalIdx - (blockNum - 1) * blockFormer;
    int64_t ubLoopOfTailBlock = (blockTail + ubFormer - 1) / ubFormer;
    int64_t ubTailOfTailBlock = blockTail - (ubLoopOfTailBlock - 1) * ubFormer;

    // Fill tiling data
    tiling->dim0 = totalIdx;
    tiling->coreNum = coreNum;
    tiling->blockFormer = blockFormer;
    tiling->blockNum = blockNum;
    tiling->ubFormer = ubFormer;
    tiling->ubLoopOfFormerBlock = ubLoopOfFormerBlock;
    tiling->ubTailOfFormerBlock = ubTailOfFormerBlock;
    tiling->ubLoopOfTailBlock = ubLoopOfTailBlock;
    tiling->ubTailOfTailBlock = ubTailOfTailBlock;
}

static ge::graphStatus DawsnTilingFunc(gert::TilingContext* context)
{
    OP_LOGI(context->GetNodeName(), "Enter DawsnTilingFunc");
    // 1. Get platform info
    uint64_t ubSize;
    int64_t availableCoreNum;
    OP_CHECK_IF(
        GetPlatformInfo(context, &ubSize, &availableCoreNum) != ge::GRAPH_SUCCESS,
        OP_LOGE(context, "GetPlatformInfo error"),
        return ge::GRAPH_FAILED);

    // 2. Get shape and dtype info
    int64_t totalIdx;
    ge::DataType dataType = ge::DT_FLOAT;
    OP_CHECK_IF(
        GetShapeAttrsInfo(context, &totalIdx, &dataType) != ge::GRAPH_SUCCESS,
        OP_LOGE(context, "GetShapeAttrsInfo error"), return ge::GRAPH_FAILED);

    // 3. Set workspace
    OP_CHECK_IF(
        GetWorkspaceSize(context) != ge::GRAPH_SUCCESS,
        OP_LOGE(context, "GetWorkspaceSize error"),
        return ge::GRAPH_FAILED);

    // 4. Get tiling data pointer
    DawsnTilingData* tiling = context->GetTilingData<DawsnTilingData>();
    OP_CHECK_NULL_WITH_CONTEXT(context, tiling);
    OP_CHECK_IF(
        memset_s(tiling, sizeof(DawsnTilingData), 0, sizeof(DawsnTilingData)) != EOK,
        OP_LOGE(context, "set tiling data error"), return ge::GRAPH_FAILED);

    // Empty tensor check
    if (totalIdx == 0) {
        context->SetBlockDim(1);
        ASCENDC_TPL_SEL_PARAM(context, static_cast<uint32_t>(dataType));
        return ge::GRAPH_SUCCESS;
    }

    // 5-8. Compute tiling parameters
    ComputeTilingParams(totalIdx, availableCoreNum, ubSize, dataType, tiling);

    context->SetBlockDim(tiling->blockNum);

    // 9. Set TilingKey (template parameter selection)
    uint32_t dTypeX = static_cast<uint32_t>(dataType);
    ASCENDC_TPL_SEL_PARAM(context, dTypeX);

    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus TilingParseForDawsn([[maybe_unused]] gert::TilingParseContext* context)
{
    return ge::GRAPH_SUCCESS;
}

struct DawsnCompileInfo {};

IMPL_OP_OPTILING(Dawsn).Tiling(DawsnTilingFunc).TilingParse<DawsnCompileInfo>(TilingParseForDawsn);

} // namespace optiling
