/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/**
 *
 * NOTE: Portions of this code were AI-generated and have been
 * technically reviewed for functional accuracy and security
 */

/*!
 * \file mul_no_nan.cpp
 * \brief MulNoNan Kernel entry (atvoss Broadcast mode)
 */

#include "kernel_operator.h"
#include "mul_no_nan_dag.h"
#include "mul_no_nan_struct.h"
#include "atvoss/broadcast/broadcast_sch.h"

using namespace Ops::Base;

template <uint64_t schMode>
__global__ __aicore__ void mul_no_nan(GM_ADDR x, GM_ADDR y, GM_ADDR z,
                                       GM_ADDR workspace, GM_ADDR tiling)
{
    KERNEL_TASK_TYPE_DEFAULT(KERNEL_TYPE_AIV_ONLY);

    // DTYPE_X is auto-generated by the build system based on input "x" dtype in mul_no_nan_def.cpp
    using OpDag = NsMulNoNan::MulNoNanCompute<DTYPE_X>::OpDag;
    BroadcastSch<schMode, OpDag> sch(tiling);
    sch.Process(x, y, z);
}
