/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file prod_virial_se_a_tiling_key.h
 * \brief Tiling key declare for prod_virial_se_a operator
 *
 * 单一场景模式（schMode=0），不枚举 dtype。
 * dtype 由 DTYPE_ 宏根据 def.cpp 的 DataType 组合自动实例化。
 */

#ifndef PROD_VIRIAL_SE_A_TILING_KEY_H_
#define PROD_VIRIAL_SE_A_TILING_KEY_H_

#include "ascendc/host_api/tiling/template_argument.h"

#define PROD_VIRIAL_SE_A_TPL_SCH_MODE_DEFAULT 0

ASCENDC_TPL_ARGS_DECL(ProdVirialSeA,
                      ASCENDC_TPL_UINT_DECL(schMode, 1, ASCENDC_TPL_UI_LIST, PROD_VIRIAL_SE_A_TPL_SCH_MODE_DEFAULT));

ASCENDC_TPL_SEL(ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST,
                                                          PROD_VIRIAL_SE_A_TPL_SCH_MODE_DEFAULT)));

#endif // PROD_VIRIAL_SE_A_TILING_KEY_H_
