/**
 * Copyright (c) 2025-2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */
/* Generated By CANNBot */

/*!
 * \file real_apt.cpp
 * \brief Real operator kernel entry (ascend950 / arch35)
 *
 * Template parameters (matching real_tiling_key.h ASCENDC_TPL_ARGS_DECL):
 *   - D_T: Output data type, from ASCENDC_TPL_DATATYPE_DECL
 *   - IS_COMPLEX: 0=real passthrough, 1=complex extract real, from ASCENDC_TPL_UINT_DECL
 */

#include "arch35/real.h"

template <typename D_T, int IS_COMPLEX>
__global__ __aicore__ void real(GM_ADDR self, GM_ADDR out, GM_ADDR workspace, GM_ADDR tiling)
{
    REGISTER_TILING_DEFAULT(RealTilingData);
    GET_TILING_DATA_WITH_STRUCT(RealTilingData, tilingData, tiling);
    NsReal::RealOp<D_T, IS_COMPLEX> op;
    op.Init(self, out, workspace, &tilingData);
    op.Process();
}
