/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 *
 * Generated By CANNBot
 */

/*!
 * \file inv_grad.h
 * \brief InvGrad kernel class definition (arch35)
 *
 * Formula: y = -grad * x * x
 *
 * Precision strategy:
 *   - float32: native fp32 — Mul(xx, x, x) -> Mul(y, grad, xx) -> Muls(y, y, -1.0f)
 *   - int32  : native int32 — Mul(xx, x, x) -> Mul(y, grad, xx) -> Muls(y, y, -1)
 *              (int32 范围足够大，常见场景不溢出；与 TBE int32 路径等价)
 *   - float16/bfloat16: 上行 fp32 计算后 Cast 回原 dtype（CAST_ROUND 银行家舍入）
 *
 * 注：int8 支持本来按 TBE 语义实现，但 arch35 上 AscendC 用户层 Cast API
 * 不支持"to int8"方向的直接转换（cast 算子 policy 表显示该方向走 MIRCRO_CAST
 * 微指令拼装，需 CastMicro 类的寄存器级编程），故 int8 由 AICPU 路径承接。
 *
 * Buffer layout (single buffer, depth=1):
 *   xQueue:    ubFactor * sizeof(T)     (input x)
 *   gradQueue: ubFactor * sizeof(T)     (input grad)
 *   outQueue:  ubFactor * sizeof(T)     (output y)
 *   tmpBuf1:   ubFactor * sizeof(float) (intermediate: fp32 xFloat / int32 xx)
 *   tmpBuf2:   ubFactor * sizeof(float) (intermediate: fp32 gradFloat; int32 路径未用)
 *
 * tmpBuf 均按 sizeof(float)=4 分配，可同时承载 fp32 与 int32 视图（sizeof 一致）。
 */

#ifndef OPS_MATH_INV_GRAD_OP_KERNEL_ARCH35_INV_GRAD_H
#define OPS_MATH_INV_GRAD_OP_KERNEL_ARCH35_INV_GRAD_H

#include "kernel_operator.h"
#include "kernel_tiling/kernel_tiling.h"
#include "inv_grad_tiling_data.h"
#include "inv_grad_tiling_key.h"

namespace NsInvGrad {

using AscendC::TPipe;
using AscendC::TQue;
using AscendC::TBuf;
using AscendC::QuePosition;
using AscendC::GlobalTensor;
using AscendC::LocalTensor;
using AscendC::DataCopyParams;
using AscendC::DataCopyPad;
using AscendC::RoundMode;
using AscendC::GetBlockIdx;
using AscendC::Cast;
using AscendC::Mul;
using AscendC::Muls;

template <typename T>
class InvGrad {
public:
    __aicore__ inline InvGrad() {}

    __aicore__ inline void Init(GM_ADDR x, GM_ADDR grad, GM_ADDR y,
                                const InvGradTilingData* tilingData);
    __aicore__ inline void Process();

private:
    __aicore__ inline void CopyIn(int64_t gmOffset, int64_t currentNum);
    __aicore__ inline void Compute(int64_t currentNum);
    __aicore__ inline void CopyOut(int64_t gmOffset, int64_t currentNum);

    // float32 native path: Mul(xx, x, x) -> Mul(y, grad, xx) -> Muls(-1.0f)
    __aicore__ inline void ComputeFloat32(LocalTensor<float>& xLocal,
                                          LocalTensor<float>& gradLocal,
                                          LocalTensor<float>& yLocal,
                                          int64_t count);
    // int32 native path: Mul(xx, x, x) -> Mul(y, grad, xx) -> Muls(-1)
    __aicore__ inline void ComputeInt32(LocalTensor<int32_t>& xLocal,
                                        LocalTensor<int32_t>& gradLocal,
                                        LocalTensor<int32_t>& yLocal,
                                        int64_t count);
    // half/bfloat16/int8 path: Cast(T -> fp32) -> compute -> Cast(fp32 -> T)
    template <typename SrcT>
    __aicore__ inline void ComputeWithCast(LocalTensor<SrcT>& xLocal,
                                           LocalTensor<SrcT>& gradLocal,
                                           LocalTensor<SrcT>& yLocal,
                                           int64_t count);

private:
    TPipe pipe;
    TQue<QuePosition::VECIN, 1>  xQueue_;     // input x
    TQue<QuePosition::VECIN, 1>  gradQueue_;  // input grad
    TQue<QuePosition::VECOUT, 1> outQueue_;   // output y
    TBuf<QuePosition::VECCALC>   tmpBuf1_;    // fp32 scratch 1 (xx / xFloat)
    TBuf<QuePosition::VECCALC>   tmpBuf2_;    // fp32 scratch 2 (gradFloat)

    GlobalTensor<T> xGM_;
    GlobalTensor<T> gradGM_;
    GlobalTensor<T> yGM_;

    int64_t blockOffset_ = 0;
    int64_t blockLen_    = 0;
    int64_t ubFactor_    = 0;
};

// =============================================================================
// Init
// =============================================================================
template <typename T>
__aicore__ inline void InvGrad<T>::Init(GM_ADDR x, GM_ADDR grad, GM_ADDR y,
                                        const InvGradTilingData* tilingData)
{
    ubFactor_ = tilingData->ubFactor;

    if (tilingData->totalElements == 0 || tilingData->blockFactor == 0) {
        blockOffset_ = 0;
        blockLen_    = 0;
        return;
    }

    blockOffset_ = tilingData->blockFactor * static_cast<int64_t>(GetBlockIdx());
    int64_t remaining = tilingData->totalElements - blockOffset_;
    if (remaining <= 0) {
        blockLen_ = 0;
        return;
    }
    blockLen_ = (remaining > tilingData->blockFactor) ? tilingData->blockFactor : remaining;

    xGM_.SetGlobalBuffer   ((__gm__ T*)x    + blockOffset_, blockLen_);
    gradGM_.SetGlobalBuffer((__gm__ T*)grad + blockOffset_, blockLen_);
    yGM_.SetGlobalBuffer   ((__gm__ T*)y    + blockOffset_, blockLen_);

    pipe.InitBuffer(xQueue_,    1, ubFactor_ * sizeof(T));
    pipe.InitBuffer(gradQueue_, 1, ubFactor_ * sizeof(T));
    pipe.InitBuffer(outQueue_,  1, ubFactor_ * sizeof(T));
    pipe.InitBuffer(tmpBuf1_,      ubFactor_ * sizeof(float));
    pipe.InitBuffer(tmpBuf2_,      ubFactor_ * sizeof(float));
}

// =============================================================================
// CopyIn: GM -> UB for both x and grad
// =============================================================================
template <typename T>
__aicore__ inline void InvGrad<T>::CopyIn(int64_t gmOffset, int64_t currentNum)
{
    LocalTensor<T> xLocal    = xQueue_.template AllocTensor<T>();
    LocalTensor<T> gradLocal = gradQueue_.template AllocTensor<T>();
    DataCopyParams copyParams;
    copyParams.blockCount = 1;
    copyParams.blockLen   = static_cast<uint16_t>(currentNum * sizeof(T));
    copyParams.srcStride  = 0;
    copyParams.dstStride  = 0;
    DataCopyPad(xLocal,    xGM_[gmOffset],    copyParams, {false, 0, 0, 0});
    DataCopyPad(gradLocal, gradGM_[gmOffset], copyParams, {false, 0, 0, 0});
    xQueue_.EnQue(xLocal);
    gradQueue_.EnQue(gradLocal);
}

// =============================================================================
// CopyOut: UB -> GM for y
// =============================================================================
template <typename T>
__aicore__ inline void InvGrad<T>::CopyOut(int64_t gmOffset, int64_t currentNum)
{
    LocalTensor<T> yLocal = outQueue_.template DeQue<T>();
    DataCopyParams copyParams;
    copyParams.blockCount = 1;
    copyParams.blockLen   = static_cast<uint16_t>(currentNum * sizeof(T));
    copyParams.srcStride  = 0;
    copyParams.dstStride  = 0;
    DataCopyPad(yGM_[gmOffset], yLocal, copyParams);
    outQueue_.FreeTensor(yLocal);
}

// =============================================================================
// ComputeFloat32: Mul(xx, x, x) -> Mul(y, grad, xx) -> Muls(y, y, -1)
// =============================================================================
template <typename T>
__aicore__ inline void InvGrad<T>::ComputeFloat32(LocalTensor<float>& xLocal,
                                                  LocalTensor<float>& gradLocal,
                                                  LocalTensor<float>& yLocal,
                                                  int64_t count)
{
    LocalTensor<float> xx = tmpBuf1_.template Get<float>();
    Mul (xx,     xLocal,    xLocal, static_cast<int32_t>(count));   // xx = x * x
    Mul (yLocal, gradLocal, xx,     static_cast<int32_t>(count));   // y = grad * xx
    Muls(yLocal, yLocal, static_cast<float>(-1.0f),
         static_cast<int32_t>(count));                              // y = -y
}

// =============================================================================
// ComputeInt32: native int32 path — Mul(xx, x, x) -> Mul(y, grad, xx) -> Muls(-1)
// =============================================================================
template <typename T>
__aicore__ inline void InvGrad<T>::ComputeInt32(LocalTensor<int32_t>& xLocal,
                                                LocalTensor<int32_t>& gradLocal,
                                                LocalTensor<int32_t>& yLocal,
                                                int64_t count)
{
    // 复用 tmpBuf1（fp32 分配 = sizeof(int32_t) = 4 字节，按 int32 视图使用）
    LocalTensor<int32_t> xx = tmpBuf1_.template Get<int32_t>();
    Mul (xx,     xLocal,    xLocal, static_cast<int32_t>(count));   // xx = x * x
    Mul (yLocal, gradLocal, xx,     static_cast<int32_t>(count));   // y = grad * xx
    Muls(yLocal, yLocal, static_cast<int32_t>(-1),
         static_cast<int32_t>(count));                              // y = -y
}

// =============================================================================
// ComputeWithCast: Cast(T -> fp32) -> compute in fp32 -> Cast(fp32 -> T)
//   适用于 half / bfloat16
// =============================================================================
template <typename T>
template <typename SrcT>
__aicore__ inline void InvGrad<T>::ComputeWithCast(LocalTensor<SrcT>& xLocal,
                                                   LocalTensor<SrcT>& gradLocal,
                                                   LocalTensor<SrcT>& yLocal,
                                                   int64_t count)
{
    LocalTensor<float> xFloat    = tmpBuf1_.template Get<float>();
    LocalTensor<float> gradFloat = tmpBuf2_.template Get<float>();

    // Up-cast: half/bf16 → float32 (CAST_NONE 无损上行)
    Cast(xFloat,    xLocal,    RoundMode::CAST_NONE, static_cast<uint32_t>(count));
    Cast(gradFloat, gradLocal, RoundMode::CAST_NONE, static_cast<uint32_t>(count));

    // fp32 compute:
    //   xFloat = x * x
    //   xFloat = grad * xFloat
    //   xFloat = -xFloat
    Mul (xFloat, xFloat,    xFloat, static_cast<int32_t>(count));
    Mul (xFloat, gradFloat, xFloat, static_cast<int32_t>(count));
    Muls(xFloat, xFloat, static_cast<float>(-1.0f),
         static_cast<int32_t>(count));

    // Down-cast: fp32 → half/bf16 (CAST_ROUND 银行家舍入)
    Cast(yLocal, xFloat, RoundMode::CAST_ROUND, static_cast<uint32_t>(count));
}

// =============================================================================
// Compute: dispatch to float32 direct path or cast path via if constexpr
// =============================================================================
template <typename T>
__aicore__ inline void InvGrad<T>::Compute(int64_t currentNum)
{
    LocalTensor<T> xLocal    = xQueue_.template DeQue<T>();
    LocalTensor<T> gradLocal = gradQueue_.template DeQue<T>();
    LocalTensor<T> yLocal    = outQueue_.template AllocTensor<T>();

    // Vector API 的 count 参数本身不要求 block 对齐——硬件 mask 处理边界。
    // 直接以 currentNum 作为 count，不再上对齐到 alignBlock：
    //   - 避免对 UB 中 [currentNum, alignedNum) 未初始化区域做读运算（cpp-secure 3.1）
    //   - 避免 Duplicate(xLocal[currentNum], ...) 在 currentNum 非 32 字节对齐时触发 VEC_ERROR
    if constexpr (std::is_same_v<T, float>) {
        ComputeFloat32(xLocal, gradLocal, yLocal, currentNum);
    } else if constexpr (std::is_same_v<T, int32_t>) {
        ComputeInt32(xLocal, gradLocal, yLocal, currentNum);
    } else {
        // half / bfloat16
        ComputeWithCast(xLocal, gradLocal, yLocal, currentNum);
    }

    outQueue_.template EnQue<T>(yLocal);
    xQueue_.FreeTensor(xLocal);
    gradQueue_.FreeTensor(gradLocal);
}

// =============================================================================
// Process: main loop over UB chunks
// =============================================================================
template <typename T>
__aicore__ inline void InvGrad<T>::Process()
{
    if (blockLen_ <= 0) {
        return;
    }
    int64_t loopCount = (blockLen_ + ubFactor_ - 1) / ubFactor_;
    for (int64_t i = 0; i < loopCount; ++i) {
        int64_t gmOffset   = i * ubFactor_;
        int64_t currentNum = (i == (loopCount - 1)) ? (blockLen_ - gmOffset) : ubFactor_;
        CopyIn(gmOffset, currentNum);
        Compute(currentNum);
        CopyOut(gmOffset, currentNum);
    }
}

} // namespace NsInvGrad
#endif // OPS_MATH_INV_GRAD_OP_KERNEL_ARCH35_INV_GRAD_H
