/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 *
 * Generated By CANNBot
 */

#include "kernel_operator.h"
#include "log_space_d_empty.h"
#include "log_space_d_kernel.h"
#include "log_space_d_struct.h"
#include "log_space_d_tiling_struct.h"

template <bool IS_EMPTY>
__global__ __aicore__ void log_space_d(GM_ADDR assist, GM_ADDR y, GM_ADDR workspace, GM_ADDR tiling)
{
    REGISTER_TILING_DEFAULT(LogSpaceDTilingData);
    GET_TILING_DATA_PTR_WITH_STRUCT(LogSpaceDTilingData, tilingData, tiling);
    KERNEL_TASK_TYPE_DEFAULT(KERNEL_TYPE_AIV_ONLY);
    (void)workspace;

    if constexpr (IS_EMPTY) {
        LogSpaceDEmpty<DTYPE_ASSIST, DTYPE_ASSIST> kernel;
        kernel.Init(tilingData);
        kernel.Process();
    } else {
        LogSpaceDKernel<DTYPE_ASSIST, DTYPE_ASSIST> kernel;
        kernel.Init(assist, y, tilingData);
        kernel.Process();
    }
}
