/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file prod_force_se_a_tiling_data.h
 * \brief Tiling data struct for prod_force_se_a operator
 */

/* Generated By CANNBot */

#ifndef PROD_FORCE_SE_A_TILING_DATA_H_
#define PROD_FORCE_SE_A_TILING_DATA_H_

struct ProdForceSeATilingData {
    int32_t nframes = 0;     // 帧数，从 net_deriv.shape[0] 获取
    int32_t nloc = 0;        // 本地原子数，从 net_deriv.shape[1] / (nnei * 4) 推导
    int32_t nnei = 0;        // 邻居数 = n_a_sel + n_r_sel（从属性获取）
    int32_t ndescrpt = 0;    // 描述符数 = 4 * nnei
    int32_t needCoreNum = 0; // 需要启动的核数
    // ⚠️ 不包含 threadNum 等线程数参数（编译期常量）
    // ⚠️ 不包含 nall（kernel 侧从 natoms GM 读取）
};

#endif // PROD_FORCE_SE_A_TILING_DATA_H_
