/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file add_mat_mat_elements_plus.cpp
 * \brief AddMatMatElementsPlus Kernel 入口（arch35 架构，Ascend950）
 *
 * 模板参数（与 arch35/add_mat_mat_elements_plus_tiling_key_arch35.h 中 ASCENDC_TPL_ARGS_DECL 对应）：
 *   D_T: 数据类型（half / float / bfloat16_t）
 *
 * TilingKey 映射：
 *   TilingKey_0: D_T = half        (fp16 Cast 绕行路径)
 *   TilingKey_1: D_T = float       (fp32 直接路径)
 *   TilingKey_2: D_T = bfloat16_t  (bf16 Cast 绕行路径)
 *
 * 输入顺序与 op_def / proto.h 一致：c, a, b, beta, alpha
 *   beta, alpha 为标量 tensor（1-element），值由 kernel Init 从 GM 读取。
 */

#include "arch35/add_mat_mat_elements_plus_arch35.h"

#ifdef __CCE_KT_TEST__
extern "C" __global__ __aicore__ void add_mat_mat_elements_plus(GM_ADDR c, GM_ADDR a, GM_ADDR b, GM_ADDR beta,
                                                                GM_ADDR alpha, GM_ADDR cOut, GM_ADDR workspace,
                                                                GM_ADDR tiling)
{
    GET_TILING_DATA_WITH_STRUCT(AddMatMatElementsPlusTilingData, tilingData, tiling);
    NsAddMatMatElementsPlus::KernelAddMatMatElementsPlus<DTYPE_C> op;
    op.Init(c, a, b, beta, alpha, cOut, tilingData);
    op.Process();
}
#else
template <typename D_T>
__global__ __aicore__ void add_mat_mat_elements_plus(GM_ADDR c, GM_ADDR a, GM_ADDR b, GM_ADDR beta, GM_ADDR alpha,
                                                     GM_ADDR cOut, GM_ADDR workspace, GM_ADDR tiling)
{
    REGISTER_TILING_DEFAULT(AddMatMatElementsPlusTilingData);
    GET_TILING_DATA_WITH_STRUCT(AddMatMatElementsPlusTilingData, tilingData, tiling);

    NsAddMatMatElementsPlus::KernelAddMatMatElementsPlus<D_T> op;
    op.Init(c, a, b, beta, alpha, cOut, tilingData);
    op.Process();
}
#endif
