/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/**
 * NOTE: Portions of this code were AI-generated and have been
 * technically reviewed for functional accuracy and security
 * Generated By CANNBot
 */

/*!
 * \file asin_grad_apt.cpp
 * \brief AsinGrad Kernel entry (arch35)
 *
 * 输入顺序与 op_def / proto.h 一致：y (forward input), dy (grad output)，
 * 输出：z (grad input)
 *
 * Template parameters (matching asin_grad_tiling_key.h ASCENDC_TPL_ARGS_DECL):
 *   - D_T: Data type, defined by ASCENDC_TPL_DATATYPE_DECL
 *   - BUFFER_MODE: Buffer mode (0=single, 1=double), defined by ASCENDC_TPL_UINT_DECL
 */

#include "arch35/asin_grad.h"

#ifdef __CCE_KT_TEST__
extern "C" __global__ __aicore__ void asin_grad(
    GM_ADDR y, GM_ADDR dy, GM_ADDR z, GM_ADDR workspace, GM_ADDR tiling)
{
    GET_TILING_DATA_WITH_STRUCT(AsinGradTilingData, tilingData, tiling);
    NsAsinGrad::AsinGrad<DTYPE_Y, float, 0> op;
    op.Init(y, dy, z, &tilingData);
    op.Process();
}
#else
template <typename D_T, int BUFFER_MODE>
__global__ __aicore__ void asin_grad(GM_ADDR y, GM_ADDR dy, GM_ADDR z, GM_ADDR workspace, GM_ADDR tiling)
{
    REGISTER_TILING_DEFAULT(AsinGradTilingData);
    GET_TILING_DATA_WITH_STRUCT(AsinGradTilingData, tilingData, tiling);

    NsAsinGrad::AsinGrad<D_T, float, BUFFER_MODE> op;
    op.Init(y, dy, z, &tilingData);
    op.Process();
}
#endif
