/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 *
 * Generated By CANNBot
 */

/*!
 * \file spence_tiling.cpp
 * \brief Spence 算子 Host 侧 Tiling 计算（arch35）
 */

#include "register/op_def_registry.h"
#include "op_common/log/log.h"
#include "op_common/op_host/util/math_util.h"
#include "op_common/op_host/util/platform_util.h"
#include "../../op_kernel/arch35/spence_tiling_data.h"
#include "../../op_kernel/arch35/spence_tiling_key.h"

namespace optiling {

using Ops::Base::CeilDiv;
using Ops::Base::CeilAlign;
using Ops::Base::FloorDiv;
using Ops::Base::FloorAlign;
using Ops::Base::GetUbBlockSize;

constexpr uint32_t WS_SYS_SIZE = 0U;
constexpr size_t WORKSPACE_NUM = 1;
constexpr int64_t ELEM_ALIGN = 512;
constexpr int64_t FP32_ELEM_BYTES = 4;
constexpr int64_t FP16_ELEM_BYTES = 2;
constexpr int64_t BITS_PER_BYTE = 8;
constexpr int64_t MIN_TILING_BITS = 32768;
constexpr int64_t UB_ALIGN_BYTES = 256;

static const gert::Shape g_vec_1_shape = {1};

static inline const gert::Shape EnsureNotScalar(const gert::Shape& in_shape) {
    if (in_shape.GetDimNum() == 0) {
        return g_vec_1_shape;
    }
    return in_shape;
}

static ge::graphStatus GetPlatformInfo(gert::TilingContext* context, uint64_t* ubSize, int64_t* coreNum)
{
    fe::PlatFormInfos* platformInfoPtr = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfoPtr);
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);
    *coreNum = ascendcPlatform.GetCoreNumAiv();
    OP_CHECK_IF(*coreNum == 0, OP_LOGE(context, "coreNum is 0"), return ge::GRAPH_FAILED);
    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, *ubSize);
    OP_CHECK_IF(*ubSize == 0, OP_LOGE(context, "ubSize is 0"), return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus GetShapeAttrsInfo(gert::TilingContext* context, int64_t* dim0, ge::DataType* dataType)
{
    auto inputX = context->GetInputShape(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputX);
    auto inputShapeX = EnsureNotScalar(inputX->GetStorageShape());

    *dim0 = inputShapeX.GetShapeSize();

    const std::set<ge::DataType> supportedDtype = {ge::DT_FLOAT, ge::DT_FLOAT16, ge::DT_BF16};
    auto inputDesc = context->GetInputDesc(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputDesc);
    *dataType = inputDesc->GetDataType();
    OP_CHECK_IF(supportedDtype.count(*dataType) == 0, OP_LOGE(context, "invalid dtype"), return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus GetWorkspaceSize(gert::TilingContext* context)
{
    size_t* currentWorkspace = context->GetWorkspaceSizes(WORKSPACE_NUM);
    OP_CHECK_NULL_WITH_CONTEXT(context, currentWorkspace);
    currentWorkspace[0] = WS_SYS_SIZE;
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus InitTilingDataAndEmptyCheck(gert::TilingContext* context, SpenceTilingData* tiling,
    int64_t dim0, ge::DataType dataType, bool& isEmpty);
static void ComputeCoreTiling(gert::TilingContext* context, int64_t dim0, int64_t elemBytes,
    int64_t coreNum, SpenceTilingData* tiling,
    int64_t& blockFormer, int64_t& blockNum, int64_t& usedCoreNum);
static void ComputeUbTiling(uint64_t ubSize, ge::DataType dataType, int64_t elemBits,
    SpenceTilingData* tiling);
static void ComputeBlockDetails(int64_t dim0, int64_t blockFormer, int64_t blockNum,
    SpenceTilingData* tiling);

static ge::graphStatus SpenceTilingFunc(gert::TilingContext* context)
{
    OP_LOGI(context->GetNodeName(), "Enter SpenceTilingFunc");
    // 1. Get platform info
    uint64_t ubSize;
    int64_t coreNum;
    OP_CHECK_IF(
        GetPlatformInfo(context, &ubSize, &coreNum) != ge::GRAPH_SUCCESS,
        OP_LOGE(context, "GetPlatformInfo error"),
        return ge::GRAPH_FAILED);

    // 2. Get shape/dtype info
    int64_t dim0;
    ge::DataType dataType = ge::DT_FLOAT;
    OP_CHECK_IF(
        GetShapeAttrsInfo(context, &dim0, &dataType) != ge::GRAPH_SUCCESS,
        OP_LOGE(context, "GetShapeAttrsInfo error"), return ge::GRAPH_FAILED);

    // 3. Workspace
    OP_CHECK_IF(
        GetWorkspaceSize(context) != ge::GRAPH_SUCCESS,
        OP_LOGE(context, "GetWorkspaceSize error"),
        return ge::GRAPH_FAILED);

    SpenceTilingData* tiling = context->GetTilingData<SpenceTilingData>();
    OP_CHECK_NULL_WITH_CONTEXT(context, tiling);
    bool isEmpty = false;
    OP_CHECK_IF(
        InitTilingDataAndEmptyCheck(context, tiling, dim0, dataType, isEmpty) != ge::GRAPH_SUCCESS,
        OP_LOGE(context, "init tiling data error"), return ge::GRAPH_FAILED);
    if (isEmpty) { return ge::GRAPH_SUCCESS; }

    int64_t elemBytes = FP32_ELEM_BYTES;
    if (dataType == ge::DT_FLOAT16 || dataType == ge::DT_BF16) {
        elemBytes = FP16_ELEM_BYTES;
    }

    int64_t blockFormer, blockNum, usedCoreNum;
    ComputeCoreTiling(context, dim0, elemBytes, coreNum, tiling,
                      blockFormer, blockNum, usedCoreNum);

    int64_t elemBits = elemBytes * BITS_PER_BYTE;
    ComputeUbTiling(ubSize, dataType, elemBits, tiling);
    ComputeBlockDetails(dim0, blockFormer, blockNum, tiling);

    context->SetBlockDim(usedCoreNum);
    uint32_t dTypeX = static_cast<uint32_t>(dataType);
    ASCENDC_TPL_SEL_PARAM(context, dTypeX);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus InitTilingDataAndEmptyCheck(gert::TilingContext* context, SpenceTilingData* tiling,
    int64_t dim0, ge::DataType dataType, bool& isEmpty)
{
    OP_CHECK_IF(
        memset_s(tiling, sizeof(SpenceTilingData), 0, sizeof(SpenceTilingData)) != EOK,
        OP_LOGE(context, "set tiling data error"), return ge::GRAPH_FAILED);
    tiling->dim0 = dim0;
    tiling->dtype = static_cast<int32_t>(dataType);
    if (dim0 == 0) {
        context->SetBlockDim(1);
        ASCENDC_TPL_SEL_PARAM(context, static_cast<uint32_t>(dataType));
        isEmpty = true;
    }
    return ge::GRAPH_SUCCESS;
}

static void ComputeCoreTiling(gert::TilingContext* context, int64_t dim0, int64_t elemBytes,
    int64_t coreNum, SpenceTilingData* tiling,
    int64_t& blockFormer, int64_t& blockNum, int64_t& usedCoreNum)
{
    int64_t elemBits = elemBytes * BITS_PER_BYTE;
    int64_t calcCoreNum = (dim0 * elemBits + MIN_TILING_BITS - 1) / MIN_TILING_BITS;
    if (calcCoreNum > coreNum) {
        calcCoreNum = coreNum;
    }
    if (calcCoreNum < 1) {
        calcCoreNum = 1;
    }
    int64_t ubBlockSize = GetUbBlockSize(context);
    blockFormer = CeilAlign(CeilDiv(dim0, calcCoreNum), ubBlockSize);
    blockNum = CeilDiv(dim0, blockFormer);
    usedCoreNum = blockNum;
    tiling->coreNum = static_cast<int32_t>(usedCoreNum);
    tiling->blockFormer = blockFormer;
    tiling->blockNum = blockNum;
}

static void ComputeUbTiling(uint64_t ubSize, ge::DataType dataType, int64_t elemBits,
    SpenceTilingData* tiling)
{
    int64_t bufferDivisor = (dataType == ge::DT_FLOAT)
        ? (2 * FP32_ELEM_BYTES)
        : (2 * FP16_ELEM_BYTES + 2 * FP32_ELEM_BYTES);
    int64_t maxElemNum = (static_cast<int64_t>(ubSize) * BITS_PER_BYTE) / bufferDivisor;
    int64_t alignFactor = UB_ALIGN_BYTES * BITS_PER_BYTE / elemBits;
    int64_t ubFormer = FloorAlign(maxElemNum, alignFactor);
    if (ubFormer < 1) { ubFormer = 1; }
    tiling->ubFormer = ubFormer;
}

static void ComputeBlockDetails(int64_t dim0, int64_t blockFormer, int64_t blockNum,
    SpenceTilingData* tiling)
{
    int64_t ubFormer = tiling->ubFormer;
    int64_t formerBlockElems = blockFormer;
    tiling->ubLoopOfFormerBlock = CeilDiv(formerBlockElems, ubFormer);
    tiling->ubTailOfFormerBlock = formerBlockElems - ubFormer * (tiling->ubLoopOfFormerBlock - 1);
    if (tiling->ubTailOfFormerBlock == 0) {
        tiling->ubTailOfFormerBlock = ubFormer;
    }
    int64_t tailBlockElems = dim0 - blockFormer * (blockNum - 1);
    if (tailBlockElems <= 0) { tailBlockElems = blockFormer; }
    tiling->ubLoopOfTailBlock = CeilDiv(tailBlockElems, ubFormer);
    tiling->ubTailOfTailBlock = tailBlockElems - ubFormer * (tiling->ubLoopOfTailBlock - 1);
    if (tiling->ubTailOfTailBlock == 0) {
        tiling->ubTailOfTailBlock = ubFormer;
    }
}

static ge::graphStatus TilingParseForSpence([[maybe_unused]] gert::TilingParseContext* context)
{
    return ge::GRAPH_SUCCESS;
}

struct SpenceCompileInfo {};

IMPL_OP_OPTILING(Spence).Tiling(SpenceTilingFunc).TilingParse<SpenceCompileInfo>(TilingParseForSpence);

} // namespace optiling
