/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file sinkhorn_infershape.cpp
 * \brief Sinkhorn InferShape registration.
 */

#include "exe_graph/runtime/infer_shape_context.h"
#include "register/op_impl_registry.h"

namespace ops {
using namespace ge;

namespace {
constexpr size_t kCostIndex = 0;
constexpr size_t kOutputPIndex = 0;

ge::graphStatus InferShapeForSinkhorn(gert::InferShapeContext* context)
{
    if (context == nullptr) {
        return ge::GRAPH_FAILED;
    }
    const gert::Shape* costShape = context->GetInputShape(kCostIndex);
    gert::Shape* pShape = context->GetOutputShape(kOutputPIndex);
    if (costShape == nullptr || pShape == nullptr) {
        return ge::GRAPH_FAILED;
    }

    *pShape = *costShape;
    return ge::GRAPH_SUCCESS;
}
} // namespace

IMPL_OP_INFERSHAPE(Sinkhorn).InferShape(InferShapeForSinkhorn);

} // namespace ops
