/**
 * Copyright (c) 2025-2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#include <array>
#include <cstdint>
#include <cstring>
#include <gtest/gtest.h>
#include "tikicpulib.h"

#include "../../../op_kernel/arch35/sign_bits_unpack.h"
#include "../../../op_kernel/arch35/sign_bits_unpack_tiling_data.h"

extern "C" __global__ __aicore__ void sign_bits_unpack(GM_ADDR input, GM_ADDR output, GM_ADDR workspace,
                                                       GM_ADDR tiling);

namespace {
constexpr uint64_t UB_FACTOR = 128;

size_t Align32(size_t size) { return (size + 31U) / 32U * 32U; }

struct KernelBuffers {
    explicit KernelBuffers(size_t inputCount, size_t outputTypeSize)
        : input(reinterpret_cast<uint8_t*>(AscendC::GmAlloc(Align32(inputCount * sizeof(uint8_t))))),
          output(reinterpret_cast<uint8_t*>(AscendC::GmAlloc(Align32(inputCount * 8 * outputTypeSize)))),
          workspace(reinterpret_cast<uint8_t*>(AscendC::GmAlloc(1024))),
          tiling(reinterpret_cast<uint8_t*>(AscendC::GmAlloc(Align32(sizeof(SignBitsUnpackTilingData)))))
    {
        std::memset(input, 0, Align32(inputCount * sizeof(uint8_t)));
        std::memset(output, 0, Align32(inputCount * 8 * outputTypeSize));
        std::memset(workspace, 0, 1024);
        std::memset(tiling, 0, Align32(sizeof(SignBitsUnpackTilingData)));
    }

    ~KernelBuffers()
    {
        AscendC::GmFree(input);
        AscendC::GmFree(output);
        AscendC::GmFree(workspace);
        AscendC::GmFree(tiling);
    }

    KernelBuffers(const KernelBuffers&) = delete;
    KernelBuffers& operator=(const KernelBuffers&) = delete;

    uint8_t* input;
    uint8_t* output;
    uint8_t* workspace;
    uint8_t* tiling;
};

void SetTilingData(uint8_t* tiling, uint64_t totalNum, uint64_t blockFactor, uint64_t size,
                   uint64_t ubFactor = UB_FACTOR)
{
    auto* data = reinterpret_cast<SignBitsUnpackTilingData*>(tiling);
    data->totalNum = totalNum;
    data->blockFactor = blockFactor;
    data->ubFactor = ubFactor;
    data->size = size;
    data->enableDump = 0;
    data->dumpFlag = 0;
}

template <typename T>
void ExpectUnpacked(const uint8_t* input, const T* output, size_t inputCount)
{
    for (size_t byteIndex = 0; byteIndex < inputCount; ++byteIndex) {
        for (size_t bitIndex = 0; bitIndex < 8; ++bitIndex) {
            const size_t outputIndex = byteIndex * 8 + bitIndex;
            const float expected = ((input[byteIndex] >> bitIndex) & 1U) != 0 ? 1.0F : -1.0F;
            EXPECT_FLOAT_EQ(static_cast<float>(output[outputIndex]), expected)
                << "byte=" << byteIndex << ", bit=" << bitIndex;
        }
    }
}

void sign_bits_unpack_half_for_test(GM_ADDR input, GM_ADDR output, GM_ADDR, GM_ADDR tiling)
{
    GET_TILING_DATA_WITH_STRUCT(SignBitsUnpackTilingData, tilingData, tiling);
    NsSignBitsUnpack::SignBitsUnpackKernel<uint8_t, half> op;
    op.Init(input, output, &tilingData);
    op.Process();
}
} // namespace

class SignBitsUnpackKernelTest : public testing::Test {};

TEST_F(SignBitsUnpackKernelTest, float32_known_bit_patterns)
{
    constexpr std::array<uint8_t, 16> inputData = {
        0x9F, 0x0F, 0x00, 0xFF, 0xAA, 0x55, 0x81, 0x7E, 0x01, 0x80, 0x33, 0xCC, 0xF0, 0x0F, 0x69, 0x96,
    };
    KernelBuffers buffers(inputData.size(), sizeof(float));
    std::memcpy(buffers.input, inputData.data(), inputData.size());
    SetTilingData(buffers.tiling, inputData.size(), inputData.size(), 2);

    AscendC::SetKernelMode(KernelMode::AIV_MODE);
    ICPU_RUN_KF(sign_bits_unpack, 1, buffers.input, buffers.output, buffers.workspace, buffers.tiling);

    ExpectUnpacked(inputData.data(), reinterpret_cast<const float*>(buffers.output), inputData.size());
}

TEST_F(SignBitsUnpackKernelTest, float16_known_bit_patterns)
{
    constexpr std::array<uint8_t, 16> inputData = {
        0x00, 0xFF, 0xAA, 0x55, 0x9F, 0x0F, 0x81, 0x7E, 0x01, 0x80, 0x33, 0xCC, 0xF0, 0x0F, 0x69, 0x96,
    };
    KernelBuffers buffers(inputData.size(), sizeof(half));
    std::memcpy(buffers.input, inputData.data(), inputData.size());
    SetTilingData(buffers.tiling, inputData.size(), inputData.size(), 4);

    AscendC::SetKernelMode(KernelMode::AIV_MODE);
    ICPU_RUN_KF(sign_bits_unpack_half_for_test, 1, buffers.input, buffers.output, buffers.workspace, buffers.tiling);

    ExpectUnpacked(inputData.data(), reinterpret_cast<const half*>(buffers.output), inputData.size());
}

TEST_F(SignBitsUnpackKernelTest, float32_consumes_all_mask_groups_in_one_ub_iteration)
{
    constexpr uint64_t largeUbFactor = 512;
    std::array<uint8_t, largeUbFactor / 8> inputData = {};
    for (size_t i = 0; i < inputData.size(); ++i) {
        inputData[i] = static_cast<uint8_t>(i * 37U + 11U);
    }
    KernelBuffers buffers(inputData.size(), sizeof(float));
    std::memcpy(buffers.input, inputData.data(), inputData.size());
    SetTilingData(buffers.tiling, inputData.size(), inputData.size(), 1, largeUbFactor);

    AscendC::SetKernelMode(KernelMode::AIV_MODE);
    ICPU_RUN_KF(sign_bits_unpack, 1, buffers.input, buffers.output, buffers.workspace, buffers.tiling);

    ExpectUnpacked(inputData.data(), reinterpret_cast<const float*>(buffers.output), inputData.size());
}

TEST_F(SignBitsUnpackKernelTest, float16_consumes_all_mask_groups_in_one_ub_iteration)
{
    constexpr uint64_t largeUbFactor = 512;
    std::array<uint8_t, largeUbFactor / 8> inputData = {};
    for (size_t i = 0; i < inputData.size(); ++i) {
        inputData[i] = static_cast<uint8_t>(i * 53U + 7U);
    }
    KernelBuffers buffers(inputData.size(), sizeof(half));
    std::memcpy(buffers.input, inputData.data(), inputData.size());
    SetTilingData(buffers.tiling, inputData.size(), inputData.size(), 1, largeUbFactor);

    AscendC::SetKernelMode(KernelMode::AIV_MODE);
    ICPU_RUN_KF(sign_bits_unpack_half_for_test, 1, buffers.input, buffers.output, buffers.workspace, buffers.tiling);

    ExpectUnpacked(inputData.data(), reinterpret_cast<const half*>(buffers.output), inputData.size());
}

TEST_F(SignBitsUnpackKernelTest, tail_input_runs_multiple_ub_iterations)
{
    constexpr std::array<uint8_t, 17> inputData = {
        0x00, 0xFF, 0xAA, 0x55, 0x9F, 0x0F, 0x81, 0x7E, 0x01, 0x80, 0x33, 0xCC, 0xF0, 0x0F, 0x69, 0x96, 0xA5,
    };
    KernelBuffers buffers(inputData.size(), sizeof(float));
    std::memcpy(buffers.input, inputData.data(), inputData.size());
    SetTilingData(buffers.tiling, inputData.size(), 32, 1);

    AscendC::SetKernelMode(KernelMode::AIV_MODE);
    ICPU_RUN_KF(sign_bits_unpack, 1, buffers.input, buffers.output, buffers.workspace, buffers.tiling);

    ExpectUnpacked(inputData.data(), reinterpret_cast<const float*>(buffers.output), inputData.size());
}

TEST_F(SignBitsUnpackKernelTest, empty_input_skips_processing)
{
    constexpr uint8_t sentinel = 0xA5;
    constexpr size_t outputBytes = 8 * sizeof(float);
    KernelBuffers buffers(1, sizeof(float));
    std::memset(buffers.output, sentinel, outputBytes);
    SetTilingData(buffers.tiling, 0, 0, 2);

    AscendC::SetKernelMode(KernelMode::AIV_MODE);
    ICPU_RUN_KF(sign_bits_unpack, 1, buffers.input, buffers.output, buffers.workspace, buffers.tiling);

    for (size_t i = 0; i < outputBytes; ++i) {
        EXPECT_EQ(buffers.output[i], sentinel) << "output byte=" << i;
    }
}

TEST_F(SignBitsUnpackKernelTest, two_core_partition)
{
    std::array<uint8_t, 32> inputData = {};
    for (size_t i = 0; i < inputData.size(); ++i) {
        inputData[i] = static_cast<uint8_t>(i * 7U + 3U);
    }
    KernelBuffers buffers(inputData.size(), sizeof(float));
    std::memcpy(buffers.input, inputData.data(), inputData.size());
    SetTilingData(buffers.tiling, inputData.size(), 16, 8);

    AscendC::SetKernelMode(KernelMode::AIV_MODE);
    ICPU_RUN_KF(sign_bits_unpack, 2, buffers.input, buffers.output, buffers.workspace, buffers.tiling);

    ExpectUnpacked(inputData.data(), reinterpret_cast<const float*>(buffers.output), inputData.size());
}
