/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */


/*!
 * \file inv_apt.cpp
 * \brief Inv 算子 Kernel 入口（arch35 / Ascend950）
 *
 * 模板参数 D_T_SELF 由 inv_tiling_key.h 中 ASCENDC_TPL_ARGS_DECL 定义。
 * dtype 静态分发：Inv<float> / Inv<half> / Inv<bfloat16_t> / Inv<int32_t> 共 4 个实例。
 */

#include "arch35/inv.h"

template <typename D_T_SELF>
__global__ __aicore__ void inv(GM_ADDR self, GM_ADDR out, GM_ADDR workspace, GM_ADDR tiling)
{
    REGISTER_TILING_DEFAULT(InvTilingData);
    GET_TILING_DATA_WITH_STRUCT(InvTilingData, tilingData, tiling);
    NsInv::Inv<D_T_SELF> op;
    op.Init(self, out, &tilingData);
    op.Process();
}
