/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file radix_sort_simt.h
 * \brief Process dispatcher for radix_sort
 */

#ifndef RADIX_SORT_SIMT_H
#define RADIX_SORT_SIMT_H

#include "kernel_operator.h"
#include "simt_api/common_functions.h"
#include "simt_api/asc_simt.h"
#include "simt_api/device_sync_functions.h"
#include "radix_sort_base.h"
#include "radix_sort_small.h"
#include "radix_sort_large.h"
#include "radix_sort_global.h"
#include "radix_sort_tiling_data.h"

namespace NsRadixSort {
using namespace AscendC;

static constexpr int64_t UB_ALIGN = 32;

__aicore__ inline int64_t AlignAllocN(int64_t n, int64_t elemSize)
{
    int64_t bytes = n * elemSize;
    return ((bytes + UB_ALIGN - 1) / UB_ALIGN) * UB_ALIGN / elemSize;
}

template <typename T, bool descending>
__aicore__ inline void ProcessSmallSingle(
    LocalMemAllocator<Hardware::UB>& ubAlloc,
    int64_t currentCoreElements, int64_t coreOff,
    __gm__ T* xGm, __gm__ T* sortedValuesGm, __gm__ int64_t* sortedIndicesGm)
{
    using Trait = RadixSortTrait<T>;
    using SortType = typename Trait::SortType;

    auto ubKeysPing = ubAlloc.Alloc<SortType>(AlignAllocN(Trait::UB_SORT_BUF, sizeof(SortType)));
    auto ubKeysPong = ubAlloc.Alloc<SortType>(AlignAllocN(Trait::UB_SORT_BUF, sizeof(SortType)));
    auto ubIdxPing  = ubAlloc.Alloc<int64_t>(AlignAllocN(Trait::UB_SORT_BUF, sizeof(int64_t)));
    auto ubIdxPong  = ubAlloc.Alloc<int64_t>(AlignAllocN(Trait::UB_SORT_BUF, sizeof(int64_t)));
    auto ubHist     = ubAlloc.Alloc<int32_t>(AlignAllocN(RADIX_BINS, sizeof(int32_t)));
    auto ubPref     = ubAlloc.Alloc<int64_t>(AlignAllocN(RADIX_BINS, sizeof(int64_t)));

    asc_vf_call<RadixSortSmallKernel<T>>(
        dim3(THREAD_NUM),
        currentCoreElements, coreOff, descending,
        xGm, sortedValuesGm, sortedIndicesGm,
        (__ubuf__ SortType*)ubKeysPing.GetPhyAddr(),
        (__ubuf__ SortType*)ubKeysPong.GetPhyAddr(),
        (__ubuf__ int64_t*)ubIdxPing.GetPhyAddr(),
        (__ubuf__ int64_t*)ubIdxPong.GetPhyAddr(),
        (__ubuf__ int32_t*)ubHist.GetPhyAddr(),
        (__ubuf__ int64_t*)ubPref.GetPhyAddr());
}

template <typename T, bool descending>
__aicore__ inline void ProcessSmallPerCore(
    LocalMemAllocator<Hardware::UB>& ubAlloc,
    const RadixSortTilingData* td, int64_t currentCoreElements, int64_t coreOff,
    __gm__ T* xGm, __gm__ char* wsGm)
{
    using Trait = RadixSortTrait<T>;
    using SortType = typename Trait::SortType;
    int64_t coreIdx = GetBlockIdx();

    auto ubKeysPing = ubAlloc.Alloc<SortType>(AlignAllocN(Trait::UB_SORT_BUF, sizeof(SortType)));
    auto ubKeysPong = ubAlloc.Alloc<SortType>(AlignAllocN(Trait::UB_SORT_BUF, sizeof(SortType)));
    auto ubIdxPing  = ubAlloc.Alloc<int64_t>(AlignAllocN(Trait::UB_SORT_BUF, sizeof(int64_t)));
    auto ubIdxPong  = ubAlloc.Alloc<int64_t>(AlignAllocN(Trait::UB_SORT_BUF, sizeof(int64_t)));
    auto ubHist     = ubAlloc.Alloc<int32_t>(AlignAllocN(RADIX_BINS, sizeof(int32_t)));
    auto ubPref     = ubAlloc.Alloc<int64_t>(AlignAllocN(RADIX_BINS, sizeof(int64_t)));

    int64_t wsElem = td->wsElemSize;
    __gm__ SortType* wsKeysGm = reinterpret_cast<__gm__ SortType*>(wsGm);
    __gm__ int64_t* wsIdxGm = reinterpret_cast<__gm__ int64_t*>(
        wsGm + ((static_cast<int64_t>(td->needCoreNum) * td->perCoreElements *
        wsElem + WS_ALIGN - 1) / WS_ALIGN) * WS_ALIGN);

    asc_vf_call<RadixSortSmallKernel<T>>(
        dim3(THREAD_NUM),
        currentCoreElements, coreOff, descending,
        xGm, reinterpret_cast<__gm__ T*>(wsKeysGm), wsIdxGm,
        (__ubuf__ SortType*)ubKeysPing.GetPhyAddr(),
        (__ubuf__ SortType*)ubKeysPong.GetPhyAddr(),
        (__ubuf__ int64_t*)ubIdxPing.GetPhyAddr(),
        (__ubuf__ int64_t*)ubIdxPong.GetPhyAddr(),
        (__ubuf__ int32_t*)ubHist.GetPhyAddr(),
        (__ubuf__ int64_t*)ubPref.GetPhyAddr());
}

template <typename T, bool descending>
__aicore__ inline void ProcessLargeSingle(
    LocalMemAllocator<Hardware::UB>& ubAlloc,
    const RadixSortTilingData* td, int64_t currentCoreElements, int64_t coreOff,
    __gm__ T* xGm, __gm__ char* wsGm,
    __gm__ T* sortedValuesGm, __gm__ int64_t* sortedIndicesGm)
{
    using Trait = RadixSortTrait<T>;
    using SortType = typename Trait::SortType;

    auto ubTileKeys    = ubAlloc.Alloc<SortType>(AlignAllocN(Trait::UB_SORT_BUF, sizeof(SortType)));
    auto ubTileIndices = ubAlloc.Alloc<int64_t>(AlignAllocN(Trait::UB_SORT_BUF, sizeof(int64_t)));
    auto ubHist        = ubAlloc.Alloc<int32_t>(AlignAllocN(RADIX_BINS, sizeof(int32_t)));
    auto ubPref        = ubAlloc.Alloc<int64_t>(AlignAllocN(RADIX_BINS, sizeof(int64_t)));
    auto ubGlobalHist  = ubAlloc.Alloc<int64_t>(AlignAllocN(RADIX_BINS, sizeof(int64_t)));

    asc_vf_call<RadixSortLargeKernel<T>>(
        dim3(THREAD_NUM),
        currentCoreElements, coreOff, descending,
        td->totalElements, 0, td->wsScatterOffset, td->wsElemSize,
        xGm, wsGm, sortedValuesGm, sortedIndicesGm,
        (__ubuf__ SortType*)ubTileKeys.GetPhyAddr(),
        (__ubuf__ int64_t*)ubTileIndices.GetPhyAddr(),
        (__ubuf__ int32_t*)ubHist.GetPhyAddr(),
        (__ubuf__ int64_t*)ubPref.GetPhyAddr(),
        (__ubuf__ int64_t*)ubGlobalHist.GetPhyAddr());
}

template <typename T, bool descending>
__aicore__ inline void ProcessLargePerCore(
    LocalMemAllocator<Hardware::UB>& ubAlloc,
    const RadixSortTilingData* td, int64_t currentCoreElements, int64_t coreOff,
    __gm__ T* xGm, __gm__ char* wsGm)
{
    using Trait = RadixSortTrait<T>;
    using SortType = typename Trait::SortType;
    int64_t coreIdx = GetBlockIdx();

    auto ubTileKeys    = ubAlloc.Alloc<SortType>(AlignAllocN(Trait::UB_SORT_BUF, sizeof(SortType)));
    auto ubTileIndices = ubAlloc.Alloc<int64_t>(AlignAllocN(Trait::UB_SORT_BUF, sizeof(int64_t)));
    auto ubHist        = ubAlloc.Alloc<int32_t>(AlignAllocN(RADIX_BINS, sizeof(int32_t)));
    auto ubPref        = ubAlloc.Alloc<int64_t>(AlignAllocN(RADIX_BINS, sizeof(int64_t)));
    auto ubGlobalHist  = ubAlloc.Alloc<int64_t>(AlignAllocN(RADIX_BINS, sizeof(int64_t)));

    int64_t wsElem = td->wsElemSize;
    int64_t histAreaBytes = td->totalTiles * static_cast<int64_t>(RADIX_BINS)
        * static_cast<int64_t>(sizeof(int32_t));
    int64_t histAligned = ((histAreaBytes + WS_ALIGN - 1) / WS_ALIGN) * WS_ALIGN;
    int64_t histBase = coreIdx * histAligned;
    int64_t scatterStride = ((td->perCoreElements * td->wsElemSize
        + WS_ALIGN - 1) / WS_ALIGN) * WS_ALIGN;
    int64_t scatterPerCore = scatterStride * 4;
    int64_t scatterBase = td->wsScatterOffset + coreIdx * scatterPerCore;
    int64_t mergeBase = td->wsScatterOffset
        + static_cast<int64_t>(td->needCoreNum) * scatterPerCore;
    __gm__ T* coreSortedValuesGm = reinterpret_cast<__gm__ T*>(
        wsGm + mergeBase);
    __gm__ int64_t* coreSortedIndicesGm = reinterpret_cast<__gm__ int64_t*>(
        wsGm + mergeBase + ((static_cast<int64_t>(td->needCoreNum)
        * td->perCoreElements * wsElem + WS_ALIGN - 1) / WS_ALIGN) * WS_ALIGN);

    asc_vf_call<RadixSortLargeKernel<T>>(
        dim3(THREAD_NUM),
        currentCoreElements, coreOff, descending,
        td->perCoreElements, histBase, scatterBase, td->wsElemSize,
        xGm, wsGm, coreSortedValuesGm, coreSortedIndicesGm,
        (__ubuf__ SortType*)ubTileKeys.GetPhyAddr(),
        (__ubuf__ int64_t*)ubTileIndices.GetPhyAddr(),
        (__ubuf__ int32_t*)ubHist.GetPhyAddr(),
        (__ubuf__ int64_t*)ubPref.GetPhyAddr(),
        (__ubuf__ int64_t*)ubGlobalHist.GetPhyAddr());
}

template <typename T, bool descending>
__aicore__ inline void DoTreeMerge(
    const RadixSortTilingData* td, int64_t mergeOff,
    __gm__ char* wsGm,
    __gm__ T* sortedValuesGm, __gm__ int64_t* sortedIndicesGm,
    LocalMemAllocator<Hardware::UB>& ubAlloc)
{
    using SortType = typename RadixSortTrait<T>::SortType;

    auto ubSegA = ubAlloc.Alloc<int64_t>(
        AlignAllocN(THREAD_NUM + 1, sizeof(int64_t)));

    int64_t wsElem = td->wsElemSize;
    int64_t perCore = td->perCoreElements;
    int64_t needCore = td->needCoreNum;
    int64_t totalElements = td->totalElements;

    int64_t keyAreaBytes = ((needCore * perCore * wsElem + WS_ALIGN - 1)
        / WS_ALIGN) * WS_ALIGN;
    int64_t idxAreaBytes = ((needCore * perCore * static_cast<int64_t>(sizeof(int64_t))
        + WS_ALIGN - 1) / WS_ALIGN) * WS_ALIGN;
    int64_t tempKeysOff = mergeOff + ((keyAreaBytes + idxAreaBytes + WS_ALIGN - 1)
        / WS_ALIGN) * WS_ALIGN;
    int64_t tempIdxOff = tempKeysOff + keyAreaBytes;

    __gm__ SortType* srcKeys = reinterpret_cast<__gm__ SortType*>(wsGm + mergeOff);
    __gm__ int64_t* srcIdx = reinterpret_cast<__gm__ int64_t*>(
        wsGm + mergeOff + keyAreaBytes);
    __gm__ SortType* dstKeys = reinterpret_cast<__gm__ SortType*>(wsGm + tempKeysOff);
    __gm__ int64_t* dstIdx = reinterpret_cast<__gm__ int64_t*>(
        wsGm + tempIdxOff);

    int64_t coreIdx = GetBlockIdx();
    int64_t gap = 1;

    while (gap < needCore) {
        int64_t segSize = gap * perCore;
        int64_t segBase = coreIdx * perCore;
        int64_t partnerBase = segBase + segSize;

        if (coreIdx % (gap * 2) == 0) {
            if (partnerBase < totalElements) {
                int64_t leftElements = segSize;
                if (segBase + leftElements > totalElements) {
                    leftElements = totalElements - segBase;
                }
                int64_t rightElements = segSize;
                if (partnerBase + rightElements > totalElements) {
                    rightElements = totalElements - partnerBase;
                }

                asc_vf_call<RadixSortMerge2WayParallelKernel<T, descending>>(
            dim3(SCATTER_THREAD_NUM),
                    leftElements, rightElements,
                    srcKeys + segBase, srcIdx + segBase,
                    srcKeys + partnerBase, srcIdx + partnerBase,
                    reinterpret_cast<__gm__ T*>(dstKeys + segBase),
                    dstIdx + segBase,
                    (__ubuf__ int64_t*)ubSegA.GetPhyAddr());
            } else if (segBase < totalElements) {
                int64_t leftElements = segSize;
                if (segBase + leftElements > totalElements) {
                    leftElements = totalElements - segBase;
                }
                asc_vf_call<RadixSortCopySegmentKernel<T, descending>>(
                    dim3(COPY_THREAD_NUM),
                    leftElements,
                    srcKeys + segBase, srcIdx + segBase,
                    reinterpret_cast<__gm__ T*>(dstKeys + segBase),
                    dstIdx + segBase);
            }
        }

        SyncAll();

        __gm__ SortType* tmpKeys = srcKeys;
        srcKeys = dstKeys;
        dstKeys = tmpKeys;
        __gm__ int64_t* tmpIdx = srcIdx;
        srcIdx = dstIdx;
        dstIdx = tmpIdx;
        gap *= 2;
    }

    asc_vf_call<RadixSortCopySegmentKernel<T, descending>>(
        dim3(THREAD_NUM),
        totalElements,
        srcKeys, srcIdx,
        sortedValuesGm, sortedIndicesGm);
}

template <typename T, bool descending>
__aicore__ inline void ProcessGlobalRadixSort(
    const RadixSortTilingData* td,
    __gm__ T* xGm, __gm__ char* wsGm,
    __gm__ T* sortedValuesGm, __gm__ int64_t* sortedIndicesGm,
    LocalMemAllocator<Hardware::UB>& ubAlloc)
{
    using Trait = RadixSortTrait<T>;
    using SortType = typename Trait::SortType;

    int64_t perCore = td->perCoreElements;
    int64_t needCore = td->needCoreNum;
    int64_t totalElements = td->totalElements;
    int64_t wsElem = td->wsElemSize;

    int64_t coreIdx = GetBlockIdx();
    int64_t coreOff = coreIdx * perCore;
    int64_t coreEnd = coreOff + perCore;
    if (coreIdx == needCore - 1) { coreEnd = totalElements; }
    int64_t currentCoreElements = coreEnd - coreOff;

    auto ubHist = ubAlloc.Alloc<int32_t>(
        AlignAllocN(RADIX_BINS, sizeof(int32_t)));
    auto ubScatter = ubAlloc.Alloc<int32_t>(
        AlignAllocN(UB_DIGIT_OFF + (UB_COUNTER_OFF - UB_DIGIT_OFF) + RADIX_BINS + RADIX_BINS, sizeof(int32_t)));
    auto ubWarpBuf = ubAlloc.Alloc<int64_t>(
        AlignAllocN(PREFIX_NUM_WARPS, sizeof(int64_t)));

    int64_t histCells = static_cast<int64_t>(needCore) * RADIX_BINS;
    int64_t globalHistOff = 0;
    int64_t prefixSumOff = AlignUp(globalHistOff + RADIX_BINS * sizeof(int64_t), WS_ALIGN);
    int64_t perCoreHistsOff = AlignUp(prefixSumOff + RADIX_BINS * sizeof(int64_t), WS_ALIGN);
    int64_t coreStartsOff = AlignUp(perCoreHistsOff + histCells * sizeof(int64_t), WS_ALIGN);
    int64_t keyAreaBytes = AlignUp(totalElements * wsElem, WS_ALIGN);
    int64_t keyBufAOff = AlignUp(coreStartsOff + histCells * sizeof(int64_t), WS_ALIGN);
    int64_t idxBufAOff = AlignUp(keyBufAOff + keyAreaBytes, WS_ALIGN);
    int64_t keyBufBOff = AlignUp(idxBufAOff + totalElements * sizeof(int64_t), WS_ALIGN);
    int64_t idxBufBOff = AlignUp(keyBufBOff + keyAreaBytes, WS_ALIGN);

    __gm__ int64_t* globalHist = reinterpret_cast<__gm__ int64_t*>(
        wsGm + globalHistOff);
    __gm__ int64_t* prefixSum = reinterpret_cast<__gm__ int64_t*>(
        wsGm + prefixSumOff);
    __gm__ int64_t* perCoreHists = reinterpret_cast<__gm__ int64_t*>(
        wsGm + perCoreHistsOff);
    __gm__ int64_t* coreStarts = reinterpret_cast<__gm__ int64_t*>(
        wsGm + coreStartsOff);
    __gm__ SortType* keyBufA = reinterpret_cast<__gm__ SortType*>(
        wsGm + keyBufAOff);
    __gm__ int64_t* idxBufA = reinterpret_cast<__gm__ int64_t*>(
        wsGm + idxBufAOff);
    __gm__ SortType* keyBufB = reinterpret_cast<__gm__ SortType*>(
        wsGm + keyBufBOff);
    __gm__ int64_t* idxBufB = reinterpret_cast<__gm__ int64_t*>(
        wsGm + idxBufBOff);

    __gm__ SortType* srcKeys = keyBufA;
    __gm__ int64_t* srcIdx = idxBufA;
    __gm__ SortType* dstKeys = keyBufB;
    __gm__ int64_t* dstIdx = idxBufB;

    for (int32_t pass = 0; pass < RadixSortTrait<T>::NUM_PASSES; pass++) {
        int32_t byteShift = pass * RADIX_BITS;
        bool isFirst = (pass == 0);

        // Clear global histogram via VF (all cores, all threads)
        asc_vf_call<RadixSortGlobalClearKernel<T>>(
            dim3(THREAD_NUM), globalHist);
        SyncAll();

        // Phase 1: Per-core histogram (+ inline Encode on first pass)
        if (isFirst) {
            asc_vf_call<RadixSortGlobalHistogramKernel<T, descending, true>>(
                dim3(THREAD_NUM),
                byteShift,
                currentCoreElements, coreOff,
                xGm, nullptr, perCoreHists, globalHist,
                (__ubuf__ int32_t*)ubHist.GetPhyAddr(),
                keyBufA, idxBufA);
        } else {
            asc_vf_call<RadixSortGlobalHistogramKernel<T, descending, false>>(
                dim3(THREAD_NUM),
                byteShift,
                currentCoreElements, coreOff,
                nullptr, srcKeys, perCoreHists, globalHist,
                (__ubuf__ int32_t*)ubHist.GetPhyAddr(),
                nullptr, nullptr);
        }
        SyncAll();

        // Phase 2: Global inclusive prefix sum + per-core start positions (256 threads, 8 warps)
        asc_vf_call<RadixSortGlobalPrefixKernel<T>>(
            dim3(PREFIX_THREAD_NUM),
            needCore, globalHist, perCoreHists, prefixSum, coreStarts,
            (__ubuf__ int64_t*)ubWarpBuf.GetPhyAddr());
        SyncAll();

        // Phase 3: Scatter (all cores, using per-core starts + per-strip UB digit sharing)
        bool isLast = (pass == RadixSortTrait<T>::NUM_PASSES - 1);
        if (isLast) {
            asc_vf_call<RadixSortGlobalScatterKernel<T, descending, true>>(
                dim3(SCATTER_THREAD_NUM),
                byteShift,
                currentCoreElements, coreOff,
                srcKeys, srcIdx, coreStarts, prefixSum,
                reinterpret_cast<__gm__ SortType*>(sortedValuesGm),
                sortedIndicesGm,
                (__ubuf__ int32_t*)ubScatter.GetPhyAddr());
        } else {
            asc_vf_call<RadixSortGlobalScatterKernel<T, descending, false>>(
                dim3(SCATTER_THREAD_NUM),
                byteShift,
                currentCoreElements, coreOff,
                srcKeys, srcIdx, coreStarts, prefixSum,
                dstKeys, dstIdx,
                (__ubuf__ int32_t*)ubScatter.GetPhyAddr());
        }
        SyncAll();

        if (isLast) { break; }

        // Swap ping-pong
        __gm__ SortType* tmpKeys = srcKeys;
        srcKeys = dstKeys; dstKeys = tmpKeys;
        __gm__ int64_t* tmpIdx = srcIdx;
        srcIdx = dstIdx; dstIdx = tmpIdx;
    }
}

template <typename T, bool descending>
__aicore__ inline void Process(
    GM_ADDR x, GM_ADDR sortedValues, GM_ADDR sortedIndices,
    GM_ADDR workspace, const RadixSortTilingData* td)
{
    __gm__ T* xGm = (__gm__ T*)x;
    __gm__ T* sortedValuesGm = (__gm__ T*)sortedValues;
    __gm__ int64_t* sortedIndicesGm = (__gm__ int64_t*)sortedIndices;
    __gm__ char* wsGm = (__gm__ char*)workspace;

    if (td->totalElements == 0) { return; }

    int64_t coreIdx = GetBlockIdx();
    int64_t coreOff = coreIdx * td->perCoreElements;
    int64_t coreEnd = coreOff + td->perCoreElements;
    if (coreIdx == td->needCoreNum - 1) {
        coreEnd = td->totalElements;
    }
    int64_t currentCoreElements = coreEnd - coreOff;

    LocalMemAllocator<Hardware::UB> ubAlloc;

    switch (td->pathType) {
    case 1:
        ProcessSmallSingle<T, descending>(ubAlloc, currentCoreElements, coreOff,
            xGm, sortedValuesGm, sortedIndicesGm);
        break;
    case 2:
    case 4:
        ProcessGlobalRadixSort<T, descending>(td, xGm, wsGm, sortedValuesGm,
            sortedIndicesGm, ubAlloc);
        break;
    case 3:
        ProcessLargeSingle<T, descending>(ubAlloc, td, currentCoreElements, coreOff,
            xGm, wsGm, sortedValuesGm, sortedIndicesGm);
        break;
    default:
        break;
    }
}

} // namespace NsRadixSort

#endif
