/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file radix_sort_large.h
 * \brief Path C/D: Tile-level GM radix sort + multi-core merge
 */

#ifndef RADIX_SORT_LARGE_H
#define RADIX_SORT_LARGE_H

#include "kernel_operator.h"
#include "kernel_tiling/kernel_tiling.h"
#include "simt_api/common_functions.h"
#include "simt_api/asc_simt.h"
#include "simt_api/device_atomic_functions.h"
#include "simt_api/device_sync_functions.h"
#include "radix_sort_base.h"
#include "radix_sort_tiling_data.h"

namespace NsRadixSort {
using namespace AscendC;

template <typename T>
__simt_vf__ __aicore__ __launch_bounds__(THREAD_NUM)
inline void RadixSortLargeKernel(
    int64_t currentCoreElements, int64_t coreOff, bool descending,
    int64_t totalElements, int64_t histBase, int64_t scatterBase, int64_t wsElemSize,
    __gm__ T* xGm, __gm__ char* wsGm,
    __gm__ T* sortedValuesGm, __gm__ int64_t* sortedIndicesGm,
    __ubuf__ typename RadixSortTrait<T>::SortType* tileKeys,
    __ubuf__ int64_t* tileIndices,
    __ubuf__ int32_t* histogram, __ubuf__ int64_t* prefixSum,
    __ubuf__ int64_t* globalHist)
{
    using Trait = RadixSortTrait<T>;
    using SortType = typename Trait::SortType;
    uint32_t localTid = threadIdx.x;
    uint32_t threadNum = blockDim.x;

    int64_t tileSize = Trait::UB_SORT_BUF;
    int64_t totalTiles = (currentCoreElements + tileSize - 1) / tileSize;

    int64_t scatterStride = ((totalElements * wsElemSize + WS_ALIGN - 1)
        / WS_ALIGN) * WS_ALIGN;
    __gm__ SortType* gmSrcKeys = reinterpret_cast<__gm__ SortType*>(
        wsGm + scatterBase);
    __gm__ int64_t* gmSrcIdx = reinterpret_cast<__gm__ int64_t*>(
        wsGm + scatterBase + scatterStride);
    __gm__ SortType* gmDstKeys = reinterpret_cast<__gm__ SortType*>(
        wsGm + scatterBase + scatterStride * 2);
    __gm__ int64_t* gmDstIdx = reinterpret_cast<__gm__ int64_t*>(
        wsGm + scatterBase + scatterStride * 3);
    __gm__ int32_t* wsHist = reinterpret_cast<__gm__ int32_t*>(
        wsGm + histBase);

    for (int64_t t = 0; t < totalTiles; t++) {
        int64_t start = t * tileSize;
        int64_t sz = (start + tileSize <= currentCoreElements) ? tileSize
                                                               : (currentCoreElements - start);
        for (int64_t i = localTid; i < sz; i += threadNum) {
            SortType encoded = Trait::Encode(xGm[coreOff + start + i]);
            gmSrcKeys[start + i] = encoded;
            gmSrcIdx[start + i] = coreOff + start + i;
        }
    }
    asc_syncthreads();

    for (int32_t byteIdx = 0; byteIdx < Trait::NUM_PASSES; byteIdx++) {
        int32_t shift = byteIdx * RADIX_BITS;

        for (int64_t t = 0; t < totalTiles; t++) {
            int64_t start = t * tileSize;
            int64_t sz = (start + tileSize <= currentCoreElements) ? tileSize
                                                                   : (currentCoreElements - start);

            for (int64_t i = localTid; i < sz; i += threadNum) {
                tileKeys[i] = gmSrcKeys[start + i];
                tileIndices[i] = gmSrcIdx[start + i];
            }
            asc_syncthreads();

            for (int32_t b = localTid; b < RADIX_BINS; b += threadNum) {
                histogram[b] = 0;
            }
            asc_syncthreads();

            for (int64_t i = localTid; i < sz; i += threadNum) {
                SortType key = tileKeys[i];
                int32_t digit = static_cast<int32_t>((key >> shift) & RADIX_DIGIT_MASK);
                if (descending) { digit = RADIX_MAX_DIGIT - digit; }
                asc_atomic_add(&histogram[digit], 1);
            }
            asc_syncthreads();

            int64_t histOff = WS_HIST_OFFSET / static_cast<int64_t>(sizeof(int32_t))
                + t * static_cast<int64_t>(RADIX_BINS);
            for (int32_t b = localTid; b < RADIX_BINS; b += threadNum) {
                wsHist[histOff + b] = histogram[b];
            }
            asc_syncthreads();
        }

        for (int32_t b = localTid; b < RADIX_BINS; b += threadNum) {
            globalHist[b] = 0;
        }
        asc_syncthreads();

        int64_t histPerTile = static_cast<int64_t>(RADIX_BINS);
        for (int64_t t = 0; t < totalTiles; t++) {
            for (int32_t b = localTid; b < RADIX_BINS; b += threadNum) {
                int64_t off = WS_HIST_OFFSET / static_cast<int64_t>(sizeof(int32_t))
                    + t * histPerTile + b;
                globalHist[b] += static_cast<int64_t>(wsHist[off]);
            }
            asc_syncthreads();
        }

        if (localTid == 0) {
            int64_t total = 0;
            for (int32_t b = 0; b < RADIX_BINS; b++) {
                total += globalHist[b];
                prefixSum[b] = total;
            }
        }
        asc_syncthreads();

        for (int64_t t = totalTiles - 1; t >= 0; t--) {
            int64_t start = t * tileSize;
            int64_t sz = (start + tileSize <= currentCoreElements) ? tileSize
                                                                   : (currentCoreElements - start);

            for (int64_t i = localTid; i < sz; i += threadNum) {
                tileKeys[i] = gmSrcKeys[start + i];
                tileIndices[i] = gmSrcIdx[start + i];
            }
            asc_syncthreads();

            if (localTid == 0) {
                for (int64_t i = sz - 1; i >= 0; i--) {
                    SortType key = tileKeys[i];
                    int32_t digit = static_cast<int32_t>((key >> shift) & RADIX_DIGIT_MASK);
                    if (descending) { digit = RADIX_MAX_DIGIT - digit; }
                    prefixSum[digit]--;
                    int64_t pos = prefixSum[digit];
                    gmDstKeys[pos] = key;
                    gmDstIdx[pos] = tileIndices[i];
                }
            }
            asc_syncthreads();
        }

        __gm__ SortType* tmpKeys = gmSrcKeys;
        gmSrcKeys = gmDstKeys;
        gmDstKeys = tmpKeys;
        __gm__ int64_t* tmpIdx = gmSrcIdx;
        gmSrcIdx = gmDstIdx;
        gmDstIdx = tmpIdx;
    }

    for (int64_t i = localTid; i < currentCoreElements; i += threadNum) {
        sortedValuesGm[coreOff + i] = Trait::Decode(gmSrcKeys[i]);
        sortedIndicesGm[coreOff + i] = gmSrcIdx[i];
    }
}

template <typename T, bool descending>
__simt_vf__ __aicore__ __launch_bounds__(THREAD_NUM)
inline void RadixSortMergeKernel(
    int32_t needCoreNum, int64_t perCoreElements, int64_t totalElements,
    __gm__ typename RadixSortTrait<T>::SortType* wsKeysGm,
    __gm__ int64_t* wsIndicesGm,
    __gm__ T* sortedValuesGm, __gm__ int64_t* sortedIndicesGm,
    __ubuf__ int64_t* segCursor, __ubuf__ int64_t* segRemaining)
{
    using Trait = RadixSortTrait<T>;
    using SortType = typename Trait::SortType;
    uint32_t localTid = threadIdx.x;

    if (localTid != 0) {
        return;
    }

    const __gm__ T* wsSigned = reinterpret_cast<const __gm__ T*>(wsKeysGm);

    for (int32_t s = 0; s < needCoreNum; s++) {
        int64_t segBase = s * perCoreElements;
        segCursor[s] = segBase;
        segRemaining[s] = (s == needCoreNum - 1)
            ? totalElements - segBase
            : perCoreElements;
    }

    int64_t outPos = 0;
    while (outPos < totalElements) {
        T bestKey = 0;
        bool firstActive = true;
        int32_t bestSeg = -1;
        int64_t bestIdx = 0;
        for (int32_t seg = 0; seg < needCoreNum; seg++) {
            if (segRemaining[seg] == 0) { continue; }
            T curKey = wsSigned[segCursor[seg]];
            bool pick;
            if constexpr (descending) {
                pick = firstActive || (curKey > bestKey);
            } else {
                pick = firstActive || (curKey < bestKey);
            }
            if (pick) {
                bestKey = curKey;
                firstActive = false;
                bestIdx = wsIndicesGm[segCursor[seg]];
                bestSeg = seg;
            }
        }
        if (bestSeg < 0) { break; }
        sortedValuesGm[outPos] = bestKey;
        sortedIndicesGm[outPos] = bestIdx;
        outPos++;
        segCursor[bestSeg]++;
        segRemaining[bestSeg]--;
    }
}

template <typename T, bool descending>
__simt_vf__ __aicore__ __launch_bounds__(THREAD_NUM)
inline void RadixSortMerge2WayParallelKernel(
    int64_t leftElements, int64_t rightElements,
    __gm__ typename RadixSortTrait<T>::SortType* leftKeysGm,
    __gm__ int64_t* leftIdxGm,
    __gm__ typename RadixSortTrait<T>::SortType* rightKeysGm,
    __gm__ int64_t* rightIdxGm,
    __gm__ T* dstValuesGm, __gm__ int64_t* dstIndicesGm,
    __ubuf__ int64_t* segA)
{
    if (threadIdx.x == 0) {
        RADIX_DCCI_INVALIDATE();
    }
    asc_syncthreads();

    uint32_t localTid = threadIdx.x;
    const __gm__ T* leftSigned = reinterpret_cast<const __gm__ T*>(leftKeysGm);
    const __gm__ T* rightSigned = reinterpret_cast<const __gm__ T*>(rightKeysGm);
    int64_t totalOut = leftElements + rightElements;

    // Phase 1: All threads compute co-ranks
    int64_t segSz = (totalOut + THREAD_NUM - 1) / THREAD_NUM;
    if (localTid == 0) {
        segA[0] = 0;
    }
    int64_t k = ((int64_t)localTid + 1) * segSz;
    if (k > totalOut) { k = totalOut; }
    if (k > 0) {
        int64_t low = (k > rightElements) ? (k - rightElements) : 0;
        int64_t high = (k < leftElements) ? k : leftElements;
        while (low < high) {
            int64_t ai = (low + high) / 2;
            int64_t bi = k - ai;
            bool moveRight;
            if constexpr (descending) {
                moveRight = (ai < leftElements) && (bi > 0)
                    && (leftSigned[ai] >= rightSigned[bi - 1]);
            } else {
                moveRight = (ai < leftElements) && (bi > 0)
                    && (leftSigned[ai] <= rightSigned[bi - 1]);
            }
            if (moveRight) { low = ai + 1; } else { high = ai; }
        }
        segA[localTid + 1] = low;
    }
    asc_syncthreads();

    // Phase 2: Each thread merges its segment
    int64_t kStart = localTid * segSz;
    int64_t kEnd = (kStart + segSz < totalOut) ? (kStart + segSz) : totalOut;
    if (kStart >= kEnd) { return; }

    int64_t l = segA[localTid];
    int64_t r = kStart - l;
    int64_t lEnd = segA[localTid + 1];
    int64_t out = kStart;
    while (out < kEnd) {
        bool pickLeft;
        if (r >= rightElements || r >= kEnd - l) {
            pickLeft = true;
        } else if (l >= lEnd) {
            pickLeft = false;
        } else {
            T lkey = leftSigned[l];
            T rkey = rightSigned[r];
            if constexpr (descending) {
                pickLeft = (lkey >= rkey);
            } else {
                pickLeft = (lkey <= rkey);
            }
        }
        if (pickLeft) {
            dstValuesGm[out] = leftSigned[l];
            dstIndicesGm[out] = leftIdxGm[l];
            l++;
        } else {
            dstValuesGm[out] = rightSigned[r];
            dstIndicesGm[out] = rightIdxGm[r];
            r++;
        }
        out++;
    }
}

template <typename T, bool descending>
__simt_vf__ __aicore__ __launch_bounds__(COPY_THREAD_NUM)
inline void RadixSortCopySegmentKernel(
    int64_t elements,
    __gm__ typename RadixSortTrait<T>::SortType* srcKeysGm,
    __gm__ int64_t* srcIdxGm,
    __gm__ T* dstValuesGm, __gm__ int64_t* dstIndicesGm)
{
    if (threadIdx.x == 0) {
        RADIX_DCCI_INVALIDATE();
    }
    asc_syncthreads();
    uint32_t localTid = threadIdx.x;
    uint32_t threadNum = blockDim.x;
    const __gm__ T* srcSigned = reinterpret_cast<const __gm__ T*>(srcKeysGm);
    for (int64_t i = localTid; i < elements; i += threadNum) {
        dstValuesGm[i] = srcSigned[i];
        dstIndicesGm[i] = srcIdxGm[i];
    }
}

} // namespace NsRadixSort

#endif
