/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file cosine_similarity_graph_infer.cpp
 * \brief cosine_similarity operater graph infer resource
 */

#include "register/op_impl_registry.h"
#include "log/log.h"

namespace ops {
using namespace ge;

static constexpr int64_t IDX_0 = 0;

static ge::graphStatus InferDataTypeCosineSimilarity(gert::InferDataTypeContext* context)
{
    OP_LOGD(context->GetNodeName(), "Begin to do InferDataTypeCosineSimilarity");

    // Output dtype follows input dtype. Only float32 is supported.
    ge::DataType x1Dtype = context->GetInputDataType(IDX_0);
    context->SetOutputDataType(IDX_0, x1Dtype);

    OP_LOGD(context->GetNodeName(), "End to do InferDataTypeCosineSimilarity");
    return GRAPH_SUCCESS;
}

IMPL_OP(CosineSimilarity).InferDataType(InferDataTypeCosineSimilarity);

}; // namespace ops
