/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file cosine_similarity_proto.h
 * \brief
 */
#ifndef OPS_OP_PROTO_INC_COSINE_SIMILARITY_H_
#define OPS_OP_PROTO_INC_COSINE_SIMILARITY_H_

#include "graph/operator_reg.h"
#include "graph/types.h"

namespace ge {

/**
*@brief Returns cosine similarity between x1 and x2,computed along dim. \n

*@par Inputs:
*Two inputs, including:
* @li input_x1: A tensor. Must be the following types: float32.
* @li input_x2: A tensor. Must of the following types: float32. \n

* @par Attributes:
* @li dim:The type is Int and the default value is 1.
* @li eps:The type is Float and the default value is 1e-8. \n

*@par Outputs:
* output_y: A ND Tensor with the same dtype of input_x's. \n

*@par Third-party framework compatibility
*Compatible with the PyTorch operator CosineSimilarity. \n
*/
REG_OP(CosineSimilarity)
    .INPUT(input_x1, TensorType({DT_FLOAT}))  /* "First operand." */
    .INPUT(input_x2, TensorType({DT_FLOAT}))  /* "Second operand." */
    .OUTPUT(output_y, TensorType({DT_FLOAT})) /* "Result, has same element type as two inputs" */
    .ATTR(dim, Int, 1)
    .ATTR(eps, Float, 1e-8f)
    .OP_END_FACTORY_REG(CosineSimilarity)

} // namespace ge

#endif // OPS_OP_PROTO_INC_COSINE_SIMILARITY_H_
