/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#include <iostream>
#include <gtest/gtest.h>
#include "tiling_context_faker.h"
#include "tiling_case_executor.h"
#include "../../../../op_kernel/arch35/trace_tiling_data.h"

using namespace std;
using namespace ge;

class TraceTiling : public testing::Test {
protected:
    static void SetUpTestCase() { std::cout << "TraceTiling SetUp" << std::endl; }

    static void TearDownTestCase() { std::cout << "TraceTiling TearDown" << std::endl; }
};

static std::map<std::string, std::string> soc_version_infos = {{"Short_SoC_version", "Ascend950"}};

struct TraceDtypeCase {
    ge::DataType inputDtype;
    ge::DataType outputDtype;
    const char* name;
};

static void ExecuteDtypeTest(ge::DataType inputDtype, ge::DataType outputDtype, ge::graphStatus expectedStatus)
{
    struct TraceCompileInfo {
    } compileInfo;
    gert::TilingContextPara tilingContextPara("Trace",
                                              {
                                                  {{{4, 4}, {4, 4}}, inputDtype, ge::FORMAT_ND},
                                              },
                                              {
                                                  {{{}, {}}, outputDtype, ge::FORMAT_ND},
                                              },
                                              {}, &compileInfo, 1, 262144, 4096);
    if (expectedStatus == ge::GRAPH_SUCCESS) {
        ExecuteTestCase(tilingContextPara, expectedStatus, 0, "4 5 ", {16777216});
        return;
    }
    ExecuteTestCase(tilingContextPara, expectedStatus);
}

TEST_F(TraceTiling, trace_graph_supported_dtypes)
{
    const std::vector<TraceDtypeCase> cases = {
        {ge::DT_COMPLEX64, ge::DT_COMPLEX64, "COMPLEX64"},
        {ge::DT_FLOAT, ge::DT_FLOAT, "FLOAT"},
        {ge::DT_FLOAT16, ge::DT_FLOAT16, "FLOAT16"},
        {ge::DT_BF16, ge::DT_BF16, "BF16"},
        {ge::DT_INT8, ge::DT_INT64, "INT8"},
        {ge::DT_INT16, ge::DT_INT64, "INT16"},
        {ge::DT_INT32, ge::DT_INT64, "INT32"},
        {ge::DT_INT64, ge::DT_INT64, "INT64"},
        {ge::DT_UINT8, ge::DT_INT64, "UINT8"},
        {ge::DT_UINT16, ge::DT_INT64, "UINT16"},
        {ge::DT_UINT32, ge::DT_INT64, "UINT32"},
        {ge::DT_UINT64, ge::DT_UINT64, "UINT64"},
        {ge::DT_BOOL, ge::DT_INT64, "BOOL"},
    };
    for (const auto& testCase : cases) {
        SCOPED_TRACE(testCase.name);
        ExecuteDtypeTest(testCase.inputDtype, testCase.outputDtype, ge::GRAPH_SUCCESS);
    }
}

TEST_F(TraceTiling, trace_rejects_aclnn_only_and_unsupported_dtypes)
{
    const std::vector<TraceDtypeCase> cases = {
        {ge::DT_DOUBLE, ge::DT_DOUBLE, "DOUBLE"},
        {ge::DT_COMPLEX128, ge::DT_COMPLEX128, "COMPLEX128"},
        {ge::DT_STRING, ge::DT_STRING, "STRING"},
    };
    for (const auto& testCase : cases) {
        SCOPED_TRACE(testCase.name);
        ExecuteDtypeTest(testCase.inputDtype, testCase.outputDtype, ge::GRAPH_FAILED);
    }
}

TEST_F(TraceTiling, trace_float32_4x4)
{
    struct TraceCompileInfo {
    } compileInfo;
    gert::TilingContextPara tilingContextPara(
        "Trace",
        {
            {{{4, 4}, {4, 4}}, ge::DT_FLOAT, ge::FORMAT_ND}, // input tensor x (4x4 float32)
        },
        {
            {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND}, // output tensor y (scalar)
        },
        {
            /* attrs - none */
        },
        &compileInfo,
        1,      // number of cores (single core strategy)
        262144, // ub size
        4096);  // max tiling data size
    uint64_t expectTilingKey = 0;
    // diagSize=4, diagStride=5 (N+1=4+1)
    string expectTilingData = "4 5 ";
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}

TEST_F(TraceTiling, trace_float16_8x8)
{
    struct TraceCompileInfo {
    } compileInfo;
    gert::TilingContextPara tilingContextPara(
        "Trace",
        {
            {{{8, 8}, {8, 8}}, ge::DT_FLOAT16, ge::FORMAT_ND}, // input tensor x (8x8 float16)
        },
        {
            {{{}, {}}, ge::DT_FLOAT16, ge::FORMAT_ND}, // output tensor y (scalar)
        },
        {
            /* attrs - none */
        },
        &compileInfo,
        1,      // number of cores
        262144, // ub size
        4096);  // max tiling data size
    uint64_t expectTilingKey = 0;
    // diagSize=8, diagStride=9 (N+1=8+1)
    string expectTilingData = "8 9 ";
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}

TEST_F(TraceTiling, trace_int32_3x5)
{
    struct TraceCompileInfo {
    } compileInfo;
    gert::TilingContextPara tilingContextPara(
        "Trace",
        {
            {{{3, 5}, {3, 5}}, ge::DT_INT32, ge::FORMAT_ND}, // input tensor x (3x5 int32, non-square)
        },
        {
            {{{}, {}}, ge::DT_INT64, ge::FORMAT_ND}, // output tensor y (scalar, int64)
        },
        {
            /* attrs - none */
        },
        &compileInfo,
        1,      // number of cores
        262144, // ub size
        4096);  // max tiling data size
    uint64_t expectTilingKey = 0;
    // diagSize=min(3,5)=3, diagStride=6 (N+1=5+1)
    string expectTilingData = "3 6 ";
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}
