/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file sparse_bincount_tiling.cpp
 * \brief Tiling implementation for sparse_bincount operator.
 *        Grid-Stride over values; two-step core allocation.
 */

#include "log/log.h"
#include "register/op_impl_registry.h"
#include "platform/platform_ascendc.h"
#include "util/math_util.h"
#include "op_host/math_tiling_templates_registry.h"
#include "../../op_kernel/arch35/sparse_bincount_tiling_data.h"
#include "../../op_kernel/arch35/sparse_bincount_tiling_key.h"

namespace optiling {

using namespace Ops::Math::OpTiling;

constexpr int64_t PER_CORE_MIN = 1024;  // Minimum elements per core, aligned to 32
constexpr uint32_t DCACHE_SIZE = 128 * 1024;
constexpr uint32_t STATIC_UB_ESTIMATE = 0;

struct SparseBincountCompileInfo {};

static ge::graphStatus SparseBincountTilingFunc(gert::TilingContext* context)
{
    // 1. Get platform info
    fe::PlatFormInfos* platformInfoPtr = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfoPtr);
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);
    int64_t maxCoreNum = static_cast<int64_t>(ascendcPlatform.GetCoreNumAiv());
    OP_CHECK_IF(maxCoreNum == 0, OP_LOGE(context, "maxCoreNum is 0"), return ge::GRAPH_FAILED);

    uint64_t ubSize = 0;
    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, ubSize);
    OP_CHECK_IF(ubSize == 0, OP_LOGE(context, "ubSize is 0"), return ge::GRAPH_FAILED);

    // 2. Get input shape info
    auto valuesShape = context->GetInputShape(1);    // values: shape (N,)
    OP_CHECK_NULL_WITH_CONTEXT(context, valuesShape);
    int64_t numValues = valuesShape->GetStorageShape().GetShapeSize();

    auto indicesShape = context->GetInputShape(0);   // indices: shape (N, R)
    OP_CHECK_NULL_WITH_CONTEXT(context, indicesShape);
    int64_t indicesColNum = 1;
    if (indicesShape->GetStorageShape().GetDimNum() > 1) {
        indicesColNum = indicesShape->GetStorageShape().GetDim(1);
    }

    auto denseShapeShape = context->GetInputShape(2); // dense_shape: shape (R,)
    OP_CHECK_NULL_WITH_CONTEXT(context, denseShapeShape);
    int64_t denseShapeNum = denseShapeShape->GetStorageShape().GetShapeSize();

    // 3. Get weights shape to determine hasWeights
    auto weightsShape = context->GetInputShape(4);   // weights: shape (N,) or (0,)
    OP_CHECK_NULL_WITH_CONTEXT(context, weightsShape);
    int64_t weightsNum = weightsShape->GetStorageShape().GetShapeSize();
    int32_t hasWeights = (weightsNum > 0) ? 1 : 0;

    // 4. Get binary_output attr
    int32_t binaryOutput = 0;
    const gert::RuntimeAttrs* attrs = context->GetAttrs();
    if (attrs != nullptr) {
        const bool* binaryOutputPtr = attrs->GetBool(0);
        if (binaryOutputPtr != nullptr) {
            binaryOutput = (*binaryOutputPtr) ? 1 : 0;
        }
    }

    // 5. Core allocation (two-step method)
    int64_t perCoreElements = (numValues > 0) ? Ops::Base::CeilDiv(numValues, maxCoreNum) : 0;
    if (perCoreElements > 0 && perCoreElements < PER_CORE_MIN) {
        perCoreElements = PER_CORE_MIN;
    }
    int64_t needCoreNum = (numValues > 0) ? Ops::Base::CeilDiv(numValues, perCoreElements) : 1;

    // 6. Fill tiling data
    auto* tiling = context->GetTilingData<SparseBincountTilingData>();
    OP_CHECK_NULL_WITH_CONTEXT(context, tiling);
    OP_CHECK_IF(
        memset_s(tiling, sizeof(SparseBincountTilingData), 0, sizeof(SparseBincountTilingData)) != EOK,
        OP_LOGE(context, "set tiling data error"), return ge::GRAPH_FAILED);

    tiling->numValues = numValues;
    tiling->indicesColNum = indicesColNum;
    tiling->denseShapeNum = denseShapeNum;

    // 7. Set block dim
    context->SetBlockDim(static_cast<uint32_t>(needCoreNum));

    // 8. Set schedule mode for SyncAll support
    context->SetScheduleMode(1);

    // 9. Set workspace (system workspace for atomic_add)
    uint64_t sysWorkspaceSize = ascendcPlatform.GetLibApiWorkSpaceSize();
    size_t* ws = context->GetWorkspaceSizes(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, ws);
    ws[0] = static_cast<size_t>(sysWorkspaceSize);

    // 10. Set local memory size
    OP_CHECK_IF((ubSize <= DCACHE_SIZE + STATIC_UB_ESTIMATE),
        OP_LOGE(context, "ubSize %lu <= DCACHE_SIZE + STATIC_UB_ESTIMATE", ubSize),
        return ge::GRAPH_FAILED);
    auto res = context->SetLocalMemorySize(static_cast<uint32_t>(ubSize - DCACHE_SIZE - STATIC_UB_ESTIMATE));
    OP_CHECK_IF((res != ge::GRAPH_SUCCESS),
        OP_LOGE(context, "SetLocalMemorySize failed"), return ge::GRAPH_FAILED);

    // 11. Set tiling key (scene mode encoding: is1D * 4 + binaryOutput * 2 + hasWeights)
    int32_t is1D = (denseShapeNum == 1) ? 1 : 0;
    uint32_t schMode = static_cast<uint32_t>(is1D * 4 + binaryOutput * 2 + hasWeights);
    uint64_t tilingKey = GET_TPL_TILING_KEY(schMode);
    context->SetTilingKey(tilingKey);

    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus TilingParseForSparseBincount(gert::TilingParseContext* context)
{
    (void)context;
    return ge::GRAPH_SUCCESS;
}

IMPL_OP_OPTILING(SparseBincount)
    .Tiling(SparseBincountTilingFunc)
    .TilingParse<SparseBincountCompileInfo>(TilingParseForSparseBincount);
}  // namespace optiling
