/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software; you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file atanh_simt.h
 * \brief Atanh operator kernel implementation based on SIMT atanhf
 */
#ifndef ATANH_SIMT_H
#define ATANH_SIMT_H

#include "kernel_operator.h"
#include "kernel_tiling/kernel_tiling.h"
#include "atanh_tiling_data.h"
#include "atanh_tiling_key.h"
#include "simt_api/asc_simt.h"
#include "simt_api/math_functions.h"
#include "simt_api/asc_fp16.h"
#include "simt_api/asc_bf16.h"
#include "simt_api/device_functions.h"

namespace NsAtanh {

using namespace AscendC;

constexpr uint32_t THREAD_NUM = 1024;

template <typename T>
__simt_vf__ __aicore__ LAUNCH_BOUND(THREAD_NUM)
inline void OpAtanhSimtKernel(int64_t totalElements, __gm__ T* x, __gm__ T* y)
{
    // 全程使用 uint64 计算 index/stride，避免 blockIdx*threadNum 在 32-bit 下溢出（大元素数下越界）。
    uint64_t threadNum = static_cast<uint64_t>(Simt::GetThreadNum());
    uint64_t blockNum = static_cast<uint64_t>(Simt::GetBlockNum());
    uint64_t total = static_cast<uint64_t>(totalElements);
    uint64_t stride = threadNum * blockNum;
    for (uint64_t index = static_cast<uint64_t>(Simt::GetBlockIdx()) * threadNum + static_cast<uint64_t>(Simt::GetThreadIdx());
         index < total;
         index += stride) {
        if constexpr (std::is_same_v<T, float>) {
            y[index] = atanhf(x[index]);
        } else if constexpr (std::is_same_v<T, half>) {
            float val = __half2float(x[index]);
            float result = atanhf(val);
            y[index] = __float2half_rn(result);
        } else if constexpr (std::is_same_v<T, bfloat16_t>) {
            float val = __bfloat162float(x[index]);
            float result = atanhf(val);
            y[index] = __float2bfloat16_rn(result);
        }
    }
}

class AtanhSimt {
public:
    __aicore__ inline AtanhSimt() {}

    template <typename T>
    __aicore__ static inline void Process(GM_ADDR x, GM_ADDR y, const AtanhTilingData* tilingData)
    {
        __gm__ T* x_gm = (__gm__ T*) x;
        __gm__ T* y_gm = (__gm__ T*) y;
        Simt::VF_CALL<OpAtanhSimtKernel<T>>(
            Simt::Dim3(THREAD_NUM), tilingData->totalNum, x_gm, y_gm);
    }
};

} // namespace NsAtanh

#endif // ATANH_SIMT_H