/**
 * Copyright (c) 2025-2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file reduce_std_v2_update.h
 * \brief ReduceStdV2Update 算子 kernel 类实现（normal + group 模板共用同一 class）。
 *
 * 数学：
 *   diff = x - mean
 *   sq_sum = Σ(diff²)  沿 dim 归约
 *   var = sq_sum × cof    (cof = 1/(N-correction))
 *   output = sqrt(var) if if_std else var
 *
 * 与 canndev 原型对齐：两遍算法（vsub → vmul → reduce_sum → vmuls(cof) → vsqrt(if_std) → cast），
 *   regbase 框架 post_op 方式（先求和后缩放），数学等价精度更优。
 *
 * 双输入扩展：x + mean 两个 GM tensor，策略 B 并行载入（preIn 并行槽不开 DB）。
 *
 * 几何骨架（normal 模板）：
 *   - aSplit / rSplit 可向外 climb（tiling 阶段算好），UB 内可含多根 A/R 轴
 *   - CopyIn 用 DataCopyPad + LoopMode（loop1/loop2）覆盖最内 4 根 UB 轴；超过 4 根 host for 拆
 *   - 所有 UB 元素数公式统一用 aUbFactorAlign × innerAProdAlign × rUbFactor × innerRProdAlign
 *
 * Reducer 7 参数：
 *   identity=0.0f, combine=Add, pad_value=0, post_op=acc×cof(+sqrt),
 *   empty_r_output_value=0.0f, needs_bisection=true, is_fast_path=true
 *
 * 3 dtype 路径（编译期 if constexpr 分发）：
 *   fp32：     LoadAlign / StoreAlign 直通，无需 Cast
 *   fp16 / bf16：LoadAlign DIST_UNPACK_B16 + Cast→fp32 / fp32→Cast + StoreAlign DIST_PACK_B32
 */
#ifndef OPS_REDUCE_STD_V2_UPDATE_H_
#define OPS_REDUCE_STD_V2_UPDATE_H_

#include "kernel_operator.h"
#include "kernel_tiling/kernel_tiling.h"
#include "adv_api/reduce/reduce.h"
#include "reduce_std_v2_update_tiling_data.h"
#include "reduce_std_v2_update_tiling_key.h"

namespace NsReduceStdV2Update {

using namespace AscendC;

// ─── 常量 ───
constexpr uint32_t kVlBytes = 256;                     // VL = 256B
constexpr uint32_t kRepF32 = kVlBytes / sizeof(float); // = 64
constexpr uint16_t kRepF32U = static_cast<uint16_t>(kRepF32);
constexpr uint32_t kBlockBytes = 32;                        // 32B
constexpr uint32_t kBlockF32 = kBlockBytes / sizeof(float); // = 8

// UB 内一根轴的描述（innermost-first 排列）
struct UBAxisDesc {
    int32_t gmIdx;      // 该轴在 tilingdata.axisShape / axisStride 中的下标
    int64_t ubSize;     // 该轴在 UB 中的有效长度（split 轴为 aLen/rLen，其它为整根 axisShape）
    int64_t paddedSize; // 该轴在 UB 中的占位长度
    int64_t gmStride;   // 该轴在 GM 上的 stride（元素，来自 axisStride）
};

template <typename DType, bool isTailR>
class ReduceStdV2UpdateKernel {
public:
    using D_T = DType;
    using ComputeT = float;

    static constexpr bool kIsFp32 = std::is_same_v<D_T, float>;
    static constexpr bool kIsB16 = (sizeof(D_T) == 2); // fp16 / bf16
    static constexpr bool kNeedCast = !kIsFp32;

    // CastTrait：X → fp32（扩位，硬件不读 sat / round，UNKNOWN + CAST_NONE）
    static constexpr AscendC::Reg::CastTrait kCastTraitToFp32{
        AscendC::Reg::RegLayout::ZERO, AscendC::Reg::SatMode::UNKNOWN, AscendC::Reg::MaskMergeMode::ZEROING,
        AscendC::RoundMode::CAST_NONE};
    // CastTrait：fp32 → X（缩位，BF16/FP16 统一 CAST_RINT，对齐 TBE tbe.round）
    static constexpr AscendC::Reg::CastTrait kCastTraitFromFp32{
        AscendC::Reg::RegLayout::ZERO, AscendC::Reg::SatMode::NO_SAT, AscendC::Reg::MaskMergeMode::ZEROING,
        AscendC::RoundMode::CAST_RINT};

    __aicore__ inline ReduceStdV2UpdateKernel() {}

    __aicore__ inline void Init(GM_ADDR x, GM_ADDR mean, GM_ADDR output, const ReduceStdV2UpdateTilingData* td);
    __aicore__ inline void Process();

    // ─── group 模板（public：供 kernel 入口 <op>.cpp 调用）───
    __aicore__ inline void InitGroup(GM_ADDR x, GM_ADDR mean, GM_ADDR output, GM_ADDR workspace,
                                     const ReduceStdV2UpdateTilingData* td);
    __aicore__ inline void ProcessGroup();

private:
    // ─── 索引解码 ───
    __aicore__ inline void UnravelALoop(int64_t aLoopIdx, int64_t& aSplitChunkIdx, int64_t& chunkGmOff,
                                        int64_t& chunkOutOff);

    // ─── 主流程 ───
    __aicore__ inline void DoOneAChunk(int64_t outerGmOff, int64_t aLen);
    __aicore__ inline void PostElewiseVar(int64_t aLen);
    __aicore__ inline void PostElewiseStd(int64_t aLen);
    __aicore__ inline void CopyOut(int64_t outerOutOff, int64_t aLen);

    // ─── group 模板（内部 helper）───
    __aicore__ inline void Phase1Process();
    __aicore__ inline void Phase2Process();
    __aicore__ inline void DoOneAChunkGroup(int64_t outerGmOff, int64_t aLen, int64_t rStart, int64_t rEnd);
    __aicore__ inline void Phase1OutputToWorkspace(int64_t wsColOff, int64_t aLen, int64_t rChunkIdx, int64_t rCount);

    // ─── CopyIn ───
    __aicore__ inline int32_t BuildUBAxes(int64_t aLen, int64_t rLen, UBAxisDesc out[]);
    __aicore__ inline void DoCopyInTile(GlobalTensor<D_T>& gmBase, int64_t baseGmOff, int64_t aLen, int64_t rLen,
                                        AscendC::LocalTensor<D_T>& preInLocal);

    // ─── VF ───
    __aicore__ inline void PreElewiseSubSquareVf(AscendC::LocalTensor<D_T>& preInX,
                                                 AscendC::LocalTensor<D_T>& preInMean, uint32_t slot);
    __aicore__ inline void ClearChunkExtensionVf(uint32_t slot, int64_t rLen);
    __aicore__ inline void MergeTmpBufVf();
    __aicore__ inline void ReduceRPattern();
    __aicore__ inline void ClearCacheTreeVf();
    __aicore__ inline void DoCachingVf(uint16_t cacheID);

    // ─── 辅助 ───
    __aicore__ inline int32_t LastAAxis() const;
    __aicore__ inline int32_t LastRAxis() const;
    __aicore__ inline int64_t RLenOfChunk(int64_t rChunkIdx) const;
    __aicore__ inline int64_t UnravelOuterR(int64_t rIdx, int64_t& rChunkIdxOut, int64_t& rLenOut) const;
    __aicore__ inline uint16_t GetCacheID(int64_t idx) const;
    __aicore__ inline uint64_t FindNearestPower2(uint64_t v) const;
    __aicore__ inline uint64_t CalLog2(uint64_t v) const;

    // ─── tilingdata 镜像 ───
    int32_t axisNum_ = 0;
    int64_t axisShape_[MAX_PATTERN_RANK] = {0};
    int64_t axisStride_[MAX_PATTERN_RANK] = {0};
    int32_t aSplit_ = 0;
    int32_t rSplit_ = 0;
    int64_t aLoopCntTotal_ = 0;
    int64_t aSplitChunkCnt_ = 0;
    int64_t aBigCoreLoopCnt_ = 0;
    int64_t aSmallCoreLoopCnt_ = 0;
    int32_t aBigCoreCnt_ = 0;
    int32_t usedCoreNum_ = 0;
    int64_t aUbFactor_ = 0;
    int64_t aUbFactorAlign_ = 0;
    int64_t rUbFactor_ = 0;
    int64_t rUbFactorAlign_ = 0;
    int64_t innerAProd_ = 0;
    int64_t innerAProdAlign_ = 0;
    int64_t innerRProd_ = 0;
    int64_t innerRProdAlign_ = 0;
    int64_t rLoopCntTotal_ = 0;
    int64_t bisectionPos_ = 0;
    int64_t bisectionTail_ = 0;
    int64_t cacheCount_ = 0;
    int64_t preReduceUbSize_ = 0;
    int64_t postReduceUbSize_ = 0;
    int64_t tmpSlotElems_ = 0;
    int64_t cacheBufElems_ = 0;
    float cof_ = 0.0f;
    int32_t ifStd_ = 0;

    // 输出端 stride（A 轴 dense 排列）
    int64_t outStride_[MAX_PATTERN_RANK] = {0};

    // ─── GM + UB ───
    GlobalTensor<D_T> xGm_;
    GlobalTensor<D_T> meanGm_;
    GlobalTensor<D_T> outputGm_;
    TPipe pipe_;
    TQue<QuePosition::VECIN, 1> preInXQue_;    // x 输入并行槽（不开 DB）
    TQue<QuePosition::VECIN, 1> preInMeanQue_; // mean 输入并行槽（不开 DB）
    TBuf<QuePosition::VECCALC> tmpBuf_;        // fp32 reduce scratch（2 份主+尾）
    TBuf<QuePosition::VECCALC> cacheBuf_;      // fp32 缓存树（固定 16KB）
    TQue<QuePosition::VECOUT, 1> outQue_;      // 输出（不开 DB）

    // ─── group 模板 ───
    GlobalTensor<float> wsGm_; // workspace GM 基址（fp32）
    int64_t rGroupCnt_ = 0;
    int64_t aTotal_ = 0;        // ∏ 所有 A 轴 axisShape
    int64_t aTotalAligned_ = 0; // aTotal 对齐到 32 字节 (workspace 行宽)
};

// ════════════════════════════════════════════════════════════════════════════
// 工具函数
// ════════════════════════════════════════════════════════════════════════════
template <typename DType, bool isTailR>
__aicore__ inline int32_t ReduceStdV2UpdateKernel<DType, isTailR>::LastAAxis() const
{
    for (int32_t i = axisNum_ - 1; i >= 0; --i) {
        if (i % 2 == 0) {
            return i;
        }
    }
    return 0;
}

template <typename DType, bool isTailR>
__aicore__ inline int32_t ReduceStdV2UpdateKernel<DType, isTailR>::LastRAxis() const
{
    for (int32_t i = axisNum_ - 1; i >= 0; --i) {
        if (i % 2 == 1) {
            return i;
        }
    }
    return 1;
}

template <typename DType, bool isTailR>
__aicore__ inline uint64_t ReduceStdV2UpdateKernel<DType, isTailR>::FindNearestPower2(uint64_t v) const
{
    if (v == 0) {
        return 0;
    }
    if (v <= 2) {
        return 1;
    }
    if (v <= 4) {
        return 2;
    }
    const uint64_t num = v - 1;
    const uint64_t pow = 63 - AscendC::ScalarCountLeadingZero(num);
    return static_cast<uint64_t>(1) << pow;
}

template <typename DType, bool isTailR>
__aicore__ inline uint64_t ReduceStdV2UpdateKernel<DType, isTailR>::CalLog2(uint64_t v) const
{
    uint64_t res = 0;
    while (v > 1) {
        v >>= 1;
        ++res;
    }
    return res;
}

template <typename DType, bool isTailR>
__aicore__ inline uint16_t ReduceStdV2UpdateKernel<DType, isTailR>::GetCacheID(int64_t idx) const
{
    const uint64_t v = static_cast<uint64_t>(idx);
    return static_cast<uint16_t>(AscendC::ScalarGetCountOfValue<1>(v ^ (v + 1)) - 1);
}

template <typename DType, bool isTailR>
__aicore__ inline int64_t ReduceStdV2UpdateKernel<DType, isTailR>::RLenOfChunk(int64_t rChunkIdx) const
{
    const int64_t rAxisSize = axisShape_[rSplit_];
    const int64_t start = rChunkIdx * rUbFactor_;
    return (start + rUbFactor_ > rAxisSize) ? (rAxisSize - start) : rUbFactor_;
}

template <typename DType, bool isTailR>
__aicore__ inline int64_t ReduceStdV2UpdateKernel<DType, isTailR>::UnravelOuterR(int64_t rIdx, int64_t& rChunkIdxOut,
                                                                                 int64_t& rLenOut) const
{
    const int64_t rChunksOnSplit = (axisShape_[rSplit_] + rUbFactor_ - 1) / rUbFactor_;
    rChunkIdxOut = rIdx % rChunksOnSplit;
    int64_t cur = rIdx / rChunksOnSplit;
    int64_t gmOff = 0;
    for (int32_t i = rSplit_ - 1; i >= 0; --i) {
        if (i % 2 == 1) {
            const int64_t sz = axisShape_[i];
            const int64_t ix = cur % sz;
            cur /= sz;
            gmOff += ix * axisStride_[i];
        }
    }
    rLenOut = RLenOfChunk(rChunkIdxOut);
    return gmOff + rChunkIdxOut * rUbFactor_ * axisStride_[rSplit_];
}

// ════════════════════════════════════════════════════════════════════════════
// Init
// ════════════════════════════════════════════════════════════════════════════
template <typename DType, bool isTailR>
__aicore__ inline void ReduceStdV2UpdateKernel<DType, isTailR>::Init(GM_ADDR x, GM_ADDR mean, GM_ADDR output,
                                                                     const ReduceStdV2UpdateTilingData* td)
{
    axisNum_ = td->axisNum;
    for (int32_t i = 0; i < MAX_PATTERN_RANK; ++i) {
        axisShape_[i] = td->axisShape[i];
        axisStride_[i] = td->axisStride[i];
    }
    aSplit_ = td->aSplitAxisIdx;
    rSplit_ = td->rSplitAxisIdx;
    aLoopCntTotal_ = td->aLoopCntTotal;
    aSplitChunkCnt_ = td->aSplitChunkCnt;
    aBigCoreLoopCnt_ = td->aBigCoreLoopCnt;
    aSmallCoreLoopCnt_ = td->aSmallCoreLoopCnt;
    aBigCoreCnt_ = td->aBigCoreCnt;
    usedCoreNum_ = td->usedCoreNum;
    aUbFactor_ = td->aUbFactor;
    aUbFactorAlign_ = td->aUbFactorAlign;
    rUbFactor_ = td->rUbFactor;
    rUbFactorAlign_ = td->rUbFactorAlign;
    innerAProd_ = td->innerAProd;
    innerAProdAlign_ = td->innerAProdAlign;
    innerRProd_ = td->innerRProd;
    innerRProdAlign_ = td->innerRProdAlign;
    rLoopCntTotal_ = td->rLoopCntTotal;
    preReduceUbSize_ = td->preReduceUbSize;
    postReduceUbSize_ = td->postReduceUbSize;
    tmpSlotElems_ = td->tmpBufUbSize / static_cast<int64_t>(sizeof(float));
    cacheBufElems_ = td->cacheBufUbSize / static_cast<int64_t>(sizeof(float));
    cof_ = td->cof;
    ifStd_ = td->ifStd;

    bisectionPos_ = static_cast<int64_t>(FindNearestPower2(static_cast<uint64_t>(rLoopCntTotal_)));
    bisectionTail_ = rLoopCntTotal_ - bisectionPos_;
    cacheCount_ = static_cast<int64_t>(CalLog2(static_cast<uint64_t>(bisectionPos_))) + 1;

    // 输出端 stride：output 上仅 A 轴 dense 排列
    {
        int64_t acc = 1;
        for (int32_t i = axisNum_ - 1; i >= 0; --i) {
            if (i % 2 == 0) {
                outStride_[i] = acc;
                acc *= axisShape_[i];
            }
        }
    }

    xGm_.SetGlobalBuffer(reinterpret_cast<__gm__ D_T*>(x));
    meanGm_.SetGlobalBuffer(reinterpret_cast<__gm__ D_T*>(mean));
    outputGm_.SetGlobalBuffer(reinterpret_cast<__gm__ D_T*>(output));

    // 双输入并行载入（策略 B）：x 和 mean 各一份 preInBuf，不开 DB（depth=1）
    // preReduceUbSize 已含 ×2（x+mean 各一份），每路分配 preReduceUbSize/2
    pipe_.InitBuffer(preInXQue_, /*bufNum=*/1, td->preReduceUbSize / 2);
    pipe_.InitBuffer(preInMeanQue_, /*bufNum=*/1, td->preReduceUbSize / 2);
    pipe_.InitBuffer(tmpBuf_, td->tmpBufUbSize * 2); // N_tmp=2（主+尾）
    pipe_.InitBuffer(cacheBuf_, td->cacheBufUbSize);
    pipe_.InitBuffer(outQue_, /*bufNum=*/1, td->postReduceUbSize);
}

// ────────────────────────────────────────────────────────────────────────────
// UnravelALoop: aLoopIdx → (aSplitChunkIdx, chunkGmOff, chunkOutOff)
// ────────────────────────────────────────────────────────────────────────────
template <typename DType, bool isTailR>
__aicore__ inline void ReduceStdV2UpdateKernel<DType, isTailR>::UnravelALoop(int64_t aLoopIdx, int64_t& aSplitChunkIdx,
                                                                             int64_t& chunkGmOff, int64_t& chunkOutOff)
{
    int64_t rem = aLoopIdx;
    aSplitChunkIdx = rem % aSplitChunkCnt_;
    rem /= aSplitChunkCnt_;

    chunkGmOff = 0;
    chunkOutOff = 0;
    for (int32_t k = aSplit_ - 2; k >= 0; k -= 2) {
        const int64_t sz = axisShape_[k];
        const int64_t ix = rem % sz;
        rem /= sz;
        chunkGmOff += ix * axisStride_[k];
        chunkOutOff += ix * outStride_[k];
    }
}

// ════════════════════════════════════════════════════════════════════════════
// Process: fused aLoop 多核解码
// ════════════════════════════════════════════════════════════════════════════
template <typename DType, bool isTailR>
__aicore__ inline void ReduceStdV2UpdateKernel<DType, isTailR>::Process()
{
    const int64_t blockIdx = static_cast<int64_t>(GetBlockIdx());
    if (blockIdx >= static_cast<int64_t>(usedCoreNum_)) {
        return;
    }

    int64_t aLoopStart;
    int64_t aLoopEnd;
    if (blockIdx < static_cast<int64_t>(aBigCoreCnt_)) {
        aLoopStart = blockIdx * aBigCoreLoopCnt_;
        aLoopEnd = aLoopStart + aBigCoreLoopCnt_;
    } else {
        aLoopStart = static_cast<int64_t>(aBigCoreCnt_) * aBigCoreLoopCnt_ +
                     (blockIdx - static_cast<int64_t>(aBigCoreCnt_)) * aSmallCoreLoopCnt_;
        aLoopEnd = aLoopStart + aSmallCoreLoopCnt_;
    }

    const int64_t aSplitAxisSize = axisShape_[aSplit_];
    const int64_t aSplitStride = axisStride_[aSplit_];
    const int64_t aSplitOutStr = outStride_[aSplit_];

    for (int64_t aLoopIdx = aLoopStart; aLoopIdx < aLoopEnd; ++aLoopIdx) {
        int64_t aSplitChunkIdx;
        int64_t chunkGmOff;
        int64_t chunkOutOff;
        UnravelALoop(aLoopIdx, aSplitChunkIdx, chunkGmOff, chunkOutOff);

        const int64_t aChunkStart = aSplitChunkIdx * aUbFactor_;
        const int64_t aEnd = aChunkStart + aUbFactor_;
        const int64_t aLen = (aEnd > aSplitAxisSize) ? (aSplitAxisSize - aChunkStart) : aUbFactor_;
        if (aLen <= 0) {
            continue;
        }

        chunkGmOff += aChunkStart * aSplitStride;
        chunkOutOff += aChunkStart * aSplitOutStr;

        DoOneAChunk(chunkGmOff, aLen);
        if (ifStd_ != 0) {
            PostElewiseStd(aLen);
        } else {
            PostElewiseVar(aLen);
        }
        CopyOut(chunkOutOff, aLen);
    }
}

// ────────────────────────────────────────────────────────────────────────────
// 单 A chunk 完整流程：清缓存树 → Phase A 配对 → Phase B 单块
// ────────────────────────────────────────────────────────────────────────────
template <typename DType, bool isTailR>
__aicore__ inline void ReduceStdV2UpdateKernel<DType, isTailR>::DoOneAChunk(int64_t outerGmOff, int64_t aLen)
{
    ClearCacheTreeVf();

    // Phase A：主-尾配对
    for (int64_t i = 0; i < bisectionTail_; ++i) {
        // 主块 slot=0：CopyIn x + mean → PreElewise → tmpBuf[0]
        {
            int64_t rChunk = 0, rLen = 0;
            const int64_t rOff = UnravelOuterR(i, rChunk, rLen);
            auto preInX = preInXQue_.AllocTensor<D_T>();
            auto preInMean = preInMeanQue_.AllocTensor<D_T>();
            DoCopyInTile(xGm_, outerGmOff + rOff, aLen, rLen, preInX);
            DoCopyInTile(meanGm_, outerGmOff + rOff, aLen, rLen, preInMean);
            preInXQue_.EnQue(preInX);
            preInMeanQue_.EnQue(preInMean);
            auto deqX = preInXQue_.DeQue<D_T>();
            auto deqMean = preInMeanQue_.DeQue<D_T>();
            PreElewiseSubSquareVf(deqX, deqMean, /*slot=*/0U);
            preInXQue_.FreeTensor(deqX);
            preInMeanQue_.FreeTensor(deqMean);
            if (rLen < rUbFactor_) {
                ClearChunkExtensionVf(0U, rLen);
            }
        }
        // 尾块 slot=1
        {
            int64_t rChunk = 0, rLen = 0;
            const int64_t rOff = UnravelOuterR(i + bisectionPos_, rChunk, rLen);
            auto preInX = preInXQue_.AllocTensor<D_T>();
            auto preInMean = preInMeanQue_.AllocTensor<D_T>();
            DoCopyInTile(xGm_, outerGmOff + rOff, aLen, rLen, preInX);
            DoCopyInTile(meanGm_, outerGmOff + rOff, aLen, rLen, preInMean);
            preInXQue_.EnQue(preInX);
            preInMeanQue_.EnQue(preInMean);
            auto deqX = preInXQue_.DeQue<D_T>();
            auto deqMean = preInMeanQue_.DeQue<D_T>();
            PreElewiseSubSquareVf(deqX, deqMean, /*slot=*/1U);
            preInXQue_.FreeTensor(deqX);
            preInMeanQue_.FreeTensor(deqMean);
            if (rLen < rUbFactor_) {
                ClearChunkExtensionVf(1U, rLen);
            }
        }
        MergeTmpBufVf();
        ReduceRPattern();
        DoCachingVf(GetCacheID(i));
    }
    // Phase B：单块
    for (int64_t i = bisectionTail_; i < bisectionPos_; ++i) {
        int64_t rChunk = 0, rLen = 0;
        const int64_t rOff = UnravelOuterR(i, rChunk, rLen);
        auto preInX = preInXQue_.AllocTensor<D_T>();
        auto preInMean = preInMeanQue_.AllocTensor<D_T>();
        DoCopyInTile(xGm_, outerGmOff + rOff, aLen, rLen, preInX);
        DoCopyInTile(meanGm_, outerGmOff + rOff, aLen, rLen, preInMean);
        preInXQue_.EnQue(preInX);
        preInMeanQue_.EnQue(preInMean);
        auto deqX = preInXQue_.DeQue<D_T>();
        auto deqMean = preInMeanQue_.DeQue<D_T>();
        PreElewiseSubSquareVf(deqX, deqMean, /*slot=*/0U);
        preInXQue_.FreeTensor(deqX);
        preInMeanQue_.FreeTensor(deqMean);
        if (rLen < rUbFactor_) {
            ClearChunkExtensionVf(0U, rLen);
        }
        ReduceRPattern();
        DoCachingVf(GetCacheID(i));
    }
}

// ════════════════════════════════════════════════════════════════════════════
// BuildUBAxes：根据 aSplit/rSplit/isTailR 枚举 UB 内轴（innermost→outermost）
// ════════════════════════════════════════════════════════════════════════════
template <typename DType, bool isTailR>
__aicore__ inline int32_t ReduceStdV2UpdateKernel<DType, isTailR>::BuildUBAxes(int64_t aLen, int64_t rLen,
                                                                               UBAxisDesc out[])
{
    int32_t k = 0;
    const int32_t lastA = LastAAxis();
    const int32_t lastR = LastRAxis();
    const int64_t bsElem = static_cast<int64_t>(kBlockBytes) / static_cast<int64_t>(sizeof(D_T));

    if constexpr (isTailR) {
        // 内 bundle = R bundle（innermost first）
        for (int32_t i = axisNum_ - 1; i >= rSplit_; --i) {
            if (i % 2 != 1) {
                continue;
            }
            int64_t actual;
            int64_t padded;
            if (i == rSplit_) {
                actual = rLen;
                padded = rUbFactorAlign_;
            } else if (i == lastR) {
                actual = axisShape_[i];
                padded = (actual + bsElem - 1) / bsElem * bsElem;
            } else {
                actual = axisShape_[i];
                padded = actual;
            }
            out[k].gmIdx = i;
            out[k].ubSize = actual;
            out[k].paddedSize = padded;
            out[k].gmStride = axisStride_[i];
            ++k;
        }
        // 外 bundle = A bundle
        for (int32_t i = axisNum_ - 1; i >= aSplit_; --i) {
            if (i % 2 != 0) {
                continue;
            }
            int64_t actual;
            int64_t padded;
            if (i == aSplit_) {
                actual = aLen;
                padded = aUbFactor_;
            } else {
                actual = axisShape_[i];
                padded = actual;
            }
            out[k].gmIdx = i;
            out[k].ubSize = actual;
            out[k].paddedSize = padded;
            out[k].gmStride = axisStride_[i];
            ++k;
        }
    } else {
        // 内 bundle = A bundle（innermost first）
        for (int32_t i = axisNum_ - 1; i >= aSplit_; --i) {
            if (i % 2 != 0) {
                continue;
            }
            int64_t actual;
            int64_t padded;
            if (i == aSplit_) {
                actual = aLen;
                padded = (i == lastA) ? aUbFactorAlign_ : aUbFactor_;
            } else if (i == lastA) {
                actual = axisShape_[i];
                padded = (actual + bsElem - 1) / bsElem * bsElem;
            } else {
                actual = axisShape_[i];
                padded = actual;
            }
            out[k].gmIdx = i;
            out[k].ubSize = actual;
            out[k].paddedSize = padded;
            out[k].gmStride = axisStride_[i];
            ++k;
        }
        // 外 bundle = R bundle
        for (int32_t i = axisNum_ - 1; i >= rSplit_; --i) {
            if (i % 2 != 1) {
                continue;
            }
            int64_t actual;
            int64_t padded;
            if (i == rSplit_) {
                actual = rLen;
                padded = rUbFactorAlign_;
            } else {
                actual = axisShape_[i];
                padded = actual;
            }
            out[k].gmIdx = i;
            out[k].ubSize = actual;
            out[k].paddedSize = padded;
            out[k].gmStride = axisStride_[i];
            ++k;
        }
    }
    return k;
}

// ════════════════════════════════════════════════════════════════════════════
// DoCopyInTile：DataCopyPad + LoopMode 把一块 GM tile 装入 preIn
// 双输入：对 x 和 mean 各调一次（同一 baseGmOff，不同 base ptr）
// ════════════════════════════════════════════════════════════════════════════
template <typename DType, bool isTailR>
__aicore__ inline void ReduceStdV2UpdateKernel<DType, isTailR>::DoCopyInTile(GlobalTensor<D_T>& gmBase,
                                                                             int64_t baseGmOff, int64_t aLen,
                                                                             int64_t rLen,
                                                                             AscendC::LocalTensor<D_T>& preInLocal)
{
    UBAxisDesc ubAxes[MAX_PATTERN_RANK];
    const int32_t K = BuildUBAxes(aLen, rLen, ubAxes);

    DataCopyExtParams extParams;
    LoopModeParams loopParams;
    loopParams.loop1Size = 0;
    loopParams.loop1SrcStride = 0;
    loopParams.loop1DstStride = 0;
    loopParams.loop2Size = 0;
    loopParams.loop2SrcStride = 0;
    loopParams.loop2DstStride = 0;

    const int64_t dtBytes = static_cast<int64_t>(sizeof(D_T));
    extParams.blockLen = static_cast<uint32_t>(ubAxes[0].ubSize * dtBytes);

    uint32_t misalign = extParams.blockLen & (kBlockBytes - 1u);
    uint8_t rPad = 0;
    if (misalign != 0) {
        uint32_t gapBytes = kBlockBytes - misalign;
        rPad = static_cast<uint8_t>(gapBytes / static_cast<uint32_t>(dtBytes));
    }
    // Reducer::pad_value=0（sum identity）
    DataCopyPadExtParams<D_T> padParams{true, 0, rPad, static_cast<D_T>(0)};

    const int64_t copyPadBytes = (static_cast<int64_t>(extParams.blockLen) + kBlockBytes - 1) / kBlockBytes *
                                 kBlockBytes;
    const int64_t target0Bytes = ubAxes[0].paddedSize * dtBytes;
    extParams.dstStride = static_cast<uint32_t>((target0Bytes - copyPadBytes) / static_cast<int64_t>(kBlockBytes));

    if (K >= 2) {
        extParams.blockCount = static_cast<uint16_t>(ubAxes[1].ubSize);
        extParams.srcStride = static_cast<uint32_t>(ubAxes[1].gmStride * dtBytes -
                                                    static_cast<int64_t>(extParams.blockLen));
    } else {
        extParams.blockCount = 1;
        extParams.srcStride = 0;
    }

    int64_t ubStride[MAX_PATTERN_RANK];
    ubStride[0] = dtBytes;
    for (int32_t i = 1; i < K; ++i) {
        ubStride[i] = ubStride[i - 1] * ubAxes[i - 1].paddedSize;
    }

    if (K >= 3) {
        loopParams.loop1Size = static_cast<uint32_t>(ubAxes[2].ubSize);
        loopParams.loop1SrcStride = static_cast<uint64_t>(ubAxes[2].gmStride) * static_cast<uint64_t>(dtBytes);
        loopParams.loop1DstStride = static_cast<uint64_t>(ubStride[2]);
        loopParams.loop2Size = 1; // ★ 哪怕外层不用，也必须 ≥ 1
    }
    if (K >= 4) {
        loopParams.loop2Size = static_cast<uint32_t>(ubAxes[3].ubSize);
        loopParams.loop2SrcStride = static_cast<uint64_t>(ubAxes[3].gmStride) * static_cast<uint64_t>(dtBytes);
        loopParams.loop2DstStride = static_cast<uint64_t>(ubStride[3]);
    }

    const bool useLoopMode = (K >= 3);
    // LoopMode 要求 K≥3，否则用 host for 循环：
    //   K∈[3,4] 的 Loop 模式（SetLoopModePara/ResetLoopModePara）仅 Ascend 950 支持；
    //   非 950 平台不支持 LoopMode 硬件特性，须重写 DoCopyInTile 用全 host for 拆所有 K>=3 的轴。
#if __NPU_ARCH__ == 3510
    if (useLoopMode) {
        SetLoopModePara(loopParams, DataCopyMVType::OUT_TO_UB); // ★ 调用前 set
    }

    int64_t outerProd = 1;
    for (int32_t kk = 4; kk < K; ++kk) {
        outerProd *= ubAxes[kk].ubSize;
    }

    for (int64_t outerFlat = 0; outerFlat < outerProd; ++outerFlat) {
        int64_t addGmOffElem = 0;
        int64_t addUbOffBytes = 0;
        int64_t cur = outerFlat;
        for (int32_t kk = 4; kk < K; ++kk) {
            const int64_t sz = ubAxes[kk].ubSize;
            const int64_t ix = cur % sz;
            cur /= sz;
            addGmOffElem += ix * ubAxes[kk].gmStride;
            addUbOffBytes += ix * ubStride[kk];
        }
        const int64_t ubOffElems = addUbOffBytes / dtBytes;
        DataCopyPad(preInLocal[ubOffElems], gmBase[baseGmOff + addGmOffElem], extParams, padParams);
    }

    if (useLoopMode) {
        ResetLoopModePara(DataCopyMVType::OUT_TO_UB); // ★ 调用后 reset，成对出现
    }
#else
#error "非 Ascend950 平台不支持 LoopMode 硬件特性，须重写 DoCopyInTile 用全 host for 拆所有 K>=3 的轴"
#endif
}

// ════════════════════════════════════════════════════════════════════════════
// PreElewiseSubSquareVf：双输入 Cast(b16→fp32) + Sub(x-mean) + Square(diff²)
//   x + mean 同时存活（策略 B 并行载入），结果存 tmpBuf[slot]（fp32）
//   对齐 canndev 原型 tbe.vsub(x, mean) + tbe.vmul(x_sub, x_sub)
// ════════════════════════════════════════════════════════════════════════════
template <typename DType, bool isTailR>
__aicore__ inline void ReduceStdV2UpdateKernel<DType, isTailR>::PreElewiseSubSquareVf(
    AscendC::LocalTensor<D_T>& preInX, AscendC::LocalTensor<D_T>& preInMean, uint32_t slot)
{
    auto tmpAll = tmpBuf_.Get<float>();
    auto tmpSlot = tmpAll[static_cast<int32_t>(slot) * static_cast<int32_t>(tmpSlotElems_)];

    __ubuf__ D_T* xPtr = reinterpret_cast<__ubuf__ D_T*>(preInX.GetPhyAddr());
    __ubuf__ D_T* meanPtr = reinterpret_cast<__ubuf__ D_T*>(preInMean.GetPhyAddr());
    __ubuf__ float* dstPtr = reinterpret_cast<__ubuf__ float*>(tmpSlot.GetPhyAddr());

    const uint32_t totalElems = static_cast<uint32_t>(aUbFactorAlign_ * innerAProdAlign_ * rUbFactorAlign_ *
                                                      innerRProdAlign_);
    const uint16_t repeatTime = static_cast<uint16_t>((totalElems + kRepF32U - 1) / kRepF32U);

    __VEC_SCOPE__
    {
        AscendC::Reg::RegTensor<float> xF32, mF32, diff, sq;
        AscendC::Reg::MaskReg mask;
        uint32_t remaining = totalElems;

        for (uint16_t i = 0; i < repeatTime; ++i) {
            int32_t off = static_cast<int32_t>(i) * static_cast<int32_t>(kRepF32);
            mask = AscendC::Reg::UpdateMask<float>(remaining);

            if constexpr (kIsFp32) {
                // FP32 输入直接 LoadAlign（无需 Cast），D_T=float 时 xPtr/meanPtr 即 __ubuf__ float*
                AscendC::Reg::LoadAlign(xF32, reinterpret_cast<__ubuf__ float*>(xPtr) + off);
                AscendC::Reg::LoadAlign(mF32, reinterpret_cast<__ubuf__ float*>(meanPtr) + off);
            } else {
                // FP16/BF16：LoadAlign DIST_UNPACK_B16 + Cast→fp32
                AscendC::Reg::RegTensor<D_T> xB16, mB16;
                AscendC::Reg::LoadAlign<D_T, AscendC::Reg::LoadDist::DIST_UNPACK_B16>(xB16, xPtr + off);
                AscendC::Reg::LoadAlign<D_T, AscendC::Reg::LoadDist::DIST_UNPACK_B16>(mB16, meanPtr + off);
                AscendC::Reg::Cast<float, D_T, kCastTraitToFp32>(xF32, xB16, mask);
                AscendC::Reg::Cast<float, D_T, kCastTraitToFp32>(mF32, mB16, mask);
            }

            AscendC::Reg::Sub(diff, xF32, mF32, mask); // diff = x - mean
            AscendC::Reg::Mul(sq, diff, diff, mask);   // sq  = diff × diff（square）
            AscendC::Reg::StoreAlign(dstPtr + off, sq, mask);
            remaining = (remaining > kRepF32) ? (remaining - kRepF32) : 0;
        }
    }
}

// ════════════════════════════════════════════════════════════════════════════
// ClearChunkExtensionVf：rSplit 方向 [rLen, rUbFactor) 段填 0.0f（identity）
//   Fast 算子（is_fast_path=true）：pre_elewise(pad_value=0)=0=identity
// ════════════════════════════════════════════════════════════════════════════
template <typename DType, bool isTailR>
__aicore__ inline void ReduceStdV2UpdateKernel<DType, isTailR>::ClearChunkExtensionVf(uint32_t slot, int64_t rLen)
{
    if (rLen >= rUbFactor_) {
        return;
    }

    auto tmpAll = tmpBuf_.Get<float>();
    auto tmpSlot = tmpAll[static_cast<int32_t>(slot) * static_cast<int32_t>(tmpSlotElems_)];
    __ubuf__ float* base = reinterpret_cast<__ubuf__ float*>(tmpSlot.GetPhyAddr());

    if constexpr (isTailR) {
        const uint32_t aBundleEntries = static_cast<uint32_t>(aUbFactorAlign_ * innerAProdAlign_);
        const uint32_t innerRPA = static_cast<uint32_t>(innerRProdAlign_);
        const uint32_t rLenInner = static_cast<uint32_t>(rLen) * innerRPA;
        const uint32_t extStart = (rLenInner + kBlockF32 - 1) / kBlockF32 * kBlockF32;
        const uint32_t aStride = static_cast<uint32_t>(rUbFactorAlign_) * innerRPA;
        if (extStart >= aStride) {
            return;
        }
        const uint32_t extLanes = aStride - extStart;
        const uint32_t repPerA = (extLanes + kRepF32 - 1) / kRepF32;
        const uint16_t aU16 = static_cast<uint16_t>(aBundleEntries);

        __VEC_SCOPE__
        {
            AscendC::Reg::RegTensor<float> idReg;
            AscendC::Reg::Duplicate(idReg, 0.0f); // Reducer::identity=0.0f

            for (uint16_t a = 0; a < aU16; ++a) {
                int32_t aOff = static_cast<int32_t>(a) * static_cast<int32_t>(aStride);
                uint32_t remaining = extLanes;
                for (uint16_t r = 0; r < static_cast<uint16_t>(repPerA); ++r) {
                    int32_t off = aOff + static_cast<int32_t>(extStart) +
                                  static_cast<int32_t>(r) * static_cast<int32_t>(kRepF32);
                    auto mask = AscendC::Reg::UpdateMask<float>(remaining);
                    AscendC::Reg::StoreAlign(base + off, idReg, mask);
                    remaining = (remaining > kRepF32) ? (remaining - kRepF32) : 0;
                }
            }
        }
    } else {
        const uint32_t cellElems = static_cast<uint32_t>(aUbFactorAlign_ * innerAProdAlign_ * innerRProdAlign_);
        const uint32_t startElem = static_cast<uint32_t>(rLen) * cellElems;
        const uint32_t totalClear = (static_cast<uint32_t>(rUbFactor_) - static_cast<uint32_t>(rLen)) * cellElems;
        const uint32_t repCount = (totalClear + kRepF32 - 1) / kRepF32;

        __VEC_SCOPE__
        {
            AscendC::Reg::RegTensor<float> idReg;
            AscendC::Reg::Duplicate(idReg, 0.0f);
            AscendC::Reg::MaskReg mask;
            uint32_t remaining = totalClear;
            for (uint16_t i = 0; i < static_cast<uint16_t>(repCount); ++i) {
                int32_t off = static_cast<int32_t>(startElem) + static_cast<int32_t>(i) * static_cast<int32_t>(kRepF32);
                mask = AscendC::Reg::UpdateMask<float>(remaining);
                AscendC::Reg::StoreAlign(base + off, idReg, mask);
                remaining = (remaining > kRepF32) ? (remaining - kRepF32) : 0;
            }
        }
    }
}

// ════════════════════════════════════════════════════════════════════════════
// MergeTmpBufVf：tmpBuf[0] += tmpBuf[1]（Reducer::combine=Add）
// ════════════════════════════════════════════════════════════════════════════
template <typename DType, bool isTailR>
__aicore__ inline void ReduceStdV2UpdateKernel<DType, isTailR>::MergeTmpBufVf()
{
    auto tmpAll = tmpBuf_.Get<float>();
    __ubuf__ float* p0 = reinterpret_cast<__ubuf__ float*>(tmpAll.GetPhyAddr());
    __ubuf__ float* p1 = p0 + tmpSlotElems_;

    const uint32_t totalElems = static_cast<uint32_t>(aUbFactorAlign_ * innerAProdAlign_ * rUbFactorAlign_ *
                                                      innerRProdAlign_);
    const uint16_t repeatTime = static_cast<uint16_t>((totalElems + kRepF32U - 1) / kRepF32U);

    __VEC_SCOPE__
    {
        AscendC::Reg::RegTensor<float> aReg, bReg;
        AscendC::Reg::MaskReg mask;
        uint32_t remaining = totalElems;
        for (uint16_t i = 0; i < repeatTime; ++i) {
            int32_t off = static_cast<int32_t>(i) * static_cast<int32_t>(kRepF32);
            mask = AscendC::Reg::UpdateMask<float>(remaining);
            AscendC::Reg::LoadAlign(aReg, p0 + off);
            AscendC::Reg::LoadAlign(bReg, p1 + off);
            AscendC::Reg::Add(aReg, aReg, bReg, mask);
            AscendC::Reg::StoreAlign(p0 + off, aReg, mask);
            remaining = (remaining > kRepF32) ? (remaining - kRepF32) : 0;
        }
    }
}

// ════════════════════════════════════════════════════════════════════════════
// ReduceRPattern：AscendC::ReduceSum<fp32, AR/RA>
//   src = tmpBuf[0]，dst = tmpBuf[1]（src/dst 不可重叠，isReuseSource=true）
// ════════════════════════════════════════════════════════════════════════════
template <typename DType, bool isTailR>
__aicore__ inline void ReduceStdV2UpdateKernel<DType, isTailR>::ReduceRPattern()
{
    auto tmpAll = tmpBuf_.Get<float>();
    auto src = tmpAll;
    auto dst = tmpAll[static_cast<int32_t>(tmpSlotElems_)];

    const uint32_t aBundle = static_cast<uint32_t>(aUbFactorAlign_ * innerAProdAlign_);
    const uint32_t rBundle = static_cast<uint32_t>(rUbFactorAlign_ * innerRProdAlign_);

    if constexpr (isTailR) {
        uint32_t srcShape[2] = {aBundle, rBundle};
        AscendC::ReduceSum<float, AscendC::Pattern::Reduce::AR, /*isReuseSource=*/true>(dst, src, srcShape,
                                                                                        /*srcInnerPad=*/true);
    } else {
        uint32_t srcShape[2] = {rBundle, aBundle};
        AscendC::ReduceSum<float, AscendC::Pattern::Reduce::RA, /*isReuseSource=*/true>(dst, src, srcShape,
                                                                                        /*srcInnerPad=*/true);
    }
}

// ════════════════════════════════════════════════════════════════════════════
// ClearCacheTreeVf：整个 cacheBuf 清 0（Reducer::identity=0.0f）
// ════════════════════════════════════════════════════════════════════════════
template <typename DType, bool isTailR>
__aicore__ inline void ReduceStdV2UpdateKernel<DType, isTailR>::ClearCacheTreeVf()
{
    __ubuf__ float* base = reinterpret_cast<__ubuf__ float*>(cacheBuf_.Get<float>().GetPhyAddr());
    const uint32_t totalElems = static_cast<uint32_t>(cacheBufElems_);
    const uint16_t repeatTime = static_cast<uint16_t>((totalElems + kRepF32U - 1) / kRepF32U);

    __VEC_SCOPE__
    {
        AscendC::Reg::RegTensor<float> zReg;
        AscendC::Reg::Duplicate(zReg, 0.0f);
        AscendC::Reg::MaskReg mask;
        uint32_t remaining = totalElems;
        for (uint16_t i = 0; i < repeatTime; ++i) {
            int32_t off = static_cast<int32_t>(i) * static_cast<int32_t>(kRepF32);
            mask = AscendC::Reg::UpdateMask<float>(remaining);
            AscendC::Reg::StoreAlign(base + off, zReg, mask);
            remaining = (remaining > kRepF32) ? (remaining - kRepF32) : 0;
        }
    }
}

// ════════════════════════════════════════════════════════════════════════════
// DoCachingVf：ReduceSum 结果（tmpBuf[1] 前 laneN 个 fp32）→ 缓存树 level cacheID
//   combine=Reg::Add
// ════════════════════════════════════════════════════════════════════════════
template <typename DType, bool isTailR>
__aicore__ inline void ReduceStdV2UpdateKernel<DType, isTailR>::DoCachingVf(uint16_t cacheID)
{
    auto tmpAll = tmpBuf_.Get<float>();
    __ubuf__ float* srcPtr = reinterpret_cast<__ubuf__ float*>(
        tmpAll[static_cast<int32_t>(tmpSlotElems_)].GetPhyAddr());
    __ubuf__ float* cachePtr = reinterpret_cast<__ubuf__ float*>(cacheBuf_.Get<float>().GetPhyAddr());

    const uint32_t laneN = static_cast<uint32_t>(aUbFactorAlign_ * innerAProdAlign_);
    const uint32_t levelStride = (laneN + kBlockF32 - 1) / kBlockF32 * kBlockF32;
    const int32_t levelOff = static_cast<int32_t>(cacheID) * static_cast<int32_t>(levelStride);
    const uint16_t repeatTime = static_cast<uint16_t>((laneN + kRepF32U - 1) / kRepF32U);
    const uint16_t cacheLvlU16 = cacheID;

    __VEC_SCOPE__
    {
        AscendC::Reg::RegTensor<float> aReg, bReg;
        AscendC::Reg::MaskReg mask;
        uint32_t remaining = laneN;
        for (uint16_t i = 0; i < repeatTime; ++i) {
            int32_t off = static_cast<int32_t>(i) * static_cast<int32_t>(kRepF32);
            mask = AscendC::Reg::UpdateMask<float>(remaining);

            AscendC::Reg::LoadAlign(aReg, srcPtr + off);

            for (uint16_t j = 0; j < cacheLvlU16; ++j) {
                int32_t jOff = static_cast<int32_t>(j) * static_cast<int32_t>(levelStride) + off;
                AscendC::Reg::LoadAlign(bReg, cachePtr + jOff);
                AscendC::Reg::Add(aReg, aReg, bReg, mask);
            }
            AscendC::Reg::StoreAlign(cachePtr + levelOff + off, aReg, mask);
            remaining = (remaining > kRepF32) ? (remaining - kRepF32) : 0;
        }
    }
}

// ════════════════════════════════════════════════════════════════════════════
// PostElewiseVar：输出方差（if_std=false），不调 Sqrt
//   post_op: var = sq_sum × cof → Cast fp32→D_T
// ════════════════════════════════════════════════════════════════════════════
template <typename DType, bool isTailR>
__aicore__ inline void ReduceStdV2UpdateKernel<DType, isTailR>::PostElewiseVar(int64_t aLen)
{
    const uint32_t laneN = static_cast<uint32_t>(aUbFactorAlign_ * innerAProdAlign_);
    const uint32_t levelStride = (laneN + kBlockF32 - 1) / kBlockF32 * kBlockF32;
    const int32_t rootOff = static_cast<int32_t>(cacheCount_ - 1) * static_cast<int32_t>(levelStride);

    __ubuf__ float* rootPtr = reinterpret_cast<__ubuf__ float*>(cacheBuf_.Get<float>().GetPhyAddr()) + rootOff;

    auto outLocal = outQue_.AllocTensor<D_T>();
    __ubuf__ D_T* outPtr = reinterpret_cast<__ubuf__ D_T*>(outLocal.GetPhyAddr());

    const uint16_t repeatTime = static_cast<uint16_t>((laneN + kRepF32U - 1) / kRepF32U);

    __VEC_SCOPE__
    {
        AscendC::Reg::RegTensor<float> f32Reg;
        AscendC::Reg::MaskReg mask;
        uint32_t remaining = laneN;
        for (uint16_t i = 0; i < repeatTime; ++i) {
            int32_t off = static_cast<int32_t>(i) * static_cast<int32_t>(kRepF32);
            mask = AscendC::Reg::UpdateMask<float>(remaining);

            AscendC::Reg::LoadAlign(f32Reg, rootPtr + off);
            AscendC::Reg::Muls(f32Reg, f32Reg, cof_, mask); // post_op: var = sq_sum × cof

            if constexpr (kIsFp32) {
                AscendC::Reg::StoreAlign(outPtr + off, f32Reg, mask);
            } else {
                AscendC::Reg::RegTensor<D_T> b16Reg;
                AscendC::Reg::Cast<D_T, float, kCastTraitFromFp32>(b16Reg, f32Reg, mask);
                AscendC::Reg::StoreAlign<D_T, AscendC::Reg::StoreDist::DIST_PACK_B32>(outPtr + off, b16Reg, mask);
            }
            remaining = (remaining > kRepF32) ? (remaining - kRepF32) : 0;
        }
    }
    outQue_.EnQue(outLocal);
}

// ════════════════════════════════════════════════════════════════════════════
// PostElewiseStd：输出标准差（if_std=true），Sqrt 前 max(var,0) 保护
//   post_op: var = sq_sum × cof → max(var,0) → Sqrt → Cast fp32→D_T
// ════════════════════════════════════════════════════════════════════════════
template <typename DType, bool isTailR>
__aicore__ inline void ReduceStdV2UpdateKernel<DType, isTailR>::PostElewiseStd(int64_t aLen)
{
    const uint32_t laneN = static_cast<uint32_t>(aUbFactorAlign_ * innerAProdAlign_);
    const uint32_t levelStride = (laneN + kBlockF32 - 1) / kBlockF32 * kBlockF32;
    const int32_t rootOff = static_cast<int32_t>(cacheCount_ - 1) * static_cast<int32_t>(levelStride);

    __ubuf__ float* rootPtr = reinterpret_cast<__ubuf__ float*>(cacheBuf_.Get<float>().GetPhyAddr()) + rootOff;

    auto outLocal = outQue_.AllocTensor<D_T>();
    __ubuf__ D_T* outPtr = reinterpret_cast<__ubuf__ D_T*>(outLocal.GetPhyAddr());

    const uint16_t repeatTime = static_cast<uint16_t>((laneN + kRepF32U - 1) / kRepF32U);

    __VEC_SCOPE__
    {
        AscendC::Reg::RegTensor<float> f32Reg, zeroReg;
        AscendC::Reg::MaskReg mask;
        uint32_t remaining = laneN;
        for (uint16_t i = 0; i < repeatTime; ++i) {
            int32_t off = static_cast<int32_t>(i) * static_cast<int32_t>(kRepF32);
            mask = AscendC::Reg::UpdateMask<float>(remaining);

            AscendC::Reg::LoadAlign(f32Reg, rootPtr + off);
            AscendC::Reg::Muls(f32Reg, f32Reg, cof_, mask); // post_op: var = sq_sum × cof
            AscendC::Reg::Duplicate(zeroReg, 0.0f);
            AscendC::Reg::Max(f32Reg, f32Reg, zeroReg, mask); // max(var,0) 保护（fp32 累加可能产生 -1e-7 级微小负值）
            AscendC::Reg::Sqrt(f32Reg, f32Reg, mask); // std = sqrt(var)

            if constexpr (kIsFp32) {
                AscendC::Reg::StoreAlign(outPtr + off, f32Reg, mask);
            } else {
                AscendC::Reg::RegTensor<D_T> b16Reg;
                AscendC::Reg::Cast<D_T, float, kCastTraitFromFp32>(b16Reg, f32Reg, mask);
                AscendC::Reg::StoreAlign<D_T, AscendC::Reg::StoreDist::DIST_PACK_B32>(outPtr + off, b16Reg, mask);
            }
            remaining = (remaining > kRepF32) ? (remaining - kRepF32) : 0;
        }
    }
    outQue_.EnQue(outLocal);
}

// ════════════════════════════════════════════════════════════════════════════
// CopyOut：DeQue → DataCopyPad → FreeTensor
// 三条路径按 isTailR/aSplit 选择
// ════════════════════════════════════════════════════════════════════════════
template <typename DType, bool isTailR>
__aicore__ inline void ReduceStdV2UpdateKernel<DType, isTailR>::CopyOut(int64_t outerOutOff, int64_t aLen)
{
    auto outDeq = outQue_.DeQue<D_T>();
    DataCopyExtParams outParams;
    if constexpr (isTailR) {
        // 路径 1：tail-R，单 burst
        outParams.blockLen = static_cast<uint32_t>(aLen * innerAProd_ * static_cast<int64_t>(sizeof(D_T)));
        outParams.blockCount = 1;
    } else {
        const int32_t lastA = LastAAxis();
        const int64_t lastASize = axisShape_[lastA];
        if (aSplit_ == lastA) {
            // 路径 2：tail-A + aSplit==LastA，单 burst
            outParams.blockLen = static_cast<uint32_t>(aLen * static_cast<int64_t>(sizeof(D_T)));
            outParams.blockCount = 1;
        } else {
            // 路径 3：tail-A + aSplit!=LastA，多 burst
            outParams.blockLen = static_cast<uint32_t>(lastASize * static_cast<int64_t>(sizeof(D_T)));
            outParams.blockCount = static_cast<uint16_t>(aLen * innerAProd_ / lastASize);
        }
    }
    outParams.srcStride = 0;
    outParams.dstStride = 0;
    DataCopyPad(outputGm_[outerOutOff], outDeq, outParams);
    outQue_.FreeTensor(outDeq);
}

// ════════════════════════════════════════════════════════════════════════════
// Group 模板：A×R 2D 分核 Phase 1 → SyncAll → Phase 2 RA mini-kernel
// ════════════════════════════════════════════════════════════════════════════
template <typename DType, bool isTailR>
__aicore__ inline void ReduceStdV2UpdateKernel<DType, isTailR>::InitGroup(GM_ADDR x, GM_ADDR mean, GM_ADDR output,
                                                                          GM_ADDR workspace,
                                                                          const ReduceStdV2UpdateTilingData* td)
{
    Init(x, mean, output, td); // 复用 normal 全套 UB/字段初始化
    wsGm_.SetGlobalBuffer(reinterpret_cast<__gm__ float*>(workspace));
    rGroupCnt_ = td->rGroupCnt;

    aTotal_ = 1;
    for (int32_t i = 0; i < axisNum_; i += 2) {
        aTotal_ *= axisShape_[i];
    }
    // workspace 行宽对齐到 32 字节 (DataCopyPad 要求 GM 地址 32 字节对齐)
    aTotalAligned_ = (aTotal_ * static_cast<int64_t>(sizeof(float)) + static_cast<int64_t>(kBlockBytes) - 1) /
                     static_cast<int64_t>(kBlockBytes) * static_cast<int64_t>(kBlockBytes) /
                     static_cast<int64_t>(sizeof(float));
}

template <typename DType, bool isTailR>
__aicore__ inline void ReduceStdV2UpdateKernel<DType, isTailR>::ProcessGroup()
{
    Phase1Process();
    SyncAll();
    Phase2Process();
}

// ────────────────────────────────────────────────────────────────────────────
// Phase1Process: 2D 坐标计算 + 局部 R 段 reduce + 写 workspace
// ────────────────────────────────────────────────────────────────────────────
template <typename DType, bool isTailR>
__aicore__ inline void ReduceStdV2UpdateKernel<DType, isTailR>::Phase1Process()
{
    int64_t blockIdx = static_cast<int64_t>(GetBlockIdx());
    if (blockIdx >= static_cast<int64_t>(usedCoreNum_)) {
        return;
    }

    const int64_t aOuter = aLoopCntTotal_;
    const int64_t rOuter = rLoopCntTotal_;

    int64_t aChunkIdx = blockIdx / rGroupCnt_;
    int64_t rChunkIdx = blockIdx % rGroupCnt_;

    int64_t rPerCore = (rOuter + rGroupCnt_ - 1) / rGroupCnt_;
    int64_t rStart = rChunkIdx * rPerCore;
    int64_t rEnd = rStart + rPerCore;
    if (rEnd > rOuter) {
        rEnd = rOuter;
    }
    if (rStart >= rOuter) {
        return;
    }

    int64_t aLoopIdx = aChunkIdx;

    int64_t aSplitChunkIdx;
    int64_t chunkGmOff;
    int64_t chunkOutOff;
    UnravelALoop(aLoopIdx, aSplitChunkIdx, chunkGmOff, chunkOutOff);

    const int64_t aSplitAxisSize = axisShape_[aSplit_];
    const int64_t aSplitStride = axisStride_[aSplit_];
    const int64_t aSplitOutStr = outStride_[aSplit_];
    const int64_t aChunkStart = aSplitChunkIdx * aUbFactor_;
    const int64_t aEndVal = aChunkStart + aUbFactor_;
    const int64_t aLen = (aEndVal > aSplitAxisSize) ? (aSplitAxisSize - aChunkStart) : aUbFactor_;
    if (aLen <= 0) {
        return;
    }

    chunkGmOff += aChunkStart * aSplitStride;
    chunkOutOff += aChunkStart * aSplitOutStr;

    int64_t rCount = rEnd - rStart;

    DoOneAChunkGroup(chunkGmOff, aLen, rStart, rEnd);
    Phase1OutputToWorkspace(chunkOutOff, aLen, rChunkIdx, rCount);
}

template <typename DType, bool isTailR>
__aicore__ inline void ReduceStdV2UpdateKernel<DType, isTailR>::DoOneAChunkGroup(int64_t outerGmOff, int64_t aLen,
                                                                                 int64_t rStart, int64_t rEnd)
{
    int64_t rCount = rEnd - rStart;
    if (rCount <= 0) {
        return;
    }

    int64_t bisectionPos = static_cast<int64_t>(FindNearestPower2(static_cast<uint64_t>(rCount)));
    int64_t bisectionTail = rCount - bisectionPos;

    ClearCacheTreeVf();

    // Phase A: 主-尾配对
    for (int64_t i = 0; i < bisectionTail; ++i) {
        {
            int64_t rChunk = 0, rLen = 0;
            const int64_t rOff = UnravelOuterR(rStart + i, rChunk, rLen);
            auto preInX = preInXQue_.AllocTensor<D_T>();
            auto preInMean = preInMeanQue_.AllocTensor<D_T>();
            DoCopyInTile(xGm_, outerGmOff + rOff, aLen, rLen, preInX);
            DoCopyInTile(meanGm_, outerGmOff + rOff, aLen, rLen, preInMean);
            preInXQue_.EnQue(preInX);
            preInMeanQue_.EnQue(preInMean);
            auto deqX = preInXQue_.DeQue<D_T>();
            auto deqMean = preInMeanQue_.DeQue<D_T>();
            PreElewiseSubSquareVf(deqX, deqMean, 0U);
            preInXQue_.FreeTensor(deqX);
            preInMeanQue_.FreeTensor(deqMean);
            if (rLen < rUbFactor_) {
                ClearChunkExtensionVf(0U, rLen);
            }
        }
        {
            int64_t rChunk = 0, rLen = 0;
            const int64_t rOff = UnravelOuterR(rStart + i + bisectionPos, rChunk, rLen);
            auto preInX = preInXQue_.AllocTensor<D_T>();
            auto preInMean = preInMeanQue_.AllocTensor<D_T>();
            DoCopyInTile(xGm_, outerGmOff + rOff, aLen, rLen, preInX);
            DoCopyInTile(meanGm_, outerGmOff + rOff, aLen, rLen, preInMean);
            preInXQue_.EnQue(preInX);
            preInMeanQue_.EnQue(preInMean);
            auto deqX = preInXQue_.DeQue<D_T>();
            auto deqMean = preInMeanQue_.DeQue<D_T>();
            PreElewiseSubSquareVf(deqX, deqMean, 1U);
            preInXQue_.FreeTensor(deqX);
            preInMeanQue_.FreeTensor(deqMean);
            if (rLen < rUbFactor_) {
                ClearChunkExtensionVf(1U, rLen);
            }
        }
        MergeTmpBufVf();
        ReduceRPattern();
        DoCachingVf(GetCacheID(i));
    }

    // Phase B: 单块
    for (int64_t i = bisectionTail; i < bisectionPos; ++i) {
        int64_t rChunk = 0, rLen = 0;
        const int64_t rOff = UnravelOuterR(rStart + i, rChunk, rLen);
        auto preInX = preInXQue_.AllocTensor<D_T>();
        auto preInMean = preInMeanQue_.AllocTensor<D_T>();
        DoCopyInTile(xGm_, outerGmOff + rOff, aLen, rLen, preInX);
        DoCopyInTile(meanGm_, outerGmOff + rOff, aLen, rLen, preInMean);
        preInXQue_.EnQue(preInX);
        preInMeanQue_.EnQue(preInMean);
        auto deqX = preInXQue_.DeQue<D_T>();
        auto deqMean = preInMeanQue_.DeQue<D_T>();
        PreElewiseSubSquareVf(deqX, deqMean, 0U);
        preInXQue_.FreeTensor(deqX);
        preInMeanQue_.FreeTensor(deqMean);
        if (rLen < rUbFactor_) {
            ClearChunkExtensionVf(0U, rLen);
        }
        ReduceRPattern();
        DoCachingVf(GetCacheID(i));
    }
}

template <typename DType, bool isTailR>
__aicore__ inline void ReduceStdV2UpdateKernel<DType, isTailR>::Phase1OutputToWorkspace(int64_t wsColOff, int64_t aLen,
                                                                                        int64_t rChunkIdx,
                                                                                        int64_t rCount)
{
    int64_t bisectionPos = static_cast<int64_t>(FindNearestPower2(static_cast<uint64_t>(rCount)));
    int64_t cacheCount = static_cast<int64_t>(CalLog2(static_cast<uint64_t>(bisectionPos))) + 1;
    int64_t laneN = aUbFactorAlign_ * innerAProdAlign_;
    int64_t levelStride = (laneN + kBlockF32 - 1) / kBlockF32 * kBlockF32;
    int64_t rootOff = (cacheCount - 1) * levelStride;

    // PipeV → MTE3 fence
    event_t eventIdVToMte3 = static_cast<event_t>(GetTPipePtr()->FetchEventID(HardEvent::V_MTE3));
    SetFlag<HardEvent::V_MTE3>(eventIdVToMte3);
    WaitFlag<HardEvent::V_MTE3>(eventIdVToMte3);

    auto cacheLocal = cacheBuf_.Get<float>();

    DataCopyExtParams ext;
    if constexpr (isTailR) {
        ext.blockLen = static_cast<uint32_t>(aLen * innerAProd_ * static_cast<int64_t>(sizeof(float)));
        ext.blockCount = 1;
        ext.srcStride = 0;
    } else {
        const int32_t lastA = LastAAxis();
        const int64_t lastASize = axisShape_[lastA];
        if (aSplit_ == lastA) {
            ext.blockLen = static_cast<uint32_t>(aLen * static_cast<int64_t>(sizeof(float)));
            ext.blockCount = 1;
            ext.srcStride = 0;
        } else {
            int64_t bsElem = kBlockBytes / static_cast<int64_t>(sizeof(float));
            int64_t lastASizeAlign = ((lastASize + bsElem - 1) / bsElem) * bsElem;
            ext.blockLen = static_cast<uint32_t>(lastASize * static_cast<int64_t>(sizeof(float)));
            ext.blockCount = static_cast<uint16_t>(aLen * innerAProd_ / lastASize);
            ext.srcStride = (lastASizeAlign - lastASize) * static_cast<int64_t>(sizeof(float)) / kBlockBytes;
        }
    }
    ext.dstStride = 0;

    int64_t wsOff = rChunkIdx * aTotalAligned_ + wsColOff;
    DataCopyPad(wsGm_[wsOff], cacheLocal[rootOff], ext);
}

// ────────────────────────────────────────────────────────────────────────────
// Phase2Process: RA mini-kernel
//   workspace → CopyIn(R 全载 rGroupCnt) → ReduceSum<RA> → PostElewise → CopyOut
// ────────────────────────────────────────────────────────────────────────────
template <typename DType, bool isTailR>
__aicore__ inline void ReduceStdV2UpdateKernel<DType, isTailR>::Phase2Process()
{
    int64_t blockIdx = static_cast<int64_t>(GetBlockIdx());

    const int64_t preInElems = preReduceUbSize_ / static_cast<int64_t>(sizeof(float));
    constexpr int64_t BS_FP32 = 32 / static_cast<int64_t>(sizeof(float));

    int64_t aUbFactorP2 = preInElems / rGroupCnt_;
    if (aUbFactorP2 >= BS_FP32) {
        aUbFactorP2 = (aUbFactorP2 / BS_FP32) * BS_FP32;
    }
    {
        int64_t limit1 = postReduceUbSize_ / static_cast<int64_t>(sizeof(D_T));
        aUbFactorP2 = (aUbFactorP2 < limit1) ? aUbFactorP2 : limit1;
        aUbFactorP2 = (aUbFactorP2 < tmpSlotElems_) ? aUbFactorP2 : tmpSlotElems_;
        aUbFactorP2 = (aUbFactorP2 < aTotal_) ? aUbFactorP2 : aTotal_;
    }

    const int64_t aSplitChunkCntP2 = (aTotal_ + aUbFactorP2 - 1) / aUbFactorP2;
    const int64_t aLoopCntTotalP2 = aSplitChunkCntP2;

    const int64_t aSmallCoreLoopCntP2 = aLoopCntTotalP2 / usedCoreNum_;
    const int64_t aBigCoreCntP2 = aLoopCntTotalP2 % usedCoreNum_;
    const int64_t aBigCoreLoopCntP2 = aSmallCoreLoopCntP2 + (aBigCoreCntP2 > 0 ? 1 : 0);
    const int64_t usedCoreNumP2 = (aSmallCoreLoopCntP2 > 0) ? usedCoreNum_ : aBigCoreCntP2;
    if (blockIdx >= usedCoreNumP2) {
        return;
    }

    int64_t aLoopStart, aLoopEnd;
    if (blockIdx < aBigCoreCntP2) {
        aLoopStart = blockIdx * aBigCoreLoopCntP2;
        aLoopEnd = aLoopStart + aBigCoreLoopCntP2;
    } else {
        aLoopStart = aBigCoreCntP2 * aBigCoreLoopCntP2 + (blockIdx - aBigCoreCntP2) * aSmallCoreLoopCntP2;
        aLoopEnd = aLoopStart + aSmallCoreLoopCntP2;
    }

    for (int64_t aLoopIdx = aLoopStart; aLoopIdx < aLoopEnd; ++aLoopIdx) {
        int64_t aSplitChunkIdx = aLoopIdx;
        int64_t a_off = aSplitChunkIdx * aUbFactorP2;
        int64_t a_len = aUbFactorP2;
        if (a_off + a_len > aTotal_) {
            a_len = aTotal_ - a_off;
        }
        int64_t a_len_ub = ((a_len + BS_FP32 - 1) / BS_FP32) * BS_FP32;

        // CopyIn workspace → preInBuf（复用 Phase 1 preIn 槽，fp32）
        auto preInLocal = preInXQue_.AllocTensor<float>();
        {
            DataCopyExtParams ext;
            ext.blockLen = static_cast<uint32_t>(a_len * static_cast<int64_t>(sizeof(float)));
            ext.blockCount = static_cast<uint16_t>(rGroupCnt_);
            ext.srcStride = static_cast<uint32_t>(aTotalAligned_ * static_cast<int64_t>(sizeof(float)) -
                                                  static_cast<int64_t>(ext.blockLen));
            ext.dstStride = 0;
            DataCopyPadExtParams<float> padParams{true, 0, static_cast<uint8_t>(a_len_ub - a_len), 0.0f};
            DataCopyPad(preInLocal, wsGm_[a_off], ext, padParams);
        }
        preInXQue_.EnQue(preInLocal);
        auto preInDeq = preInXQue_.DeQue<float>();

        // ReduceSum<fp32, RA, srcInnerPad=true>
        {
            auto tmpAll = tmpBuf_.Get<float>();
            uint32_t srcShape[2] = {static_cast<uint32_t>(rGroupCnt_), static_cast<uint32_t>(a_len_ub)};
            ReduceSum<float, AscendC::Pattern::Reduce::RA, true>(tmpAll, preInDeq, srcShape, true);
        }
        preInXQue_.FreeTensor(preInDeq);

        // PostElewise + CopyOut
        {
            auto tmpSrc = tmpBuf_.Get<float>();
            auto outLocal = outQue_.AllocTensor<D_T>();
            __ubuf__ float* srcPtr = reinterpret_cast<__ubuf__ float*>(tmpSrc.GetPhyAddr());
            __ubuf__ D_T* dstPtr = reinterpret_cast<__ubuf__ D_T*>(outLocal.GetPhyAddr());

            const uint16_t repeatTime = static_cast<uint16_t>((static_cast<uint32_t>(a_len) + kRepF32U - 1) / kRepF32U);

            __VEC_SCOPE__
            {
                AscendC::Reg::RegTensor<float> f32Reg, zeroReg;
                AscendC::Reg::MaskReg mask;
                uint32_t remaining = static_cast<uint32_t>(a_len);
                for (uint16_t i = 0; i < repeatTime; ++i) {
                    int32_t off = static_cast<int32_t>(i) * static_cast<int32_t>(kRepF32);
                    mask = AscendC::Reg::UpdateMask<float>(remaining);

                    AscendC::Reg::LoadAlign(f32Reg, srcPtr + off);
                    AscendC::Reg::Muls(f32Reg, f32Reg, cof_, mask); // post_op: var = sq_sum × cof

                    if (ifStd_ != 0) {
                        AscendC::Reg::Duplicate(zeroReg, 0.0f);
                        AscendC::Reg::Max(f32Reg, f32Reg, zeroReg, mask);
                        AscendC::Reg::Sqrt(f32Reg, f32Reg, mask);
                    }

                    if constexpr (kIsFp32) {
                        AscendC::Reg::StoreAlign(dstPtr + off, f32Reg, mask);
                    } else {
                        AscendC::Reg::RegTensor<D_T> b16Reg;
                        AscendC::Reg::Cast<D_T, float, kCastTraitFromFp32>(b16Reg, f32Reg, mask);
                        AscendC::Reg::StoreAlign<D_T, AscendC::Reg::StoreDist::DIST_PACK_B32>(dstPtr + off, b16Reg,
                                                                                              mask);
                    }
                    remaining = (remaining > kRepF32) ? (remaining - kRepF32) : 0;
                }
            }
            outQue_.EnQue(outLocal);

            auto outDeq = outQue_.DeQue<D_T>();
            DataCopyExtParams outParams;
            outParams.blockLen = static_cast<uint32_t>(a_len * static_cast<int64_t>(sizeof(D_T)));
            outParams.blockCount = 1;
            outParams.srcStride = 0;
            outParams.dstStride = 0;
            DataCopyPad(outputGm_[a_off], outDeq, outParams);
            outQue_.FreeTensor(outDeq);
        }
    }
}

} // namespace NsReduceStdV2Update

#endif // OPS_REDUCE_STD_V2_UPDATE_H_
