/**
 * Copyright (c) 2025-2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file reduce_std_v2_update_empty.h
 * \brief ReduceStdV2Update 空 tensor 模板 kernel 类实现。
 *
 * 覆盖两种几何：
 *   EMPTY_A (∃ A 轴 axisShape==0)：output 是空 tensor，kernel 零操作。
 *       usedCoreNum=0、SetBlockDim(1)、所有核命中 `blockIdx >= usedCoreNum` 早退。
 *   EMPTY_R (∃ R 轴 axisShape==0 且 ∀ A 轴 axisShape>0)：
 *       empty_r_output_value=NaN，与 normal 模板 N<=correction 时的 cof=NaN 语义一致。
 *       本算子 has_post_elewise=true（Cast 至少存在），走 Duplicate fp32 NaN → tmpBuf →
 *       Cast 缩位 → outBuf → CopyOut。
 *
 * 与 normal 模板共享：
 *   - TilingData struct（字段含义按重映射；新增 aTotal 走 axisShape[0]）
 *   - TilingKey 两 bool（isEmptyTensor / isTailR）：空模板下 isTailR 固定 0、kernel 不读
 *
 * 物理隔离：本文件独立；kernel 类不带 isTailR 模板参数（empty 与 tail 类型无关）。
 */
#ifndef OPS_REDUCE_STD_V2_UPDATE_EMPTY_H_
#define OPS_REDUCE_STD_V2_UPDATE_EMPTY_H_

#include "kernel_operator.h"
#include "kernel_tiling/kernel_tiling.h"
#include "reduce_std_v2_update_tiling_data.h"
#include "reduce_std_v2_update_tiling_key.h"

namespace NsReduceStdV2Update {

using namespace AscendC;

template <typename DType>
class ReduceStdV2UpdateEmptyKernel {
public:
    using D_T = DType;
    using ComputeT = float;

    static constexpr bool kIsFp32 = std::is_same_v<D_T, float>;
    static constexpr bool kIsB16 = (sizeof(D_T) == 2); // fp16 / bf16

    // CastTrait：fp32 → X（缩位，BF16/FP16 统一 CAST_RINT）
    static constexpr AscendC::Reg::CastTrait kCastTraitFromFp32{
        AscendC::Reg::RegLayout::ZERO, AscendC::Reg::SatMode::NO_SAT, AscendC::Reg::MaskMergeMode::ZEROING,
        AscendC::RoundMode::CAST_RINT};

    static constexpr uint32_t kVlBytes = 256;
    static constexpr uint32_t kRepF32 = kVlBytes / sizeof(float); // = 64
    static constexpr uint16_t kRepF32U = static_cast<uint16_t>(kRepF32);
    static constexpr uint8_t kOutputBufferNum = 1;
    // UpdateMask updates its scalar argument by reference; do not decrement it again.

    __aicore__ inline ReduceStdV2UpdateEmptyKernel() {}

    __aicore__ inline void Init(GM_ADDR x, GM_ADDR mean, GM_ADDR output, const ReduceStdV2UpdateTilingData* td)
    {
        // Empty 模板不读 x/mean，签名保留扩展灵活性。
        (void)x;
        (void)mean;
        usedCoreNum_ = td->usedCoreNum;
        aTotal_ = td->axisShape[0]; // aTotal 走 axisShape[0]
        aUbFactor_ = td->aUbFactor;
        aBigCoreCnt_ = td->aBigCoreCnt;
        aBigCoreLoopCnt_ = td->aBigCoreLoopCnt;
        aSmallCoreLoopCnt_ = td->aSmallCoreLoopCnt;
        outputValue_ = td->cof;

        outputGm_.SetGlobalBuffer(reinterpret_cast<__gm__ D_T*>(output));
        // 仅 outBuf + tmpBuf：N_out=1, N_tmp=1（fp32 中转）
        // postReduceUbSize = CeilAlign(aUbFactor × sizeof(D_T), blockSize)
        pipe_.InitBuffer(outQue_, kOutputBufferNum, td->postReduceUbSize);
        pipe_.InitBuffer(tmpBuf_, td->tmpBufUbSize);
    }

    __aicore__ inline void Process()
    {
        const int64_t blockIdx = static_cast<int64_t>(GetBlockIdx());
        // EMPTY_A: usedCoreNum=0 → 所有核早退（kernel 零操作）
        // EMPTY_R: usedCoreNum>0 → 走下面主循环
        if (blockIdx >= static_cast<int64_t>(usedCoreNum_)) {
            return;
        }

        int64_t aStart, aEnd;
        if (blockIdx < static_cast<int64_t>(aBigCoreCnt_)) {
            aStart = blockIdx * aBigCoreLoopCnt_ * aUbFactor_;
            aEnd = aStart + aBigCoreLoopCnt_ * aUbFactor_;
        } else {
            aStart = static_cast<int64_t>(aBigCoreCnt_) * aBigCoreLoopCnt_ * aUbFactor_ +
                     (blockIdx - static_cast<int64_t>(aBigCoreCnt_)) * aSmallCoreLoopCnt_ * aUbFactor_;
            aEnd = aStart + aSmallCoreLoopCnt_ * aUbFactor_;
        }
        if (aEnd > aTotal_) {
            aEnd = aTotal_;
        }

        for (int64_t aOff = aStart; aOff < aEnd; aOff += aUbFactor_) {
            const int64_t aLen = (aOff + aUbFactor_ > aEnd) ? (aEnd - aOff) : aUbFactor_;
            FillNanAndCopyOut(aOff, aLen);
        }
    }

private:
    // ════════════════════════════════════════════════════════════════════════
    // 单 chunk：Duplicate fp32 NaN → tmpBuf → Cast→D_T → outBuf → DataCopyPad
    // ════════════════════════════════════════════════════════════════════════
    __aicore__ inline void FillNanAndCopyOut(int64_t outOff, int64_t aLen)
    {
        // Step 1: Duplicate fp32 NaN → tmpBuf
        auto tmpLocal = tmpBuf_.Get<float>();
        __ubuf__ float* tmpPtr = reinterpret_cast<__ubuf__ float*>(tmpLocal.GetPhyAddr());

        const uint32_t totalElems = static_cast<uint32_t>(aLen);
        const uint16_t repeatTime = static_cast<uint16_t>((totalElems + kRepF32U - 1) / kRepF32U);

        __VEC_SCOPE__
        {
            AscendC::Reg::RegTensor<float> f32Reg;
            AscendC::Reg::Duplicate(f32Reg, outputValue_);
            AscendC::Reg::MaskReg mask;
            uint32_t remaining = totalElems;

            for (uint16_t i = 0; i < repeatTime; ++i) {
                const int32_t off = static_cast<int32_t>(i) * static_cast<int32_t>(kRepF32);
                mask = AscendC::Reg::UpdateMask<float>(remaining);
                AscendC::Reg::StoreAlign(tmpPtr + off, f32Reg, mask);
            }
        }

        // Step 2: Cast fp32→D_T → outBuf
        auto outLocal = outQue_.AllocTensor<D_T>();
        __ubuf__ D_T* outPtr = reinterpret_cast<__ubuf__ D_T*>(outLocal.GetPhyAddr());

        __VEC_SCOPE__
        {
            AscendC::Reg::RegTensor<float> f32Reg;
            AscendC::Reg::MaskReg mask;
            uint32_t remaining = totalElems;

            for (uint16_t i = 0; i < repeatTime; ++i) {
                const int32_t off = static_cast<int32_t>(i) * static_cast<int32_t>(kRepF32);
                mask = AscendC::Reg::UpdateMask<float>(remaining);
                AscendC::Reg::LoadAlign(f32Reg, tmpPtr + off);

                if constexpr (kIsFp32) {
                    AscendC::Reg::StoreAlign(outPtr + off, f32Reg, mask);
                } else {
                    AscendC::Reg::RegTensor<D_T> b16Reg;
                    AscendC::Reg::Cast<D_T, float, kCastTraitFromFp32>(b16Reg, f32Reg, mask);
                    AscendC::Reg::StoreAlign<D_T, AscendC::Reg::StoreDist::DIST_PACK_B32>(outPtr + off, b16Reg, mask);
                }
            }
        }
        outQue_.EnQue(outLocal);

        // Step 3: CopyOut → GM
        auto outDeq = outQue_.DeQue<D_T>();
        DataCopyExtParams outParams;
        outParams.blockLen = static_cast<uint32_t>(aLen * static_cast<int64_t>(sizeof(D_T)));
        outParams.blockCount = 1;
        outParams.srcStride = 0;
        outParams.dstStride = 0;
        DataCopyPad(outputGm_[outOff], outDeq, outParams);
        outQue_.FreeTensor(outDeq);
    }

    // ─── tilingdata 镜像 ───
    int32_t usedCoreNum_ = 0;
    int64_t aTotal_ = 0;
    int64_t aUbFactor_ = 0;
    int32_t aBigCoreCnt_ = 0;
    int64_t aBigCoreLoopCnt_ = 0;
    int64_t aSmallCoreLoopCnt_ = 0;
    float outputValue_ = 0.0F;

    // ─── GM + UB ───
    GlobalTensor<D_T> outputGm_;
    TPipe pipe_;
    TBuf<QuePosition::VECCALC> tmpBuf_; // fp32 中转（empty_r_output_value 写入）
    TQue<QuePosition::VECOUT, 1> outQue_;
};

} // namespace NsReduceStdV2Update

#endif // OPS_REDUCE_STD_V2_UPDATE_EMPTY_H_
