/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 *
 * Generated By CANNBot
 */

/*!
 * \file spence_tiling_data.h
 * \brief TilingData 结构体定义
 */

#ifndef _SPENCE_TILING_DATA_H_
#define _SPENCE_TILING_DATA_H_

struct SpenceTilingData {
    int64_t dim0 = 0;                  // 展平元素总数
    int32_t coreNum = 0;               // 实际使用核数
    int64_t blockFormer = 0;           // 每核基础元素数（对齐后）
    int64_t blockNum = 0;              // 虚拟 block 数量
    int64_t ubFormer = 0;              // 每个 UB tile 的元素数（kernel 用作 chunk size）
    int64_t ubLoopOfFormerBlock = 0;   // 首 block 的 UB 循环次数（预留，供未来 kernel 优化）
    int64_t ubTailOfFormerBlock = 0;   // 首 block 尾部元素数（预留，供未来 kernel 优化）
    int64_t ubLoopOfTailBlock = 0;     // 尾 block 的 UB 循环次数（预留，供未来 kernel 优化）
    int64_t ubTailOfTailBlock = 0;     // 尾 block 尾部元素数（预留，供未来 kernel 优化）
    int32_t dtype = 0;                 // 数据类型标识
};

#endif
