/**
 * Copyright (c) 2025-2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#include <gtest/gtest.h>
#include <vector>

#include "infershape_case_executor.h"
#include "infershape_context_faker.h"

class SignBitsUnpackInfershapeTest : public testing::Test {};

TEST_F(SignBitsUnpackInfershapeTest, basic_shape)
{
    gert::InfershapeContextPara context("SignBitsUnpack",
                                        {
                                            {{{2}, {2}}, ge::DT_UINT8, ge::FORMAT_ND},
                                        },
                                        {
                                            {{{}, {}}, ge::DT_FLOAT16, ge::FORMAT_ND},
                                        },
                                        {
                                            {"size", Ops::Math::AnyValue::CreateFrom<int64_t>(2)},
                                        });
    std::vector<std::vector<int64_t>> expectedShape = {{2, 8}};

    ExecuteTestCase(context, ge::GRAPH_SUCCESS, expectedShape);
}

TEST_F(SignBitsUnpackInfershapeTest, size_one_flattens_output)
{
    gert::InfershapeContextPara context("SignBitsUnpack",
                                        {
                                            {{{16}, {16}}, ge::DT_UINT8, ge::FORMAT_ND},
                                        },
                                        {
                                            {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                        },
                                        {
                                            {"size", Ops::Math::AnyValue::CreateFrom<int64_t>(1)},
                                        });
    std::vector<std::vector<int64_t>> expectedShape = {{1, 128}};

    ExecuteTestCase(context, ge::GRAPH_SUCCESS, expectedShape);
}

TEST_F(SignBitsUnpackInfershapeTest, size_equals_unpacked_element_count)
{
    gert::InfershapeContextPara context("SignBitsUnpack",
                                        {
                                            {{{2}, {2}}, ge::DT_UINT8, ge::FORMAT_ND},
                                        },
                                        {
                                            {{{}, {}}, ge::DT_FLOAT16, ge::FORMAT_ND},
                                        },
                                        {
                                            {"size", Ops::Math::AnyValue::CreateFrom<int64_t>(16)},
                                        });
    std::vector<std::vector<int64_t>> expectedShape = {{16, 1}};

    ExecuteTestCase(context, ge::GRAPH_SUCCESS, expectedShape);
}

TEST_F(SignBitsUnpackInfershapeTest, empty_input)
{
    gert::InfershapeContextPara context("SignBitsUnpack",
                                        {
                                            {{{0}, {0}}, ge::DT_UINT8, ge::FORMAT_ND},
                                        },
                                        {
                                            {{{}, {}}, ge::DT_FLOAT16, ge::FORMAT_ND},
                                        },
                                        {
                                            {"size", Ops::Math::AnyValue::CreateFrom<int64_t>(2)},
                                        });
    std::vector<std::vector<int64_t>> expectedShape = {{2, 0}};

    ExecuteTestCase(context, ge::GRAPH_SUCCESS, expectedShape);
}

TEST_F(SignBitsUnpackInfershapeTest, size_zero_fails)
{
    gert::InfershapeContextPara context("SignBitsUnpack",
                                        {
                                            {{{2}, {2}}, ge::DT_UINT8, ge::FORMAT_ND},
                                        },
                                        {
                                            {{{}, {}}, ge::DT_FLOAT16, ge::FORMAT_ND},
                                        },
                                        {
                                            {"size", Ops::Math::AnyValue::CreateFrom<int64_t>(0)},
                                        });

    ExecuteTestCase(context, ge::GRAPH_FAILED, {});
}

TEST_F(SignBitsUnpackInfershapeTest, size_negative_fails)
{
    gert::InfershapeContextPara context("SignBitsUnpack",
                                        {
                                            {{{2}, {2}}, ge::DT_UINT8, ge::FORMAT_ND},
                                        },
                                        {
                                            {{{}, {}}, ge::DT_FLOAT16, ge::FORMAT_ND},
                                        },
                                        {
                                            {"size", Ops::Math::AnyValue::CreateFrom<int64_t>(-1)},
                                        });

    ExecuteTestCase(context, ge::GRAPH_FAILED, {});
}

TEST_F(SignBitsUnpackInfershapeTest, non_divisible_size_uses_integer_division)
{
    gert::InfershapeContextPara context("SignBitsUnpack",
                                        {
                                            {{{3}, {3}}, ge::DT_UINT8, ge::FORMAT_ND},
                                        },
                                        {
                                            {{{}, {}}, ge::DT_FLOAT16, ge::FORMAT_ND},
                                        },
                                        {
                                            {"size", Ops::Math::AnyValue::CreateFrom<int64_t>(5)},
                                        });
    std::vector<std::vector<int64_t>> expectedShape = {{5, 4}};

    ExecuteTestCase(context, ge::GRAPH_SUCCESS, expectedShape);
}

TEST_F(SignBitsUnpackInfershapeTest, input_rank_must_be_one)
{
    gert::InfershapeContextPara context("SignBitsUnpack",
                                        {
                                            {{{2, 1}, {2, 1}}, ge::DT_UINT8, ge::FORMAT_ND},
                                        },
                                        {
                                            {{{}, {}}, ge::DT_FLOAT16, ge::FORMAT_ND},
                                        },
                                        {
                                            {"size", Ops::Math::AnyValue::CreateFrom<int64_t>(2)},
                                        });

    ExecuteTestCase(context, ge::GRAPH_FAILED, {});
}

TEST_F(SignBitsUnpackInfershapeTest, missing_size_attribute_fails)
{
    gert::InfershapeContextPara context("SignBitsUnpack",
                                        {
                                            {{{2}, {2}}, ge::DT_UINT8, ge::FORMAT_ND},
                                        },
                                        {
                                            {{{}, {}}, ge::DT_FLOAT16, ge::FORMAT_ND},
                                        });

    ExecuteTestCase(context, ge::GRAPH_FAILED, {});
}
