/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */
/* Generated By CANNBot */

#include <iostream>
#include <gtest/gtest.h>
#include "tiling_context_faker.h"
#include "tiling_case_executor.h"
#include "any_value.h"
#include "../../../../op_kernel/arch35/prod_env_mat_a_tiling_data.h"
#include "../../../../op_kernel/arch35/prod_env_mat_a_tiling_key.h"

using namespace std;
using namespace ge;

class ProdEnvMatATiling : public testing::Test {
protected:
    static void SetUpTestCase() { std::cout << "ProdEnvMatATiling SetUp" << std::endl; }

    static void TearDownTestCase() { std::cout << "ProdEnvMatATiling TearDown" << std::endl; }
};

std::map<std::string, std::string> soc_version_infos = {{"Short_SoC_version", "Ascend950"}};

static std::vector<gert::TilingContextPara::OpAttr> MakeAttrs(float rcutA, float rcutR, float rcutRSmth,
                                                              const std::vector<int64_t>& selA,
                                                              const std::vector<int64_t>& selR)
{
    return {
        {"rcut_a", Ops::Math::AnyValue::CreateFrom<float>(rcutA)},
        {"rcut_r", Ops::Math::AnyValue::CreateFrom<float>(rcutR)},
        {"rcut_r_smth", Ops::Math::AnyValue::CreateFrom<float>(rcutRSmth)},
        {"sel_a", Ops::Math::AnyValue::CreateFrom<std::vector<int64_t>>(selA)},
        {"sel_r", Ops::Math::AnyValue::CreateFrom<std::vector<int64_t>>(selR)},
    };
}

TEST_F(ProdEnvMatATiling, prod_env_mat_a_tiling_0)
{
    struct ProdEnvMatACompileInfo {
    } compileInfo;
    auto attrs = MakeAttrs(-1.0f, 6.0f, 0.5f, {4}, {});
    gert::TilingContextPara tilingContextPara("ProdEnvMatA",
                                              {
                                                  {{{2, 12}, {2, 12}}, ge::DT_FLOAT, ge::FORMAT_ND}, // coord
                                                  {{{2, 4}, {2, 4}}, ge::DT_INT32, ge::FORMAT_ND},   // type
                                                  {{{3}, {3}}, ge::DT_INT32, ge::FORMAT_ND},         // natoms
                                                  {{{9}, {9}}, ge::DT_FLOAT, ge::FORMAT_ND},         // box
                                                  {{{16}, {16}}, ge::DT_INT32, ge::FORMAT_ND},       // mesh
                                                  {{{1, 4}, {1, 4}}, ge::DT_FLOAT, ge::FORMAT_ND},   // davg
                                                  {{{1, 4}, {1, 4}}, ge::DT_FLOAT, ge::FORMAT_ND},   // dstd
                                              },
                                              {
                                                  {{{2, 64}, {2, 64}}, ge::DT_FLOAT, ge::FORMAT_ND},   // descrpt
                                                  {{{2, 192}, {2, 192}}, ge::DT_FLOAT, ge::FORMAT_ND}, // descrpt_deriv
                                                  {{{2, 48}, {2, 48}}, ge::DT_FLOAT, ge::FORMAT_ND},   // rij
                                                  {{{2, 16}, {2, 16}}, ge::DT_INT32, ge::FORMAT_ND},   // nlist
                                              },
                                              attrs, &compileInfo, 64, 262144, 4096);
    uint64_t expectTilingKey = PROD_ENV_MAT_A_SCH_MODE_DEFAULT;
    string expectTilingData = EMPTY_EXPECT_TILING_DATA;
    // tiling.cpp GetWorkspaceSize uses GetLibApiWorkSpaceSize() (sys workspace)
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}

TEST_F(ProdEnvMatATiling, prod_env_mat_a_tiling_1)
{
    struct ProdEnvMatACompileInfo {
    } compileInfo;
    auto attrs = MakeAttrs(-1.0f, 8.0f, 2.0f, {4, 6}, {});
    gert::TilingContextPara tilingContextPara("ProdEnvMatA",
                                              {
                                                  {{{3, 30}, {3, 30}}, ge::DT_FLOAT, ge::FORMAT_ND}, // coord
                                                  {{{3, 10}, {3, 10}}, ge::DT_INT32, ge::FORMAT_ND}, // type
                                                  {{{4}, {4}}, ge::DT_INT32, ge::FORMAT_ND},         // natoms
                                                  {{{9}, {9}}, ge::DT_FLOAT, ge::FORMAT_ND},         // box
                                                  {{{16}, {16}}, ge::DT_INT32, ge::FORMAT_ND},       // mesh
                                                  {{{2, 10}, {2, 10}}, ge::DT_FLOAT, ge::FORMAT_ND}, // davg
                                                  {{{2, 10}, {2, 10}}, ge::DT_FLOAT, ge::FORMAT_ND}, // dstd
                                              },
                                              {
                                                  {{{3, 320}, {3, 320}}, ge::DT_FLOAT, ge::FORMAT_ND}, // descrpt
                                                  {{{3, 960}, {3, 960}}, ge::DT_FLOAT, ge::FORMAT_ND}, // descrpt_deriv
                                                  {{{3, 240}, {3, 240}}, ge::DT_FLOAT, ge::FORMAT_ND}, // rij
                                                  {{{3, 80}, {3, 80}}, ge::DT_INT32, ge::FORMAT_ND},   // nlist
                                              },
                                              attrs, &compileInfo, 64, 262144, 4096);
    uint64_t expectTilingKey = PROD_ENV_MAT_A_SCH_MODE_DEFAULT;
    string expectTilingData = EMPTY_EXPECT_TILING_DATA;
    // tiling.cpp GetWorkspaceSize uses GetLibApiWorkSpaceSize() (sys workspace)
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}

TEST_F(ProdEnvMatATiling, prod_env_mat_a_tiling_2)
{
    struct ProdEnvMatACompileInfo {
    } compileInfo;
    auto attrs = MakeAttrs(-1.0f, 6.0f, 0.5f, {46}, {});
    gert::TilingContextPara tilingContextPara(
        "ProdEnvMatA",
        {
            {{{10, 600}, {10, 600}}, ge::DT_FLOAT, ge::FORMAT_ND}, // coord
            {{{10, 200}, {10, 200}}, ge::DT_INT32, ge::FORMAT_ND}, // type
            {{{3}, {3}}, ge::DT_INT32, ge::FORMAT_ND},             // natoms
            {{{9}, {9}}, ge::DT_FLOAT, ge::FORMAT_ND},             // box
            {{{16}, {16}}, ge::DT_INT32, ge::FORMAT_ND},           // mesh
            {{{1, 46}, {1, 46}}, ge::DT_FLOAT, ge::FORMAT_ND},     // davg
            {{{1, 46}, {1, 46}}, ge::DT_FLOAT, ge::FORMAT_ND},     // dstd
        },
        {
            {{{10, 35328}, {10, 35328}}, ge::DT_FLOAT, ge::FORMAT_ND},   // descrpt
            {{{10, 105984}, {10, 105984}}, ge::DT_FLOAT, ge::FORMAT_ND}, // descrpt_deriv
            {{{10, 26496}, {10, 26496}}, ge::DT_FLOAT, ge::FORMAT_ND},   // rij
            {{{10, 8832}, {10, 8832}}, ge::DT_INT32, ge::FORMAT_ND},     // nlist
        },
        attrs, &compileInfo, 64, 262144, 4096);
    uint64_t expectTilingKey = PROD_ENV_MAT_A_SCH_MODE_DEFAULT;
    string expectTilingData = EMPTY_EXPECT_TILING_DATA;
    // tiling.cpp GetWorkspaceSize uses GetLibApiWorkSpaceSize() (sys workspace)
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}

TEST_F(ProdEnvMatATiling, prod_env_mat_a_tiling_3)
{
    struct ProdEnvMatACompileInfo {
    } compileInfo;
    auto attrs = MakeAttrs(-1.0f, 6.0f, 0.5f, {4}, {});
    gert::TilingContextPara tilingContextPara("ProdEnvMatA",
                                              {
                                                  {{{1, 12}, {1, 12}}, ge::DT_FLOAT, ge::FORMAT_ND}, // coord
                                                  {{{1, 4}, {1, 4}}, ge::DT_INT32, ge::FORMAT_ND},   // type
                                                  {{{3}, {3}}, ge::DT_INT32, ge::FORMAT_ND},         // natoms
                                                  {{{9}, {9}}, ge::DT_FLOAT, ge::FORMAT_ND},         // box
                                                  {{{16}, {16}}, ge::DT_INT32, ge::FORMAT_ND},       // mesh
                                                  {{{1, 4}, {1, 4}}, ge::DT_FLOAT, ge::FORMAT_ND},   // davg
                                                  {{{1, 4}, {1, 4}}, ge::DT_FLOAT, ge::FORMAT_ND},   // dstd
                                              },
                                              {
                                                  {{{1, 0}, {1, 0}}, ge::DT_FLOAT, ge::FORMAT_ND}, // descrpt (nloc=0)
                                                  {{{1, 0}, {1, 0}}, ge::DT_FLOAT, ge::FORMAT_ND}, // descrpt_deriv
                                                  {{{1, 0}, {1, 0}}, ge::DT_FLOAT, ge::FORMAT_ND}, // rij
                                                  {{{1, 0}, {1, 0}}, ge::DT_INT32, ge::FORMAT_ND}, // nlist
                                              },
                                              attrs, &compileInfo, 64, 262144, 4096);
    uint64_t expectTilingKey = PROD_ENV_MAT_A_SCH_MODE_DEFAULT;
    string expectTilingData = EMPTY_EXPECT_TILING_DATA;
    // tiling.cpp GetWorkspaceSize uses GetLibApiWorkSpaceSize() (sys workspace)
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}

TEST_F(ProdEnvMatATiling, prod_env_mat_a_tiling_4)
{
    struct ProdEnvMatACompileInfo {
    } compileInfo;
    auto attrs = MakeAttrs(-1.0f, 0.0f, 0.5f, {4}, {});
    gert::TilingContextPara tilingContextPara("ProdEnvMatA",
                                              {
                                                  {{{2, 12}, {2, 12}}, ge::DT_FLOAT, ge::FORMAT_ND}, // coord
                                                  {{{2, 4}, {2, 4}}, ge::DT_INT32, ge::FORMAT_ND},   // type
                                                  {{{3}, {3}}, ge::DT_INT32, ge::FORMAT_ND},         // natoms
                                                  {{{9}, {9}}, ge::DT_FLOAT, ge::FORMAT_ND},         // box
                                                  {{{16}, {16}}, ge::DT_INT32, ge::FORMAT_ND},       // mesh
                                                  {{{1, 4}, {1, 4}}, ge::DT_FLOAT, ge::FORMAT_ND},   // davg
                                                  {{{1, 4}, {1, 4}}, ge::DT_FLOAT, ge::FORMAT_ND},   // dstd
                                              },
                                              {
                                                  {{{2, 64}, {2, 64}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                  {{{2, 192}, {2, 192}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                  {{{2, 48}, {2, 48}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                  {{{2, 16}, {2, 16}}, ge::DT_INT32, ge::FORMAT_ND},
                                              },
                                              attrs, &compileInfo, 64, 262144, 4096);
    std::vector<size_t> expectWorkspaces = {0};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_FAILED, 0, expectWorkspaces);
}

TEST_F(ProdEnvMatATiling, prod_env_mat_a_tiling_5)
{
    struct ProdEnvMatACompileInfo {
    } compileInfo;
    auto attrs = MakeAttrs(-1.0f, 6.0f, 0.5f, {}, {});
    gert::TilingContextPara tilingContextPara("ProdEnvMatA",
                                              {
                                                  {{{2, 12}, {2, 12}}, ge::DT_FLOAT, ge::FORMAT_ND}, // coord
                                                  {{{2, 4}, {2, 4}}, ge::DT_INT32, ge::FORMAT_ND},   // type
                                                  {{{3}, {3}}, ge::DT_INT32, ge::FORMAT_ND},         // natoms
                                                  {{{9}, {9}}, ge::DT_FLOAT, ge::FORMAT_ND},         // box
                                                  {{{16}, {16}}, ge::DT_INT32, ge::FORMAT_ND},       // mesh
                                                  {{{1, 4}, {1, 4}}, ge::DT_FLOAT, ge::FORMAT_ND},   // davg
                                                  {{{1, 4}, {1, 4}}, ge::DT_FLOAT, ge::FORMAT_ND},   // dstd
                                              },
                                              {
                                                  {{{2, 64}, {2, 64}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                  {{{2, 192}, {2, 192}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                  {{{2, 48}, {2, 48}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                  {{{2, 16}, {2, 16}}, ge::DT_INT32, ge::FORMAT_ND},
                                              },
                                              attrs, &compileInfo, 64, 262144, 4096);
    std::vector<size_t> expectWorkspaces = {0};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_FAILED, 0, expectWorkspaces);
}
