/**
 * Copyright (c) 2025-2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/**
 * ReduceStdV2Update GE IR 调用示例（对外交付上库主通路）
 *
 * 演示通过 GE IR 图模式调用 ReduceStdV2Update 算子：
 * 1. ge::GEInitialize() 初始化（graphRunMode=1，deviceId=0）
 * 2. 构建 Data(x) + Data(mean) -> ReduceStdV2Update(dim, if_std, unbiased, keepdim, correction) 计算图
 * 3. ge::Session AddGraph + RunGraph 执行（加载自定义 Ascend C kernel）
 * 4. 读取输出张量并与 CPU golden 逐元素比对
 * 5. ge::GEFinalize() 资源释放
 *
 * 算子语义：
 *   if_std=false: var = sum((x - mean)^2, dim) / (N - correction)
 *   if_std=true:  std = sqrt(var)
 *
 * GEIR 通路可通过 if_std 属性控制输出方差或标准差（aclnn 接口固定 if_std=false）。
 *
 * 覆盖：
 *   Test 1 - FP32, if_std=false（方差）, unbiased=true, dim=[1], keepdim=false
 *   Test 2 - FP32, if_std=true（标准差）, correction=1, dim=[1], keepdim=true
 *
 * 编译：参见 CMakeLists.txt   运行：参见 run.sh
 *   ⚠ GE IR 执行触发 TBE 动态编译，需系统 Python 3.9（见 run.sh 环境设置）。
 */

#include <iostream>
#include <fstream>
#include <string.h>
#include <stdint.h>
#include <vector>
#include <string>
#include <map>
#include <cmath>
#include <algorithm>
#include "assert.h"

#include "graph.h"
#include "types.h"
#include "tensor.h"
#include "ge_error_codes.h"
#include "ge_api_types.h"
#include "ge_api.h"
#include "array_ops.h"
#include "reduce_ops.h"
#include "ge_ir_build.h"

#define FAILED -1
#define SUCCESS 0

using namespace ge;
using std::map;
using std::string;
using std::vector;

string GetTime()
{
    time_t timep;
    time(&timep);
    char tmp[64];
    strftime(tmp, sizeof(tmp), "%Y-%m-%d %H:%M:%S,000", localtime(&timep));
    return tmp;
}

// ---- 测试数据：x shape [4,8]
static const int64_t M = 4;
static const int64_t N = 8;
static const float xData[M * N] = {
    1.f, 2.f, 3.f, 4.f, 5.f, 6.f, 7.f, 8.f, 2.f, 3.f, 4.f, 5.f, 6.f, 7.f, 8.f, 9.f,
    0.f, 1.f, 2.f, 3.f, 4.f, 5.f, 6.f, 7.f, 1.f, 1.f, 1.f, 1.f, 1.f, 1.f, 1.f, 1.f,
};

// ---- 计算 mean 并广播到 x 的 shape（dim=1，沿列归约）
static void ComputeMeanBroadcast(const float* x, float* mean, int64_t rows, int64_t cols, int64_t dim)
{
    if (dim == 1) {
        for (int64_t i = 0; i < rows; ++i) {
            double sum = 0;
            for (int64_t j = 0; j < cols; ++j)
                sum += x[i * cols + j];
            float m = static_cast<float>(sum / cols);
            for (int64_t j = 0; j < cols; ++j)
                mean[i * cols + j] = m;
        }
    } else {
        for (int64_t j = 0; j < cols; ++j) {
            double sum = 0;
            for (int64_t i = 0; i < rows; ++i)
                sum += x[i * cols + j];
            float m = static_cast<float>(sum / rows);
            for (int64_t i = 0; i < rows; ++i)
                mean[i * cols + j] = m;
        }
    }
}

// ---- CPU golden：var 或 std（double 精度）
static void ComputeGolden(const float* x, const float* mean, float* output, int64_t rows, int64_t cols, int64_t dim,
                          int64_t correction, bool if_std)
{
    if (dim == 1) {
        for (int64_t i = 0; i < rows; ++i) {
            double sqSum = 0;
            for (int64_t j = 0; j < cols; ++j) {
                double diff = static_cast<double>(x[i * cols + j]) - mean[i * cols + j];
                sqSum += diff * diff;
            }
            double var = sqSum / (cols - correction);
            output[i] = static_cast<float>(if_std ? std::sqrt(std::max(var, 0.0)) : var);
        }
    } else {
        for (int64_t j = 0; j < cols; ++j) {
            double sqSum = 0;
            for (int64_t i = 0; i < rows; ++i) {
                double diff = static_cast<double>(x[i * cols + j]) - mean[i * cols + j];
                sqSum += diff * diff;
            }
            double var = sqSum / (rows - correction);
            output[j] = static_cast<float>(if_std ? std::sqrt(std::max(var, 0.0)) : var);
        }
    }
}

// 构建 ReduceStdV2Update 计算图
int CreateGraph(DataType inDtype, bool if_std, bool unbiased, bool keepdim, int64_t correction,
                const std::vector<int64_t>& dimArr, const std::vector<int64_t>& tensorShape,
                const std::vector<int64_t>& outShape, std::vector<ge::Tensor>& input, std::vector<Operator>& inputs,
                std::vector<Operator>& outputs, Graph& graph)
{
    int64_t n = 1;
    for (auto d : tensorShape)
        n *= d;

    // ---- 输入 x（Data 占位）
    auto dataX = op::Data("x");
    dataX.set_attr_index(0);
    TensorDesc xDesc(ge::Shape(tensorShape), FORMAT_ND, inDtype);
    xDesc.SetPlacement(ge::kPlacementHost);
    xDesc.SetFormat(FORMAT_ND);
    xDesc.SetRealDimCnt(tensorShape.size());
    dataX.update_input_desc_x(xDesc);
    dataX.update_output_desc_y(xDesc);

    std::vector<float> hX(xData, xData + n);
    uint32_t dataLen = static_cast<uint32_t>(n) * sizeof(float);
    Tensor xTensor(xDesc, reinterpret_cast<uint8_t*>(hX.data()), dataLen);
    input.push_back(xTensor);
    graph.AddOp(dataX);
    inputs.push_back(dataX);

    // ---- 输入 mean（Data 占位，已广播到 x shape）
    auto dataMean = op::Data("mean");
    dataMean.set_attr_index(1);
    TensorDesc meanDesc(ge::Shape(tensorShape), FORMAT_ND, inDtype);
    meanDesc.SetPlacement(ge::kPlacementHost);
    meanDesc.SetFormat(FORMAT_ND);
    meanDesc.SetRealDimCnt(tensorShape.size());
    dataMean.update_input_desc_x(meanDesc);
    dataMean.update_output_desc_y(meanDesc);

    std::vector<float> hMean(n, 0.f);
    ComputeMeanBroadcast(hX.data(), hMean.data(), M, N, dimArr[0]);
    Tensor meanTensor(meanDesc, reinterpret_cast<uint8_t*>(hMean.data()), dataLen);
    input.push_back(meanTensor);
    graph.AddOp(dataMean);
    inputs.push_back(dataMean);

    // ---- ReduceStdV2Update 节点
    auto reduceOp = op::ReduceStdV2Update("reduce_std_v2_update_0");
    reduceOp.set_input_x(dataX);
    reduceOp.set_input_mean(dataMean);
    reduceOp.update_input_desc_x(xDesc);
    reduceOp.update_input_desc_mean(meanDesc);

    reduceOp.set_attr_dim(dimArr);
    reduceOp.set_attr_if_std(if_std);
    reduceOp.set_attr_unbiased(unbiased);
    reduceOp.set_attr_keepdim(keepdim);
    reduceOp.set_attr_correction(correction);

    TensorDesc yDesc(ge::Shape(outShape), FORMAT_ND, inDtype);
    yDesc.SetFormat(FORMAT_ND);
    reduceOp.update_output_desc_output_var(yDesc);

    graph.AddOp(reduceOp);
    outputs.push_back(reduceOp);

    return SUCCESS;
}

// 单个测试用例
int RunTestCase(const char* testName, bool if_std, bool unbiased, bool keepdim, int64_t correction,
                const std::vector<int64_t>& dimArr, const std::vector<int64_t>& tensorShape,
                const std::vector<int64_t>& outShape, int64_t outNum, uint32_t graph_id)
{
    if (dimArr.empty()) {
        printf("%s - ERROR - dimArr is empty\n", GetTime().c_str());
        return FAILED;
    }

    Graph graph(testName);
    std::vector<ge::Tensor> input;
    std::vector<Operator> inputs{};
    std::vector<Operator> outputs{};

    DataType inDtype = DT_FLOAT;
    int ret = CreateGraph(inDtype, if_std, unbiased, keepdim, correction, dimArr, tensorShape, outShape, input, inputs,
                          outputs, graph);
    if (ret != SUCCESS) {
        printf("%s - ERROR - Create graph failed\n", GetTime().c_str());
        return FAILED;
    }

    if (!inputs.empty() && !outputs.empty()) {
        graph.SetInputs(inputs).SetOutputs(outputs);
    }

    std::map<AscendString, AscendString> build_options = {};
    ge::Session* session = new Session(build_options);
    if (session == nullptr) {
        printf("%s - ERROR - Create session failed\n", GetTime().c_str());
        return FAILED;
    }

    std::map<AscendString, AscendString> graph_options = {};
    ret = session->AddGraph(graph_id, graph, graph_options);
    if (ret != SUCCESS) {
        printf("%s - ERROR - AddGraph failed\n", GetTime().c_str());
        delete session;
        return FAILED;
    }

    printf("%s - INFO - Run graph: %s\n", GetTime().c_str(), testName);
    std::vector<ge::Tensor> output;
    ret = session->RunGraph(graph_id, input, output);
    if (ret != SUCCESS) {
        printf("%s - ERROR - RunGraph failed\n", GetTime().c_str());
        ge::AscendString error_msg = ge::GEGetErrorMsgV2();
        std::cout << "Error: " << error_msg.GetString() << std::endl;
        delete session;
        return FAILED;
    }
    printf("%s - INFO - RunGraph success\n", GetTime().c_str());

    // ---- 结果验证
    bool passed = true;
    if (output.empty()) {
        printf("%s - ERROR - No output\n", GetTime().c_str());
        passed = false;
    } else {
        int64_t n = M * N;
        std::vector<float> hX(xData, xData + n);
        std::vector<float> hMean(n, 0.f);
        ComputeMeanBroadcast(hX.data(), hMean.data(), M, N, dimArr[0]);

        std::vector<float> hGolden(static_cast<size_t>(outNum));
        ComputeGolden(hX.data(), hMean.data(), hGolden.data(), M, N, dimArr[0], correction, if_std);

        const float* outData = reinterpret_cast<const float*>(output[0].GetData());
        int64_t outRealNum = output[0].GetTensorDesc().GetShape().GetShapeSize();
        if (outRealNum <= 0)
            outRealNum = outNum;

        std::cout << "--- " << testName << ": float32, if_std=" << (if_std ? "true" : "false")
                  << ", correction=" << correction << ", keepdim=" << (keepdim ? "true" : "false") << ", dim=["
                  << dimArr[0] << "] ---" << std::endl;
        std::cout << "  output shape size = " << outRealNum << std::endl;

        const float rtol = 1e-4f, atol = 1e-4f;
        int64_t cmpNum = std::min<int64_t>(outRealNum, outNum);
        for (int64_t i = 0; i < cmpNum; ++i) {
            float err = std::abs(outData[i] - hGolden[i]);
            bool ok = (err <= atol + rtol * std::abs(hGolden[i]));
            if (!ok)
                passed = false;
            std::cout << "  out[" << i << "]=" << outData[i] << " (expected " << hGolden[i] << ", err " << err
                      << (ok ? " OK" : " FAIL") << ")" << std::endl;
        }
    }

    std::cout << (passed ? "[PASS]" : "[FAIL]") << " " << testName << std::endl << std::endl;
    delete session;
    return passed ? SUCCESS : FAILED;
}

int main(int argc, char* argv[])
{
    printf("%s - INFO - Start to initialize ge\n", GetTime().c_str());
    std::map<AscendString, AscendString> global_options = {{"ge.exec.deviceId", "0"}, {"ge.graphRunMode", "1"}};
    Status ret = ge::GEInitialize(global_options);
    if (ret != SUCCESS) {
        printf("%s - ERROR - Initialize ge failed\n", GetTime().c_str());
        return FAILED;
    }
    printf("%s - INFO - Initialize ge success\n", GetTime().c_str());

    std::cout << "=== ReduceStdV2Update GE IR Test ===" << std::endl << std::endl;

    std::vector<int64_t> tensorShape = {M, N};
    std::vector<int64_t> dimArr = {1};

    // Test 1: if_std=false（方差）, unbiased=true (correction=1), keepdim=false, dim=[1]
    //   output shape = [4], expected var = [6.0, 6.0, 6.0, 0.0]
    std::vector<int64_t> outShape1 = {M};
    int r1 = RunTestCase("GEIR_Test1_var", false, true, false, 1, dimArr, tensorShape, outShape1, M, 0);

    // Test 2: if_std=true（标准差）, unbiased=true (correction=1), keepdim=true, dim=[1]
    //   output shape = [4,1], expected std = [2.44949, 2.44949, 2.44949, 0.0]
    //   注：tiling 中 unbiased=false 会强制 correction=0，故 unbiased=true 与 correction=1 配合使用
    std::vector<int64_t> outShape2 = {M, 1};
    int r2 = RunTestCase("GEIR_Test2_std", true, true, true, 1, dimArr, tensorShape, outShape2, M, 1);

    bool allPassed = (r1 == SUCCESS && r2 == SUCCESS);
    std::cout << (allPassed ? "[PASS] All GE IR tests passed." : "[FAIL] Some GE IR tests failed.") << std::endl;

    printf("%s - INFO - Finalize ge\n", GetTime().c_str());
    ge::GEFinalize();
    printf("%s - INFO - Finalize ge success\n", GetTime().c_str());

    return allPassed ? SUCCESS : FAILED;
}
