/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#include "register/op_def_registry.h"
#include "op_common/log/log.h"
#include "op_common/op_host/util/math_util.h"
#include "op_common/op_host/util/platform_util.h"
#include "../../op_kernel/arch35/population_count_tiling_data.h"
#include "../../op_kernel/arch35/population_count_tiling_key.h"

namespace optiling {

using Ops::Base::CeilDiv;
using Ops::Base::CeilAlign;
using Ops::Base::FloorDiv;
using Ops::Base::FloorAlign;
using Ops::Base::GetUbBlockSize;

constexpr uint32_t WS_SYS_SIZE = 0U;
constexpr int64_t MIN_SPLIT_THRESHOLD = 1024;
// UB 中每个元素占用的等效总字节数（含所有 buffer 分配）
// 单 buffer: 2(input) + 1(output) + 2(tmp) = 5
constexpr int64_t UB_BYTES_PER_ELEM_SINGLE = 5;
// 双 buffer: 4(input×2buf) + 2(output×2buf) + 2(tmp) = 8
constexpr int64_t UB_BYTES_PER_ELEM_DOUBLE = 8;

static const gert::Shape g_vec_1_shape = {1};

static inline const gert::Shape EnsureNotScalar(const gert::Shape& in_shape) {
    if (in_shape.GetDimNum() == 0) {
        return g_vec_1_shape;
    }
    return in_shape;
}

static ge::graphStatus GetPlatformInfo(gert::TilingContext* context, uint64_t& ubSize, int64_t& coreNum)
{
    fe::PlatFormInfos* platformInfoPtr = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfoPtr);
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);
    coreNum = ascendcPlatform.GetCoreNumAiv();
    OP_CHECK_IF(coreNum == 0, OP_LOGE(context, "coreNum is 0"), return ge::GRAPH_FAILED);
    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, ubSize);
    OP_CHECK_IF(ubSize == 0, OP_LOGE(context, "ubSize is 0"), return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus GetShapeAttrsInfo(gert::TilingContext* context, int64_t& totalIdx, ge::DataType& dataType)
{
    auto inputX = context->GetInputShape(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputX);
    auto inputShapeX = EnsureNotScalar(inputX->GetStorageShape());

    totalIdx = inputShapeX.GetShapeSize();

    const std::set<ge::DataType> supportedDtype = {ge::DT_INT16, ge::DT_UINT16};
    auto inputDesc = context->GetInputDesc(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputDesc);
    dataType = inputDesc->GetDataType();
    OP_CHECK_IF(supportedDtype.count(dataType) == 0,
                OP_LOGE(context, "PopulationCount: invalid input dtype %d (must be INT16/UINT16)",
                        static_cast<int>(dataType)),
                return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus GetWorkspaceSize(gert::TilingContext* context)
{
    size_t* currentWorkspace = context->GetWorkspaceSizes(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, currentWorkspace);
    currentWorkspace[0] = WS_SYS_SIZE;
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus HandleEmptyTensor(gert::TilingContext* context, ge::DataType dataType)
{
    PopulationCountTilingData* tiling = context->GetTilingData<PopulationCountTilingData>();
    OP_CHECK_NULL_WITH_CONTEXT(context, tiling);
    OP_CHECK_IF(
        memset_s(tiling, sizeof(PopulationCountTilingData), 0, sizeof(PopulationCountTilingData)) != EOK,
        OP_LOGE(context, "memset tiling data error (empty tensor)"),
        return ge::GRAPH_FAILED);

    size_t* workspace = context->GetWorkspaceSizes(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, workspace);
    workspace[0] = WS_SYS_SIZE;

    context->SetBlockDim(1);
    uint32_t dTypeX = static_cast<uint32_t>(dataType);
    uint64_t useDoubleBuffer = 0U;
    ASCENDC_TPL_SEL_PARAM(context, dTypeX, useDoubleBuffer);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus ComputeTilingParams(gert::TilingContext* context, int64_t totalIdx,
                                           uint64_t ubSize, int64_t coreNum, ge::DataType dataType)
{
    OP_CHECK_IF(
        GetWorkspaceSize(context) != ge::GRAPH_SUCCESS,
        OP_LOGE(context, "GetWorkspaceSize error"),
        return ge::GRAPH_FAILED);

    PopulationCountTilingData* tiling = context->GetTilingData<PopulationCountTilingData>();
    OP_CHECK_NULL_WITH_CONTEXT(context, tiling);
    OP_CHECK_IF(
        memset_s(tiling, sizeof(PopulationCountTilingData), 0, sizeof(PopulationCountTilingData)) != EOK,
        OP_LOGE(context, "memset tiling data error"),
        return ge::GRAPH_FAILED);

    tiling->totalNum = totalIdx;

    int64_t ubBlockSize = GetUbBlockSize(context);
    tiling->blockFactor = CeilAlign(CeilDiv(totalIdx, coreNum), ubBlockSize);
    int64_t usedCoreNum = CeilDiv(totalIdx, std::max<int64_t>(tiling->blockFactor, 1));

    uint64_t useDoubleBuffer = (totalIdx > MIN_SPLIT_THRESHOLD) ? 1 : 0;
    int64_t perElemBytes = useDoubleBuffer ? UB_BYTES_PER_ELEM_DOUBLE : UB_BYTES_PER_ELEM_SINGLE;
    int64_t ubFactorRaw = static_cast<int64_t>(ubSize) / perElemBytes;
    tiling->ubFactor = FloorAlign(ubFactorRaw, ubBlockSize);

    context->SetBlockDim(std::max<int64_t>(usedCoreNum, 1));

    uint32_t dTypeX = static_cast<uint32_t>(dataType);
    ASCENDC_TPL_SEL_PARAM(context, dTypeX, useDoubleBuffer);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus PopulationCountTilingFunc(gert::TilingContext* context)
{
    uint64_t ubSize = 0;
    int64_t coreNum = 0;
    OP_CHECK_IF(
        GetPlatformInfo(context, ubSize, coreNum) != ge::GRAPH_SUCCESS,
        OP_LOGE(context, "GetPlatformInfo error"),
        return ge::GRAPH_FAILED);

    int64_t totalIdx = 0;
    ge::DataType dataType = ge::DT_UNDEFINED;
    OP_CHECK_IF(
        GetShapeAttrsInfo(context, totalIdx, dataType) != ge::GRAPH_SUCCESS,
        OP_LOGE(context, "GetShapeAttrsInfo error"),
        return ge::GRAPH_FAILED);

    if (totalIdx == 0) {
        return HandleEmptyTensor(context, dataType);
    }
    return ComputeTilingParams(context, totalIdx, ubSize, coreNum, dataType);
}

static ge::graphStatus TilingParseForPopulationCount([[maybe_unused]] gert::TilingParseContext* context)
{
    return ge::GRAPH_SUCCESS;
}

struct PopulationCountCompileInfo {};

IMPL_OP_OPTILING(PopulationCount)
    .Tiling(PopulationCountTilingFunc)
    .TilingParse<PopulationCountCompileInfo>(TilingParseForPopulationCount);

} // namespace optiling
