/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file ada_cast_tiling_data.h
 * \brief TilingData 结构体定义（arch35）
 *
 * ✅ 必须使用标准 C++ struct 定义 TilingData
 * ❌ 禁止使用废弃的 BEGIN_TILING_DATA_DEF 宏
 *
 * 面向 EleWise 范式：blockFormer（512 元素对齐）+ ubFormer（256B 对齐）Tiling，首/尾 block 区分。
 */

#ifndef _ADA_CAST_TILING_DATA_H_
#define _ADA_CAST_TILING_DATA_H_

struct AdaCastTilingData {
    // dim0：元素总数量（1D~4D shape 各维连乘）。
    // 采用 int64_t（与 ops-math_simd 仓兄弟算子一致），实际值由 GetShapeSize() 产出非负，
    // 且 Host 校验非负 + 多核切分避免乘法溢出后，与 uint64 在合法值域 [0, INT64_MAX] 上语义等价；
    // 二进制布局 8B 完全一致，不影响 host/kernel 数据交换。
    int64_t dim0 = 0;
    int32_t coreNum = 0;             // 实际使用的核数（host 动态获取，禁止硬编码）
    int64_t blockFormer = 0;         // 每个核的基础元素数（对齐到 512 元素）
    int64_t blockNum = 0;            // 虚拟 block 数量
    int64_t ubFormer = 0;            // 每个 UB 块的基础大小（256B 对齐）
    int64_t ubLoopOfFormerBlock = 0; // 首 block 的 UB 循环次数
    int64_t ubTailOfFormerBlock = 0; // 首 block 的尾部大小
    int64_t ubLoopOfTailBlock = 0;   // 尾 block 的 UB 循环次数
    int64_t ubTailOfTailBlock = 0;   // 尾 block 的尾部大小
    float pixelQuotient = 0.0f;      // 预计算标量 float32(1.0) / float32(pixel)
};

#endif // _ADA_CAST_TILING_DATA_H_
