/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file eltwise_proto.h
 * \brief
 */
#ifndef OPS_OP_PROTO_INC_ELTWISE_H_
#define OPS_OP_PROTO_INC_ELTWISE_H_

#include "graph/operator_reg.h"
#include "graph/types.h"

namespace ge {

/**
* @brief Computes element-wise operation on a list of tensors.
*        Compatible with Caffe EltwiseLayer.

* @par Inputs:
* Dynamic inputs, including:
* x: A list of tensors with same shape and dtype, count in [1, 32]. Must be one of:
* float16, float32, bfloat16.

* @par Attributes:
* @li N: A required int attribute, count of input tensors.
* @li mode: An int attribute. 0=PRODUCT, 1=SUM (default), 2=MAX.
* @li coeff: A listFloat attribute. Effective only when mode=1; length must equal N.
*            Defaults to empty (treated as all 1.0).

* @par Outputs:
* y: A tensor with same shape and dtype as inputs.

* @par Third-party framework compatibility
* Compatible with the Caffe EltwiseLayer.
*/
REG_OP(Eltwise)
    .DYNAMIC_INPUT(x, TensorType({DT_FLOAT16, DT_FLOAT, DT_BF16}))
    .OUTPUT(y, TensorType({DT_FLOAT16, DT_FLOAT, DT_BF16}))
    .REQUIRED_ATTR(N, Int)
    .ATTR(mode, Int, 1)
    .ATTR(coeff, ListFloat, {})
    .OP_END_FACTORY_REG(Eltwise)

} // namespace ge

#endif // OPS_OP_PROTO_INC_ELTWISE_H_
