/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file split_v_tiling_key.h
 * \brief split_v tiling key declare
 */

#ifndef OP_KERNEL_SPLIT_V_TILING_KEY_H_
#define OP_KERNEL_SPLIT_V_TILING_KEY_H_

#include "ascendc/host_api/tiling/template_argument.h"

/* Mode场景定义 */
#define TILING_KEY_SPLIT_V_PURE_COPY 0
#define TILING_KEY_SPLIT_V_ONE_OUTER 1
#define TILING_KEY_SPLIT_V_GENERAL 2
#define TILING_KEY_SPLIT_V_OTHER 3
#define TILING_KEY_SPLIT_V_SAME_LEN 4
#define TILING_KEY_SPLIT_V_SAME_LEN_COMPACT 5
#define TILING_KEY_SPLIT_V_UNEVEN_COMPACT 6
#define TILING_KEY_SPLIT_V_SAME_LEN_COMPACT_8BIT 7
#define TILING_KEY_SPLIT_V_UNEVEN_COMPACT_8BIT 8
#define TILING_KEY_SPLIT_V_SAME_LEN_PURE_COPY_8BIT 9
#define TILING_KEY_SPLIT_V_UNEVEN_PURE_COPY_16BIT 10
#define TILING_KEY_SPLIT_V_SAME_LEN_INNER_COPY 11
#define TILING_KEY_SPLIT_V_UNEVEN_INNER_ALIGNED_MID 12
#define TILING_KEY_SPLIT_V_SAME_LEN_COMPACT_32BIT 13
#define TILING_KEY_SPLIT_V_UNEVEN_COMPACT_32BIT 14
#define TILING_KEY_SPLIT_V_SAME_LEN_PURE_COPY_WIDE 15
#define TILING_KEY_SPLIT_V_UNEVEN_PURE_COPY_WIDE 16
#define TILING_KEY_SPLIT_V_ONE_ROW_PURE_COPY 17
#define TILING_KEY_SPLIT_V_SAME_LEN_COMPACT_LARGE_OUTER 18
#define TILING_KEY_SPLIT_V_SAME_LEN_COMPACT_DOUBLE_BUFFER 19
/* 继续定义其他Mode场景... */

/* 模板参数 */
ASCENDC_TPL_ARGS_DECL(
    SplitV,
    ASCENDC_TPL_UINT_DECL(schMode, 5, ASCENDC_TPL_UI_LIST, TILING_KEY_SPLIT_V_PURE_COPY, TILING_KEY_SPLIT_V_ONE_OUTER,
                          TILING_KEY_SPLIT_V_GENERAL, TILING_KEY_SPLIT_V_OTHER, TILING_KEY_SPLIT_V_SAME_LEN,
                          TILING_KEY_SPLIT_V_SAME_LEN_COMPACT, TILING_KEY_SPLIT_V_UNEVEN_COMPACT,
                          TILING_KEY_SPLIT_V_SAME_LEN_COMPACT_8BIT, TILING_KEY_SPLIT_V_UNEVEN_COMPACT_8BIT,
                          TILING_KEY_SPLIT_V_SAME_LEN_PURE_COPY_8BIT, TILING_KEY_SPLIT_V_UNEVEN_PURE_COPY_16BIT,
                          TILING_KEY_SPLIT_V_SAME_LEN_INNER_COPY, TILING_KEY_SPLIT_V_UNEVEN_INNER_ALIGNED_MID,
                          TILING_KEY_SPLIT_V_SAME_LEN_COMPACT_32BIT, TILING_KEY_SPLIT_V_UNEVEN_COMPACT_32BIT,
                          TILING_KEY_SPLIT_V_SAME_LEN_PURE_COPY_WIDE, TILING_KEY_SPLIT_V_UNEVEN_PURE_COPY_WIDE,
                          TILING_KEY_SPLIT_V_ONE_ROW_PURE_COPY, TILING_KEY_SPLIT_V_SAME_LEN_COMPACT_LARGE_OUTER,
                          TILING_KEY_SPLIT_V_SAME_LEN_COMPACT_DOUBLE_BUFFER));

/* 模板参数组合 */
ASCENDC_TPL_SEL(ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_UINT_SEL(
    schMode, ASCENDC_TPL_UI_LIST, TILING_KEY_SPLIT_V_PURE_COPY, TILING_KEY_SPLIT_V_ONE_OUTER,
    TILING_KEY_SPLIT_V_GENERAL, TILING_KEY_SPLIT_V_OTHER, TILING_KEY_SPLIT_V_SAME_LEN,
    TILING_KEY_SPLIT_V_SAME_LEN_COMPACT, TILING_KEY_SPLIT_V_UNEVEN_COMPACT, TILING_KEY_SPLIT_V_SAME_LEN_COMPACT_8BIT,
    TILING_KEY_SPLIT_V_UNEVEN_COMPACT_8BIT, TILING_KEY_SPLIT_V_SAME_LEN_PURE_COPY_8BIT,
    TILING_KEY_SPLIT_V_UNEVEN_PURE_COPY_16BIT, TILING_KEY_SPLIT_V_SAME_LEN_INNER_COPY,
    TILING_KEY_SPLIT_V_UNEVEN_INNER_ALIGNED_MID, TILING_KEY_SPLIT_V_SAME_LEN_COMPACT_32BIT,
    TILING_KEY_SPLIT_V_UNEVEN_COMPACT_32BIT, TILING_KEY_SPLIT_V_SAME_LEN_PURE_COPY_WIDE,
    TILING_KEY_SPLIT_V_UNEVEN_PURE_COPY_WIDE, TILING_KEY_SPLIT_V_ONE_ROW_PURE_COPY,
    TILING_KEY_SPLIT_V_SAME_LEN_COMPACT_LARGE_OUTER, TILING_KEY_SPLIT_V_SAME_LEN_COMPACT_DOUBLE_BUFFER)));

#endif // OP_KERNEL_SPLIT_V_TILING_KEY_H_
