/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 *
 * Generated By CANNBot
 */

#ifndef FRESNEL_SIN_H
#define FRESNEL_SIN_H

#include "kernel_operator.h"
#include "kernel_tiling/kernel_tiling.h"
#include "fresnel_sin_tiling_data.h"
#include "fresnel_sin_tiling_key.h"

namespace NsFresnelSin {

using namespace AscendC;

// ====== Cephes Fresnel Sin Coefficients ======
// Source: Cephes fresnl.c / TensorFlow special_math_op_misc_impl.h
// All arrays in Horner (descending degree) order: [0] = highest degree

// Small |x| (x^2 < 2.5625): S(|x|) = |x|^3 * P_SN(x^4) / Q_SD(x^4)
// P_SN: degree 5, 6 coefficients
static constexpr float SN[6] = {-2.99181919401019853726e3f, 7.08840045257738576863e5f,   -6.29741486205862506537e7f,
                                2.54890880573376359104e9f,  -4.42979518059697779103e10f, 3.18016297876567817986e11f};
// Q_SD: degree 6, 7 coefficients (leading coeff = 1.0)
static constexpr float SD[7] = {1.00000000000000000000e0f, 2.81376268889994315696e2f, 4.55847810806532581675e4f,
                                5.17343888770096400730e6f, 4.19320245898111231129e8f, 2.24411795645340920940e10f,
                                6.07366389490084639049e11f};

// Asymptotic f: f = 1 - u * P_FN(u) / Q_FD(u)
// u = 1/(pi^2 * x^4), degree 9, 10 coefficients
static constexpr float FN[10] = {4.21543555043677546506e-1f,  1.43407919780758885261e-1f,  1.15220955073585758835e-2f,
                                 3.45017939782574027900e-4f,  4.63613749287867322088e-6f,  3.05568983790257605827e-8f,
                                 1.02304514164907233465e-10f, 1.72010743268161828879e-13f, 1.34283276233062758925e-16f,
                                 3.76329711269987889006e-20f};
// Q_FD: degree 10, 11 coefficients (leading coeff = 1.0)
static constexpr float FD[11] = {1.00000000000000000000e0f,   7.51586398353378947175e-1f,  1.16888925859191382142e-1f,
                                 6.44051526508858611005e-3f,  1.55934409164153020873e-4f,  1.84627567348930545870e-6f,
                                 1.12699224763999035261e-8f,  3.60140029589371370404e-11f, 5.88754533621578410010e-14f,
                                 4.52001434074129701496e-17f, 1.25443237090011264384e-20f};

// Asymptotic g: g = t * P_GN(u) / Q_GD(u)
// t = 1/(pi * x^2), u = t^2, degree 10, 11 coefficients
static constexpr float GN[11] = {5.04442073643383265887e-1f,  1.97102833525523411709e-1f,  1.87648584092575249293e-2f,
                                 6.84079380915393090172e-4f,  1.15138826111884280931e-5f,  9.82852443688422223854e-8f,
                                 4.45344415861750144738e-10f, 1.08268041139020870318e-12f, 1.37555460633261799868e-15f,
                                 8.36354435630677421531e-19f, 1.86958710162783235106e-22f};
// Q_GD: degree 11, 12 coefficients (leading coeff = 1.0)
static constexpr float GD[12] = {1.00000000000000000000e0f,   1.47495759925128324529e0f,   3.37748989120019970451e-1f,
                                 2.53603741420338795122e-2f,  8.14679107184306179049e-4f,  1.27545075667729118702e-5f,
                                 1.04314589657571990585e-7f,  4.60680728146520428211e-10f, 1.10273215066240270757e-12f,
                                 1.38796531259578871258e-15f, 8.39158816283118707363e-19f, 1.86958710162783236342e-22f};

static constexpr float PI_VAL = 3.14159265358979323846f;
static constexpr float HALF_PI_VAL = 1.57079632679489661923f;
static constexpr float HALF_VAL = 0.5f;
static constexpr float NEG_ONE_VAL = -1.0f;
static constexpr float ONE_VAL = 1.0f;
static constexpr float ZERO_VAL = 0.0f;
static constexpr float QUARTER_VAL = 0.25f;
static constexpr float FOUR_VAL = 4.0f;
static constexpr float ASYM_THRESH = 36974.0f;
static constexpr float SMALL_SQ = 2.5625f;

static constexpr int64_t CALC_BUF_COUNT = 8;
static constexpr int64_t MASK_BUF_COUNT = 3;
static constexpr int64_t CMP_ALIGN_FP32 = 64;
static constexpr int64_t CMP_ALIGN_FP16 = 128;

static constexpr int SN_DEGREE_PLUS1 = 6;
static constexpr int SD_DEGREE_PLUS1 = 7;
static constexpr int FN_DEGREE_PLUS1 = 10;
static constexpr int FD_DEGREE_PLUS1 = 11;
static constexpr int GN_DEGREE_PLUS1 = 11;
static constexpr int GD_DEGREE_PLUS1 = 12;

template <typename T>
class FresnelSin {
public:
    __aicore__ inline FresnelSin() {}
    __aicore__ inline void Init(GM_ADDR x, GM_ADDR y, const FresnelSinTilingData* td);
    __aicore__ inline void Process();

private:
    __aicore__ inline void DoCompute(int64_t n, int64_t computeN);
    __aicore__ inline void ComputeAsymptoticF(AscendC::LocalTensor<float>& b1, AscendC::LocalTensor<float>& b2,
                                              AscendC::LocalTensor<float>& b4, AscendC::LocalTensor<float>& b5,
                                              AscendC::LocalTensor<float>& b6, AscendC::LocalTensor<float>& b7,
                                              uint32_t cN);
    __aicore__ inline void ComputeAsymptoticG(AscendC::LocalTensor<float>& b2, AscendC::LocalTensor<float>& b5,
                                              AscendC::LocalTensor<float>& b6, AscendC::LocalTensor<float>& b7,
                                              uint32_t cN);
    __aicore__ inline void ComputeAsymptoticBranch(AscendC::LocalTensor<float>& b1, AscendC::LocalTensor<float>& b2,
                                                   AscendC::LocalTensor<float>& b3, AscendC::LocalTensor<float>& b4,
                                                   AscendC::LocalTensor<float>& b5, AscendC::LocalTensor<float>& b6,
                                                   AscendC::LocalTensor<float>& b7, AscendC::LocalTensor<uint8_t>& mask,
                                                   uint32_t cN);
    __aicore__ inline void ComputePolynomialBranch(AscendC::LocalTensor<float>& b1, AscendC::LocalTensor<float>& b3,
                                                   AscendC::LocalTensor<float>& b4, AscendC::LocalTensor<float>& b5,
                                                   AscendC::LocalTensor<float>& b6, AscendC::LocalTensor<float>& b7,
                                                   AscendC::LocalTensor<uint8_t>& mask, uint32_t cN);
    __aicore__ inline void HandleSpecialValues(AscendC::LocalTensor<float>& b0, AscendC::LocalTensor<float>& b3,
                                               AscendC::LocalTensor<float>& b4, AscendC::LocalTensor<float>& b5,
                                               AscendC::LocalTensor<uint8_t>& mask,
                                               AscendC::LocalTensor<uint8_t>& maskPInf,
                                               AscendC::LocalTensor<uint8_t>& maskInf, uint32_t cN);
    __aicore__ inline void FinalizeAndOutput(AscendC::LocalTensor<T>& xL, AscendC::LocalTensor<T>& yL,
                                             AscendC::LocalTensor<float>& b0, AscendC::LocalTensor<float>& b1,
                                             AscendC::LocalTensor<float>& b2, AscendC::LocalTensor<float>& b3,
                                             AscendC::LocalTensor<float>& b4, AscendC::LocalTensor<float>& b5,
                                             AscendC::LocalTensor<float>& b6, AscendC::LocalTensor<float>& b7,
                                             AscendC::LocalTensor<uint8_t>& mask,
                                             AscendC::LocalTensor<uint8_t>& maskPInf,
                                             AscendC::LocalTensor<uint8_t>& maskInf, uint32_t cN);

    TPipe pipe;
    TQue<QuePosition::VECIN, 1> qIn;
    TQue<QuePosition::VECOUT, 1> qOut;
    TQue<QuePosition::VECCALC, 1> calcQ[CALC_BUF_COUNT];
    TQue<QuePosition::VECCALC, 1> maskQ;
    GlobalTensor<T> xGM, yGM;
    int64_t blkLen_ = 0, ubLen_ = 0;
};

template <typename T>
__aicore__ inline void FresnelSin<T>::Init(GM_ADDR x, GM_ADDR y, const FresnelSinTilingData* td)
{
    int64_t rem = td->totalNum - td->blockFactor * AscendC::GetBlockIdx();
    blkLen_ = (rem > td->blockFactor) ? td->blockFactor : rem;
    ubLen_ = td->ubFactor;

    xGM.SetGlobalBuffer((__gm__ T*)x + td->blockFactor * AscendC::GetBlockIdx(), blkLen_);
    yGM.SetGlobalBuffer((__gm__ T*)y + td->blockFactor * AscendC::GetBlockIdx(), blkLen_);

    pipe.InitBuffer(qIn, 1, ubLen_ * sizeof(T));
    pipe.InitBuffer(qOut, 1, ubLen_ * sizeof(T));
    for (int i = 0; i < CALC_BUF_COUNT; i++)
        pipe.InitBuffer(calcQ[i], 1, ubLen_ * sizeof(float));
    pipe.InitBuffer(maskQ, MASK_BUF_COUNT, ubLen_ * sizeof(uint8_t));
}

template <typename T>
__aicore__ inline void FresnelSin<T>::Process()
{
    constexpr int64_t CMP_ALIGN = (sizeof(T) == 4) ? CMP_ALIGN_FP32 : CMP_ALIGN_FP16;
    int64_t loops = (blkLen_ + ubLen_ - 1) / ubLen_;
    for (int64_t i = 0; i < loops; i++) {
        int64_t n = (i == loops - 1) ? (blkLen_ - ubLen_ * i) : ubLen_;
        int64_t computeN = ((n + CMP_ALIGN - 1) / CMP_ALIGN) * CMP_ALIGN;
        if (computeN > ubLen_)
            computeN = ubLen_;

        auto xL = qIn.AllocTensor<T>();
        AscendC::DataCopyExtParams copyInParams{static_cast<uint16_t>(1), static_cast<uint32_t>(n * sizeof(T)), 0, 0,
                                                0};
        AscendC::DataCopyPadExtParams<T> padInParams{true, 0, 0, static_cast<T>(0)};
        AscendC::DataCopyPad(xL, xGM[i * ubLen_], copyInParams, padInParams);
        qIn.EnQue(xL);
        DoCompute(n, computeN);
        auto yL = qOut.DeQue<T>();
        AscendC::DataCopyExtParams copyOutParams{static_cast<uint16_t>(1), static_cast<uint32_t>(n * sizeof(T)), 0, 0,
                                                 0};
        AscendC::DataCopyPad(yGM[i * ubLen_], yL, copyOutParams);
        qOut.FreeTensor(yL);
    }
}

template <typename T>
__aicore__ inline void FresnelSin<T>::ComputeAsymptoticF(
    AscendC::LocalTensor<float>& b1, AscendC::LocalTensor<float>& b2, AscendC::LocalTensor<float>& b4,
    AscendC::LocalTensor<float>& b5, AscendC::LocalTensor<float>& b6, AscendC::LocalTensor<float>& b7, uint32_t cN)
{
    // t = 1/(pi*x^2), u = t^2
    Duplicate(b4, PI_VAL, cN);
    Mul(b5, b4, b2, cN);
    Reciprocal(b4, b5, cN);
    Mul(b6, b4, b4, cN);

    // y = 1/(pi*|x|)
    Duplicate(b5, PI_VAL, cN);
    Mul(b5, b5, b1, cN);
    Reciprocal(b7, b5, cN);

    // P_FN(u) via Horner
    Duplicate(b5, FN[0], cN);
    for (int j = 1; j < FN_DEGREE_PLUS1; j++) {
        Mul(b5, b5, b6, cN);
        Adds(b5, b5, FN[j], cN);
    }

    // Q_FD(u) via Horner
    Duplicate(b4, FD[0], cN);
    for (int j = 1; j < FD_DEGREE_PLUS1; j++) {
        Mul(b4, b4, b6, cN);
        Adds(b4, b4, FD[j], cN);
    }

    // f = 1 - u * P_FN/Q_FD
    Div(b5, b5, b4, cN);
    Mul(b5, b5, b6, cN);
    Duplicate(b4, ONE_VAL, cN);
    Sub(b4, b4, b5, cN);
}

template <typename T>
__aicore__ inline void FresnelSin<T>::ComputeAsymptoticG(AscendC::LocalTensor<float>& b2,
                                                         AscendC::LocalTensor<float>& b5,
                                                         AscendC::LocalTensor<float>& b6,
                                                         AscendC::LocalTensor<float>& b7, uint32_t cN)
{
    // P_GN(u) via Horner
    Duplicate(b5, GN[0], cN);
    for (int j = 1; j < GN_DEGREE_PLUS1; j++) {
        Mul(b5, b5, b6, cN);
        Adds(b5, b5, GN[j], cN);
    }

    // Q_GD(u) via Horner
    Duplicate(b7, GD[0], cN);
    for (int j = 1; j < GD_DEGREE_PLUS1; j++) {
        Mul(b7, b7, b6, cN);
        Adds(b7, b7, GD[j], cN);
    }

    // Recompute t = 1/(pi*x^2), then g = t * P_GN/Q_GD
    Duplicate(b6, PI_VAL, cN);
    Mul(b6, b6, b2, cN);
    Reciprocal(b6, b6, cN);
    Div(b5, b5, b7, cN);
    Mul(b5, b5, b6, cN);
}

template <typename T>
__aicore__ inline void FresnelSin<T>::ComputeAsymptoticBranch(
    AscendC::LocalTensor<float>& b1, AscendC::LocalTensor<float>& b2, AscendC::LocalTensor<float>& b3,
    AscendC::LocalTensor<float>& b4, AscendC::LocalTensor<float>& b5, AscendC::LocalTensor<float>& b6,
    AscendC::LocalTensor<float>& b7, AscendC::LocalTensor<uint8_t>& mask, uint32_t cN)
{
    Duplicate(b3, HALF_VAL, cN);

    ComputeAsymptoticF(b1, b2, b4, b5, b6, b7, cN);
    ComputeAsymptoticG(b2, b5, b6, b7, cN);

    // z_reduced = (pi/2) * (x^2 mod 4)
    Duplicate(b6, QUARTER_VAL, cN);
    Mul(b6, b2, b6, cN);
    Floor(b6, b6, cN);
    Duplicate(b7, FOUR_VAL, cN);
    Mul(b7, b6, b7, cN);
    Sub(b6, b2, b7, cN);
    Duplicate(b7, HALF_PI_VAL, cN);
    Mul(b6, b6, b7, cN);

    Cos(b7, b6, cN);
    Sin(b2, b6, cN);
    Mul(b4, b4, b7, cN);
    Mul(b5, b5, b2, cN);
    Add(b4, b4, b5, cN);

    Duplicate(b5, PI_VAL, cN);
    Mul(b5, b5, b1, cN);
    Div(b4, b4, b5, cN);
    Duplicate(b5, HALF_VAL, cN);
    Sub(b4, b5, b4, cN);

    Mul(b6, b1, b1, cN);
    CompareScalar<uint8_t>(mask, b6, SMALL_SQ, CMPMODE::GE, cN);
    Select(b3, mask, b4, b3, SELMODE::VSEL_TENSOR_TENSOR_MODE, cN);
}

template <typename T>
__aicore__ inline void FresnelSin<T>::ComputePolynomialBranch(
    AscendC::LocalTensor<float>& b1, AscendC::LocalTensor<float>& b3, AscendC::LocalTensor<float>& b4,
    AscendC::LocalTensor<float>& b5, AscendC::LocalTensor<float>& b6, AscendC::LocalTensor<float>& b7,
    AscendC::LocalTensor<uint8_t>& mask, uint32_t cN)
{
    Duplicate(b4, ZERO_VAL, cN);
    Div(b5, b4, b4, cN);
    Duplicate(b4, ZERO_VAL, cN);

    Mul(b6, b1, b1, cN);
    Mul(b7, b6, b6, cN);

    Duplicate(b4, SN[0], cN);
    for (int j = 1; j < SN_DEGREE_PLUS1; j++) {
        Mul(b4, b4, b7, cN);
        Adds(b4, b4, SN[j], cN);
    }

    Duplicate(b5, SD[0], cN);
    for (int j = 1; j < SD_DEGREE_PLUS1; j++) {
        Mul(b5, b5, b7, cN);
        Adds(b5, b5, SD[j], cN);
    }

    Div(b4, b4, b5, cN);
    Mul(b5, b6, b1, cN);
    Mul(b4, b4, b5, cN);

    CompareScalar<uint8_t>(mask, b6, SMALL_SQ, CMPMODE::LT, cN);
    Select(b3, mask, b4, b3, SELMODE::VSEL_TENSOR_TENSOR_MODE, cN);
}

template <typename T>
__aicore__ inline void FresnelSin<T>::HandleSpecialValues(
    AscendC::LocalTensor<float>& b0, AscendC::LocalTensor<float>& b3, AscendC::LocalTensor<float>& b4,
    AscendC::LocalTensor<float>& b5, AscendC::LocalTensor<uint8_t>& mask, AscendC::LocalTensor<uint8_t>& maskPInf,
    AscendC::LocalTensor<uint8_t>& maskInf, uint32_t cN)
{
    // Restore sign: S(-x) = -S(x)
    Duplicate(b4, NEG_ONE_VAL, cN);
    Mul(b4, b3, b4, cN);
    CompareScalar<uint8_t>(mask, b0, ZERO_VAL, CMPMODE::LT, cN);
    Select(b3, mask, b4, b3, SELMODE::VSEL_TENSOR_TENSOR_MODE, cN);

    // Handle NaN: override with NaN where x != x
    Duplicate(b4, ZERO_VAL, cN);
    Div(b5, b4, b4, cN);
    Compare(mask, b0, b0, CMPMODE::EQ, cN);
    Select(b3, mask, b3, b5, SELMODE::VSEL_TENSOR_TENSOR_MODE, cN);

    // Handle ±Inf: override with ±0.5
    Duplicate(b4, HALF_VAL, cN);
    Duplicate(b5, -HALF_VAL, cN);
    Select(b4, maskPInf, b4, b5, SELMODE::VSEL_TENSOR_TENSOR_MODE, cN);
    Select(b3, maskInf, b4, b3, SELMODE::VSEL_TENSOR_TENSOR_MODE, cN);
}

template <typename T>
__aicore__ inline void FresnelSin<T>::FinalizeAndOutput(
    AscendC::LocalTensor<T>& xL, AscendC::LocalTensor<T>& yL, AscendC::LocalTensor<float>& b0,
    AscendC::LocalTensor<float>& b1, AscendC::LocalTensor<float>& b2, AscendC::LocalTensor<float>& b3,
    AscendC::LocalTensor<float>& b4, AscendC::LocalTensor<float>& b5, AscendC::LocalTensor<float>& b6,
    AscendC::LocalTensor<float>& b7, AscendC::LocalTensor<uint8_t>& mask, AscendC::LocalTensor<uint8_t>& maskPInf,
    AscendC::LocalTensor<uint8_t>& maskInf, uint32_t cN)
{
    if constexpr (std::is_same_v<T, float>) {
        DataCopy(yL, b3, cN);
    } else {
        Cast(yL, b3, RoundMode::CAST_ROUND, cN);
    }

    calcQ[0].FreeTensor(b0);
    calcQ[1].FreeTensor(b1);
    calcQ[2].FreeTensor(b2);
    calcQ[3].FreeTensor(b3);
    calcQ[4].FreeTensor(b4);
    calcQ[5].FreeTensor(b5);
    calcQ[6].FreeTensor(b6);
    calcQ[7].FreeTensor(b7);
    maskQ.FreeTensor(mask);
    maskQ.FreeTensor(maskPInf);
    maskQ.FreeTensor(maskInf);

    qIn.FreeTensor(xL);
    qOut.EnQue(yL);
}

template <typename T>
__aicore__ inline void FresnelSin<T>::DoCompute(int64_t n, int64_t computeN)
{
    auto xL = qIn.DeQue<T>();
    auto yL = qOut.AllocTensor<T>();

    auto b0 = calcQ[0].AllocTensor<float>();
    auto b1 = calcQ[1].AllocTensor<float>();
    auto b2 = calcQ[2].AllocTensor<float>();
    auto b3 = calcQ[3].AllocTensor<float>();
    auto b4 = calcQ[4].AllocTensor<float>();
    auto b5 = calcQ[5].AllocTensor<float>();
    auto b6 = calcQ[6].AllocTensor<float>();
    auto b7 = calcQ[7].AllocTensor<float>();
    auto mask = maskQ.AllocTensor<uint8_t>();

    uint32_t cN = static_cast<uint32_t>(computeN);

    if constexpr (std::is_same_v<T, float>) {
        DataCopy(b0, xL, cN);
    } else {
        Cast(b0, xL, RoundMode::CAST_NONE, cN);
    }

    Abs(b1, b0, cN);
    Mul(b2, b1, b1, cN);
    Compare(mask, b0, b0, CMPMODE::EQ, cN);

    auto maskPInf = maskQ.AllocTensor<uint8_t>();
    auto maskInf = maskQ.AllocTensor<uint8_t>();
    Duplicate(b4, ONE_VAL, cN);
    Add(b5, b1, b4, cN);
    Compare(maskInf, b1, b5, CMPMODE::EQ, cN);
    CompareScalar<uint8_t>(maskPInf, b0, ZERO_VAL, CMPMODE::GT, cN);

    ComputeAsymptoticBranch(b1, b2, b3, b4, b5, b6, b7, mask, cN);
    ComputePolynomialBranch(b1, b3, b4, b5, b6, b7, mask, cN);
    HandleSpecialValues(b0, b3, b4, b5, mask, maskPInf, maskInf, cN);

    FinalizeAndOutput(xL, yL, b0, b1, b2, b3, b4, b5, b6, b7, mask, maskPInf, maskInf, cN);
}

} // namespace NsFresnelSin

#endif // FRESNEL_SIN_H
