/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file atan_grad_graph_infer.cpp
 * \brief AtanGrad InferDataType: output dtype = input y dtype
 *
 * 复用 canndev 仓 runtime2.0 通用模式（runtime_util.cc InferDtype4SameInput）：
 *   输出 z 的 dtype = 输入 y 的 dtype（idx 0）。
 * canndev 仓原始逻辑保留不删除，当前长尾算子仍使用 canndev 仓代码。
 */

#include "register/op_impl_registry.h"
#include "log/log.h"

using namespace ge;

namespace ops {

static ge::graphStatus InferDataTypeForAtanGrad(gert::InferDataTypeContext* context)
{
    OP_LOGD(context->GetNodeName(), "Begin to do InferDataTypeForAtanGrad");
    const ge::DataType yDataType = context->GetInputDataType(0);
    context->SetOutputDataType(0, yDataType);
    return ge::GRAPH_SUCCESS;
}

IMPL_OP(AtanGrad).InferDataType(InferDataTypeForAtanGrad);

} // namespace ops
