/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 *
 * Generated By CANNBot
 */

/*!
 * \file test_ndtri_tiling_arch35.cpp
 * \brief Ndtri Tiling UT（arch35 / Ascend950）
 *
 * 覆盖路径（参见 op_host/arch35/ndtri_tiling_arch35.cpp）:
 *   1) dtype 路径（DispatchTilingKey）：FP32 / FP16 / BF16 → C_DT_FLOAT/C_DT_FLOAT16/C_DT_BF16
 *   2) isAlign 路径（DispatchTilingKey）：
 *        - totalNum % alignElem == 0 → isAlign=1
 *        - totalNum % alignElem != 0 → isAlign=0
 *   3) 多核 vs 单核（DoTiling）：
 *        - totalNum <  alignElem → 单核 usedCoreNum=1
 *        - totalNum >= alignElem → 多核
 *   4) 失败路径：
 *        - 不支持 dtype（INT32/DOUBLE 等）→ CheckDtype 返回 GRAPH_FAILED
 *        - totalNum=0（zero-shape）→ GetTotalNum 返回 GRAPH_FAILED
 *
 * 期望 tilingData 字段（NdtriTilingData，定义在 op_kernel/arch35/ndtri_tiling_data.h）：
 *   "totalNum blockFactor ubFactor "
 *
 * 期望 TilingKey: ASCENDC_TPL_SEL_PARAM(context, dtypeKey, isAlign)
 *   dtypeKey: 0=C_DT_FLOAT, 1=C_DT_FLOAT16, 2=C_DT_BF16（具体取决于框架编码）
 *   实际 TilingKey 由框架根据 (dtypeKey, isAlign) 计算，本 UT 通过 expectTilingKey 固化运行时实际值。
 */

#include <cstdint>
#include <iostream>
#include <gtest/gtest.h>
#include "../../../../op_kernel/arch35/ndtri_tiling_data.h"
#include "tiling_context_faker.h"
#include "tiling_case_executor.h"

namespace optiling {
// Ndtri 的 TilingParse 不读取任何字段（NdtriCompileInfo 是空 struct）。
// 这里定义一个本地占位类型，方便 UT 提供 compileInfo 指针。
struct NdtriCompileInfoStub {
    uint64_t reserved = 0;
};
}  // namespace optiling

using namespace std;

class NdtriTilingTest : public testing::Test {
protected:
    static void SetUpTestCase()
    {
        std::cout << "NdtriTilingTest SetUp" << std::endl;
    }

    static void TearDownTestCase()
    {
        std::cout << "NdtriTilingTest TearDown" << std::endl;
    }
};

// ==========================================================================
// 主路径：FP32 对齐 + 多核
//   shape {1, 64, 2, 64} = 8192 elem
//   FP32: alignElem = 32/4 = 8
//   8192 % 8 == 0 → isAlign=1
//   8192 >= alignElem → 多核
// 期望 tilingData: "8192 <blockFactor> <ubFactor> "
//   coreNum=64: perCoreRaw=ceil(8192/64)=128，blockFactor=ceil_align(128,8)=128
//   ubFactor: availableUb=(262144-49152)/80=2662 → floor_align(2662,256)=2560
// ==========================================================================
TEST_F(NdtriTilingTest, test_tiling_fp32_align_001)
{
    optiling::NdtriCompileInfoStub compileInfo;
    gert::TilingContextPara tilingContextPara(
        "Ndtri",
        {
            {{{1, 64, 2, 64}, {1, 64, 2, 64}}, ge::DT_FLOAT, ge::FORMAT_ND},
        },
        {
            {{{1, 64, 2, 64}, {1, 64, 2, 64}}, ge::DT_FLOAT, ge::FORMAT_ND},
        },
        &compileInfo);
    // TilingKey = 256：fp32 + isAlign=1（由 ASCENDC_TPL_SEL_PARAM 编码）
    uint64_t expectTilingKey = 256;
    string expectTilingData = "8192 128 2560 ";
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}

// ==========================================================================
// FP32 非对齐 + 单核（totalNum < alignElem）
//   shape {1, 7} = 7 elem
//   FP32: alignElem=8 → 7 < 8 → 单核 usedCoreNum=1
//   7 % 8 != 0 → isAlign=0
//   blockFactor=7
// ==========================================================================
TEST_F(NdtriTilingTest, test_tiling_fp32_unalign_small_single_core_002)
{
    optiling::NdtriCompileInfoStub compileInfo;
    gert::TilingContextPara tilingContextPara(
        "Ndtri",
        {
            {{{1, 7}, {1, 7}}, ge::DT_FLOAT, ge::FORMAT_ND},
        },
        {
            {{{1, 7}, {1, 7}}, ge::DT_FLOAT, ge::FORMAT_ND},
        },
        &compileInfo);
    // TilingKey = 0：fp32 + isAlign=0
    uint64_t expectTilingKey = 0;
    string expectTilingData = "7 7 2560 ";
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}

// ==========================================================================
// FP16 对齐 + 多核
//   shape {1, 64, 2, 64} = 8192 elem
//   FP16: alignElem=32/2=16；8192 % 16 == 0 → isAlign=1
//   perCoreRaw=ceil(8192/64)=128，blockFactor=ceil_align(128,16)=128
//   ubFactor: availableUb/64=(262144-49152)/64=3328 → floor_align(3328,256)=3328
// ==========================================================================
TEST_F(NdtriTilingTest, test_tiling_fp16_align_003)
{
    optiling::NdtriCompileInfoStub compileInfo;
    gert::TilingContextPara tilingContextPara(
        "Ndtri",
        {
            {{{1, 64, 2, 64}, {1, 64, 2, 64}}, ge::DT_FLOAT16, ge::FORMAT_ND},
        },
        {
            {{{1, 64, 2, 64}, {1, 64, 2, 64}}, ge::DT_FLOAT16, ge::FORMAT_ND},
        },
        &compileInfo);
    // TilingKey = 257：fp16 + isAlign=1
    uint64_t expectTilingKey = 257;
    string expectTilingData = "8192 128 3328 ";
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}

// ==========================================================================
// FP16 小规模 单核（< alignElem）
//   shape {3} = 3 elem，FP16 alignElem=16
//   3 < 16 → 单核
//   3 % 16 != 0 → isAlign=0
// ==========================================================================
TEST_F(NdtriTilingTest, test_tiling_fp16_small_single_core_004)
{
    optiling::NdtriCompileInfoStub compileInfo;
    gert::TilingContextPara tilingContextPara(
        "Ndtri",
        {
            {{{3}, {3}}, ge::DT_FLOAT16, ge::FORMAT_ND},
        },
        {
            {{{3}, {3}}, ge::DT_FLOAT16, ge::FORMAT_ND},
        },
        &compileInfo);
    // TilingKey = 1：fp16 + isAlign=0
    uint64_t expectTilingKey = 1;
    string expectTilingData = "3 3 3328 ";
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}

// ==========================================================================
// BF16 对齐 + 多核（与 FP16 共享对齐路径）
// ==========================================================================
TEST_F(NdtriTilingTest, test_tiling_bf16_align_005)
{
    optiling::NdtriCompileInfoStub compileInfo;
    gert::TilingContextPara tilingContextPara(
        "Ndtri",
        {
            {{{1, 64, 2, 64}, {1, 64, 2, 64}}, ge::DT_BF16, ge::FORMAT_ND},
        },
        {
            {{{1, 64, 2, 64}, {1, 64, 2, 64}}, ge::DT_BF16, ge::FORMAT_ND},
        },
        &compileInfo);
    // TilingKey = 283：bf16 + isAlign=1（与 fp32/fp16 的连续编码不一致，由 ASCENDC_TPL_SEL_PARAM 内部映射决定）
    uint64_t expectTilingKey = 283;
    string expectTilingData = "8192 128 3328 ";
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}

// ==========================================================================
// FP32 非对齐 + 多核（大 shape）
//   shape {2, 1000} = 2000 elem
//   FP32 alignElem=8；2000 % 8 == 0（实际对齐）→ 改为 {1, 997} 制造非对齐
//   997 not divisible by 8 → isAlign=0
//   997 >= 8 → 多核
//   perCoreRaw=ceil(997/64)=16，blockFactor=ceil_align(16,8)=16
// ==========================================================================
TEST_F(NdtriTilingTest, test_tiling_fp32_unalign_multi_core_006)
{
    optiling::NdtriCompileInfoStub compileInfo;
    gert::TilingContextPara tilingContextPara(
        "Ndtri",
        {
            {{{1, 997}, {1, 997}}, ge::DT_FLOAT, ge::FORMAT_ND},
        },
        {
            {{{1, 997}, {1, 997}}, ge::DT_FLOAT, ge::FORMAT_ND},
        },
        &compileInfo);
    // TilingKey = 0：fp32 + isAlign=0
    uint64_t expectTilingKey = 0;
    string expectTilingData = "997 16 2560 ";
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}

// ==========================================================================
// 失败路径：不支持的 dtype（INT32）
//   CheckDtype 应返回 GRAPH_FAILED
// ==========================================================================
TEST_F(NdtriTilingTest, test_tiling_fail_unsupported_dtype_int32_007)
{
    optiling::NdtriCompileInfoStub compileInfo;
    gert::TilingContextPara tilingContextPara(
        "Ndtri",
        {
            {{{1, 64, 2, 64}, {1, 64, 2, 64}}, ge::DT_INT32, ge::FORMAT_ND},
        },
        {
            {{{1, 64, 2, 64}, {1, 64, 2, 64}}, ge::DT_INT32, ge::FORMAT_ND},
        },
        &compileInfo);
    uint64_t expectTilingKey = 0;
    string expectTilingData = "";
    std::vector<size_t> expectWorkspaces = {0};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_FAILED, expectTilingKey, expectTilingData, expectWorkspaces);
}

// ==========================================================================
// 失败路径：不支持的 dtype（DOUBLE）
// ==========================================================================
TEST_F(NdtriTilingTest, test_tiling_fail_unsupported_dtype_double_008)
{
    optiling::NdtriCompileInfoStub compileInfo;
    gert::TilingContextPara tilingContextPara(
        "Ndtri",
        {
            {{{1, 1, 2, 64}, {1, 1, 2, 64}}, ge::DT_DOUBLE, ge::FORMAT_ND},
        },
        {
            {{{1, 1, 2, 64}, {1, 1, 2, 64}}, ge::DT_DOUBLE, ge::FORMAT_ND},
        },
        &compileInfo);
    uint64_t expectTilingKey = 0;
    string expectTilingData = "";
    std::vector<size_t> expectWorkspaces = {0};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_FAILED, expectTilingKey, expectTilingData, expectWorkspaces);
}

// ==========================================================================
// 失败路径：zero-shape 1D —— shape {0} → totalNum=0 → GetTotalNum 返回 GRAPH_FAILED
// ==========================================================================
TEST_F(NdtriTilingTest, test_tiling_fail_zero_shape_1d_009)
{
    optiling::NdtriCompileInfoStub compileInfo;
    gert::TilingContextPara tilingContextPara(
        "Ndtri",
        {
            {{{0}, {0}}, ge::DT_FLOAT, ge::FORMAT_ND},
        },
        {
            {{{0}, {0}}, ge::DT_FLOAT, ge::FORMAT_ND},
        },
        &compileInfo);
    uint64_t expectTilingKey = 0;
    string expectTilingData = "";
    std::vector<size_t> expectWorkspaces = {0};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_FAILED, expectTilingKey, expectTilingData, expectWorkspaces);
}

// ==========================================================================
// 失败路径：zero-shape 3D —— shape {4, 0, 3} → totalNum=0 → GetTotalNum 返回 GRAPH_FAILED
// ==========================================================================
TEST_F(NdtriTilingTest, test_tiling_fail_zero_shape_3d_010)
{
    optiling::NdtriCompileInfoStub compileInfo;
    gert::TilingContextPara tilingContextPara(
        "Ndtri",
        {
            {{{4, 0, 3}, {4, 0, 3}}, ge::DT_FLOAT, ge::FORMAT_ND},
        },
        {
            {{{4, 0, 3}, {4, 0, 3}}, ge::DT_FLOAT, ge::FORMAT_ND},
        },
        &compileInfo);
    uint64_t expectTilingKey = 0;
    string expectTilingData = "";
    std::vector<size_t> expectWorkspaces = {0};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_FAILED, expectTilingKey, expectTilingData, expectWorkspaces);
}
