#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# ----------------------------------------------------------------------------
# This program is free software, you can redistribute it and/or modify it.
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This file is a part of the CANN Open Software.
# Licensed under CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING
# BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# ----------------------------------------------------------------------------

# Generated By CANNBot

import sys
import os
import numpy as np
import re


def parse_str_to_shape_list(shape_str):
    shape_str = shape_str.strip('(').strip(')')
    shape_list = [int(x) for x in shape_str.split(",") if x]
    return np.array(shape_list)


def golden_radix_sort(x, descending=False):
    """LSD radix sort golden (8-bit per pass, 256 bins)."""
    N = len(x)
    if N == 0:
        return x.copy(), np.array([], dtype=np.int64)

    indices = np.arange(N, dtype=np.int64)
    sorted_idx = np.zeros(N, dtype=np.int64)

    # Signed integer -> unsigned domain mapping
    if x.dtype == np.int32:
        keys = x.astype(np.uint32) ^ np.uint32(0x80000000)
    elif x.dtype == np.int64:
        keys = x.astype(np.uint64) ^ np.uint64(0x8000000000000000)
    else:
        keys = x.copy()

    byte_width = keys.dtype.itemsize
    num_passes = byte_width
    num_bins = 256
    sorted_keys = np.zeros(N, dtype=keys.dtype)

    for byte_idx in range(num_passes):
        shift = byte_idx * 8
        histogram = np.zeros(num_bins, dtype=np.int64)
        for k in keys:
            digit = (int(k) >> shift) & 0xFF
            if descending:
                digit = 255 - digit
            histogram[digit] += 1

        prefix_sum = np.zeros(num_bins, dtype=np.int64)
        prefix_sum[0] = histogram[0]
        for b in range(1, num_bins):
            prefix_sum[b] = prefix_sum[b - 1] + histogram[b]

        for i in range(N - 1, -1, -1):
            k = keys[i]
            digit = (int(k) >> shift) & 0xFF
            if descending:
                digit = 255 - digit
            prefix_sum[digit] -= 1
            pos = prefix_sum[digit]
            sorted_keys[pos] = k
            sorted_idx[pos] = indices[i]

        keys, sorted_keys = sorted_keys, keys
        indices, sorted_idx = sorted_idx, indices

    # Restore signed integer representation
    if x.dtype == np.int32:
        sorted_values = (keys ^ np.uint32(0x80000000)).view(np.int32)
    elif x.dtype == np.int64:
        sorted_values = (keys ^ np.uint64(0x8000000000000000)).view(np.int64)
    else:
        sorted_values = keys

    return sorted_values, indices


def gen_data_and_golden(shape_str, d_type="int32"):
    d_type_dict = {
        "int32": np.int32,
        "uint32": np.uint32,
        "int64": np.int64,
        "uint64": np.uint64,
    }
    np_type = d_type_dict[d_type]
    shape = parse_str_to_shape_list(shape_str)
    size = int(np.prod(shape))

    # Generate random integer data
    if d_type in ("int32", "int64"):
        tmp_input = np.random.randint(-1000, 1000, size=size).astype(np_type)
    else:
        tmp_input = np.random.randint(0, 2000, size=size).astype(np_type)

    tmp_input = tmp_input.reshape(shape).astype(np_type)
    sorted_values, sorted_indices = golden_radix_sort(tmp_input, descending=False)

    tmp_input.astype(np_type).tofile(f"{d_type}_input_radix_sort.bin")
    sorted_values.astype(np_type).tofile(f"{d_type}_golden_radix_sort.bin")
    sorted_indices.astype(np.int64).tofile(f"{d_type}_golden_radix_sort_indices.bin")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Param num must be 3.")
        exit(1)
    # 清理bin文件
    os.system("rm -rf *.bin")
    gen_data_and_golden(sys.argv[1], sys.argv[2])
