/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file add_mat_mat_elements_proto.h
 * \brief
 */
#ifndef OPS_OP_PROTO_INC_ADD_MAT_MAT_ELEMENTS_H_
#define OPS_OP_PROTO_INC_ADD_MAT_MAT_ELEMENTS_H_

#include "graph/operator_reg.h"
#include "graph/types.h"

namespace ge {

/**
*@brief Calculates the reversed outputs of the function "AddMatMatElements"
*  c = c * beta + alpha * a * b

*@par Inputs:
*Three inputs, including:
* @li c: A mutable Tensor. Must be one of the following types:
*     float16, float32.
* @li a: A mutable Tensor of the same dtype as "c".
* @li b: A mutable Tensor of the same dtype as "c".
* @li beta: A mutable scalar of the same dtype as "c".
* @li alpha: A mutable scalar of the same dtype as "c". \n

*@par Outputs:
* @li c: A mutable Tensor. Has the same dtype as "c". \n

*@par Third-party framework compatibility
* Compatible with the TensorFlow operator AddMatMatElements.
*/
REG_OP(AddMatMatElements)
    .INPUT(c, TensorType({DT_FLOAT, DT_FLOAT16}))
    .INPUT(a, TensorType({DT_FLOAT, DT_FLOAT16}))
    .INPUT(b, TensorType({DT_FLOAT, DT_FLOAT16}))
    .INPUT(beta, TensorType({DT_FLOAT, DT_FLOAT16}))
    .INPUT(alpha, TensorType({DT_FLOAT, DT_FLOAT16}))
    .OUTPUT(c, TensorType({DT_FLOAT, DT_FLOAT16}))
    .OP_END_FACTORY_REG(AddMatMatElements)

} // namespace ge

#endif // OPS_OP_PROTO_INC_ADD_MAT_MAT_ELEMENTS_H_
